### ISSUE TITLE
Too many listeners?

### ISSUE THREAD

**Issue by den1k** [vercel/vercel#1026]
`now deploy`
```
Deploying ~/... under team-name
(node:70059) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upload listeners added. Use emitter.setMaxListeners() to increase limit
(node:70059) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 complete listeners added. Use emitter.setMaxListeners() to increase limit
(node:70059) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by leo** [comment]
@OlliV Since you added the new upload mechanism (it works in `now@7`, we added the new endpoint in version 8), can you please tackle this?

It's caused by [these 3 listeners](https://github.com/zeit/now-cli/blob/bbc1b509f0334ea30e72b5bc125c50d69d6f4045/src/providers/sh/commands/deploy.js#L599-L614) getting registered too often (10 is the default max limit for even listeners in the latest Node.js version that we're using).

**Comment by leo** [comment]
Just documenting this here: We discovered that this is a server-side issue sometimes spawned by an error on the server-side. An endless error loop is then caused on the client, leading the maximum event listener limit getting reached (they're getting registered in a loop).

We're working on fixing the server-side issue!

**Comment by leo** [comment]
Problem solved!
