### ISSUE TITLE
GCP deployment failure

### ISSUE THREAD

**Issue by dudleycarr** [vercel/vercel#1052]
I'm attempting to deploy the minimal micro example from the docs to GCP. The CLI says "Error! API resources failed to deploy"

In GCP Console:
```Deployment failure:
Function load error: Node.js module defined by file index.js is expected to export function named handler
```

`index.js` contains only:
```module.exports = () => 'Ahoy, world!'```

`handler` function is defined, however, in `functions.js`

**Comment by byCedric** [comment]
I would recommend registering on Slack for these kind of questions. There is a rich community available and some of the people are happy to answer these issues 😄 See [zeit.co/chat](zeit.co/chat).

Just by reading the exception I can make out that you are indeed exporting a handler function. But this error describes that you should export your handler function also under the name `handler`. So instead of doing:

```
module.exports = () => 'Ahoy, world!';
```

try doing:

```
module.exports = {
    handler: () => 'Ahoy, world!',
};
```

or even

```
module.exports.handler = () => 'Ahoy, world!';
```

Hope this helps and to see you soon on slack! 😄

**Comment by nmn** [comment]
Had similar problems. Using GCP constantly gave me errors.

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
