### ISSUE TITLE
Always log debug logs to a file 

### ISSUE THREAD

**Issue by jamo** [vercel/vercel#1105]
It would be really helpful when having broken behavior/stuck deployment, to be able to look at now-cli log to see which api call failed
e.g here when demoing `now` it's almost impossible to actually get any idea what went wrong.

<details>

```
$ now --public
> Deploying ~/test/ under email@example.com
> Two manifests found. Press [n] to deploy or re-run with --flag
> [1] package.json	   --npm
> [2] Dockerfile	--docker

> Using Node.js 8.9.4 (default)
> Ready! https://ssl-a-ddjdfvucdl.now.sh (copied to clipboard) [2s]
> Initializing…
```

</details>

Retrying would likely solve the issue, but it would be neat if it would also be possible to look back to the history of failed deployments processes.

**Comment by leo** [comment]
@rauchg can you weight in on this? I think it's a great idea, but I remember you (or maybe someone else from the team) saying that log files aren't good.

**Comment by jamo** [comment]
Alternative ideas also wellcome, but it'd be great to be able to get some more insights to the internals w/o strace and such

**Comment by TooTallNate** [comment]
I think it's a really good idea. Would make user bug reports a lot more reproducible and would make debugging our CI easier as well.

**Comment by leo** [comment]
Tagging this, so someone from the community can look into implementing it. 😊

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
