### ISSUE TITLE
Set MY_CUSTOM_URL from NOW_URL when deploying

### ISSUE THREAD

**Issue by gr2m** [vercel/vercel#1119]
Thank you so much for the amazing tool 💐❤️ 

I have an app that I'd like to utilize the internal app URL stored in `NOW_URL`. I'm currently reading it out form the source code (`process.env.NOW_URL`) but I'd prefer to make the code more deployment target agnostic and set the `MY_CUSTOM_URL` to the value of `NOW_URL`. Is there any way to do that right now?

I'm continuously deploying from travis if that makes any difference, this is the deploy script I'm using

```sh
now="npx now --token=$NOW_TOKEN"

$now rm --safe --yes wip-bot
$now --public
$now alias
```

With configuration in `package.json`

```json
  "now": {
    "alias": "my-alias-here",
    "env": {
      "NODE_ENV": "production"
    }
  }
```

**Comment by leo** [comment]
Sounds a like a very good idea!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
