### ISSUE TITLE
Dynamic proxy with aliases

### ISSUE THREAD

**Issue by seanconnollydev** [vercel/vercel#1136]
Consider this sample `rules.json` file from the [path alias feature](https://zeit.co/docs/features/path-aliases) docs.

```
{
  "rules": [
    { "pathname": "/api/register", "method": ["POST"], "dest": "my-api-register.now.sh" },
    { "pathname": "/api/**", "method": ["GET", "POST"], "dest": "my-api.now.sh" },
    { "dest": "my-ui.now.sh" }
  ]
}
```
This proxy structure works well for a permanent domain environment but what if I wanted to spin up a new environment for feature testing?

The real world scenario is I create a feature branch for my project, I only make changes to the "api register" service and I want to put that in a QA environment for running tests, showing to stakeholders, etc.  Lets call the desired subdomain `my-ui-with-feature.now.sh".

If I just ran `now` from my "api register" directory, that generates a unique deployment for me, e.g. `api-register-wcepelgodl.now.sh`.  If I want `my-ui-with-feature.now.sh` to point to my new service (without also deploying a new version of the "api" service), my `rules.json` needs to look like this:

```
{
  "rules": [
    { "pathname": "/api/register", "method": ["POST"], "dest": "my-api-register.now.sh" },
    { "pathname": "/api/**", "method": ["GET", "POST"], "dest": "api-register-wcepelgodl.now.sh" },
    { "dest": "my-ui-with-feature.now.sh" }
  ]
}
```
I can then push this out with a call to `now alias`.  My QA environment looks like my production environment, except it has a new feature in the "api register" service.

But the problem is that the proxy file needs to be updated every time I and others on my team want to do this.  Is it possible for the `now-cli` to support a dynamic proxy like this or it expected that people might generate new `rules.json` files as part of a script?

**Comment by sconno05** [comment]
After pondering this for a while, it might make sense to support JSON template syntax to allow for dynamic proxies.

So my `rules.json` file might look like this:
```
{
  "rules": [
    { "pathname": "/api/register", "method": ["POST"], "dest": "{{REGISTER_API_HOST}}" },
    { "pathname": "/api/**", "method": ["GET", "POST"], "dest": "{{API_HOST}}" },
    { "dest": "{{UI_HOST}}" }
  ]
}
```

And a `.env.production` file looks like this:
```
REGISTER_API_HOST=my-api-register.now.sh
API_HOST=my-api.now.sh
UI_HOST=my-ui.now.sh
```

And for local development, a `.env` file:
```
REGISTER_API_HOST=http://localhost:3001
API_HOST=http://localhost:3000
UI_HOST=http://localhost:5000
```

Another benefit to this is it allows me to share rule sets across environments.  My local `rules-dev.json` needs to have an identical path routing structure to my production `rules.json`.

And since we've abstracted the values out to environment variables, we can overwrite just one of those values dynamically:

`export LAST_NOW_URL=$(now)` deploys a new instance with a unique URL and stores it in `$LAST_NOW_URL`.

And I can use that to override my default proxies:
UI_HOST=$LAST_NOW_URL now alias ==local-config=
