### ISSUE TITLE
"now dns add" should have a flag to overwrite any existing matching entry

### ISSUE THREAD

**Issue by henderea** [vercel/vercel#1145]
I use a script and `now dns` to have dynamic DNS, but I have to have the script remove the old DNS entries for the subdomain because overwriting isn't the default.

It would be very helpful if I could use a command like `now dns add --overwrite <details...>` to add the new DNS entry while overwriting all others that match.  Matching would be based on everything that uniquely identifies the entry, which would be the domain/subdomain, and possibly other factors for certain record types if applicable.

**Comment by leo** [comment]
Sounds like a very good idea!

**Comment by leo** [comment]
Wrong button 😄

**Comment by henderea** [comment]
Hey, it's been over a month.  I would figure this to be fairly simple.  Any idea when I can expect it?

**Comment by henderea** [comment]
Still nothing happening? This would be very useful to me because my `expect` script doesn't always work right for removing the old entry, and then I end up with 2 entries, one of which won't work, and that means that if I load the page before manually removing the old entry, the page might be broken until the DNS cache of my browser finally resets.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
