### ISSUE TITLE
Circle build fails when releasing a new version, but files are uploaded correctly

### ISSUE THREAD

**Issue by timneutkens** [vercel/vercel#1165]
https://circleci.com/gh/zeit/now-cli/550

**Comment by leo** [comment]
Each build consists out of multiple jobs. The jobs responsible for testing worked out just fine, so the upload started. However, GitHub currently has problems with certain functionalities (as you saw in the tweet), which led to the „upload“ job not completing...

If we want, we can retry it once the problems are fixed. But since the binaries are there, I suppose we‘re fine.

**Comment by leo** [comment]
https://circleci.com/workflow-run/7980946e-b67f-41da-8bc8-694f0960f392
