### ISSUE TITLE
`team ls` should also list team members

### ISSUE THREAD

**Issue by paulogdm** [vercel/vercel#1180]
Today: ![imgur](https://i.imgur.com/csaiPck.png)
Proposed: ![imgur](https://i.imgur.com/S9LCQ2b.png)

Summary: Basically it would be really nice to see all members registered under a team from the CLI.

Request supported by a few users on [Slack](https://zeit.co/chat)
_PS: Imgur album: [https://imgur.com/a/Fg6l2](https://imgur.com/a/Fg6l2)_

**Comment by rauchg** [comment]
I'm getting:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/13041/37223281-df7947d2-2384-11e8-8241-09d466cee055.png">

From the linked images

**Comment by paulogdm** [comment]
@rauchg damn ninjas, just updated it!

**Comment by seanconnollydev** [comment]
👍

**Comment by leo** [comment]
I'm not sure about this, as it would make the output much much longer. But it's interesting!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
