### ISSUE TITLE
`now alias revert`

### ISSUE THREAD

**Issue by mxstbr** [vercel/vercel#1185]
We just deployed some bad code :tm: and had to revert to an earlier alias, but unfortunately it was very hard to figure out what the last deployment URL of the alias was.

It'd be great if the CLI had a command like `now alias revert <alias>` which reverts the last alias of a certain URL.

```sh
now bad-code/
now alias bad-code-asdf123.now.sh production.com
# 10 minutes and lots of error reports later
# Oh shit
now alias revert production.com
```

**Comment by sreeramjayan** [comment]
@mxstbr There is an option to remove an alias `now rm|remove [id]`. Would that help?
https://zeit.co/docs/features/now-cli

**Comment by mxstbr** [comment]
Not quite, since we don't want to remove an alias, we want to roll-back to the last alias that was assigned. Removing the alias to our production application would be horrible :wink:

**Comment by rauchg** [comment]
This is a very interesting idea. I wonder if we should allow for depth? Kinda like git's `HEAD^N` thing. 
CCing @Qix- @leo @OlliV for opinions.

**Comment by Qix-** [comment]
Seeing as how the IETF specifies TLDs can only contain `[a-fA-F]`, we could even opt for the Git-like syntax directly:

```console
$ now alias revert production.com~2
```

**Comment by leo** [comment]
This sounds like a very good idea!

**Comment by ericelliott** [comment]
Just accidentally deployed our staging environment. This super-fast rollback option would be **really** handy right about now! =)

**Comment by codeofsumit** [comment]
same here 😱

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
