### ISSUE TITLE
"now ls" on app names that are valid domains is broken

### ISSUE THREAD

**Issue by andyburke** [vercel/vercel#1261]
If you have an app name like "mysite.com", you can no longer ```now ls mysite.com```. I believe I tracked down the issue and I presented a possible solution:

https://github.com/zeit/now-cli/pull/1260#issuecomment-378819277

However, I wanted to open an issue because this is currently blocking me and I'm not sure what priority comments on existing commits get.

**Comment by andyburke** [comment]
**_As an aside, and I do not require a response to this, just consider it a suggestion:_**

The change that is causing this bug seems to have gone immediately through canary and into a release. Perhaps I'm misunderstanding the git log, but it seems like this change was created and pushed through canary and out to the mainline all within about 4 hours.

I appreciate the idea of moving fast, but perhaps it would be prudent to let things live in canary for 12 or 24 hours as a general rule to give a chance for less common scenarios to arise.

**Comment by leo** [comment]
Thank you for creating this issue @andyburke. You are absolutely right that such things should not go to the stable channel right away - that‘s why the rest of the commits we‘ve made there today will sit on canary for a while first.

However, this PR was an exception because it fixed another issue: `now ls` not accepting deployment URLs directly. In turn, we had to release it immediately.

I understand the inconvenience we might have caused and we‘ll be rolling out a fix shortly.

**Comment by leo** [comment]
Thanks again for your feedback! Here's the fix: https://github.com/zeit/now-cli/pull/1263
