### ISSUE TITLE
Fetching deployment causes error 

### ISSUE THREAD

**Issue by tixtixti** [vercel/vercel#1274]
Using: now 11.0.6 / OSX 10.13.3 / hyper 1.4.8

After using inspect / scale or alias command in now command always error after printing` Fetching deployment `

Example: 

Command: `now alias https://file-xxxxxxxxx.now.sh xx.yyy.ddd` where is yyy.ddd is my domain. 

Output: `> Error! An unexpected error occurred in alias: Error: Fetching a deployment failed
    at module.exports.EventEmitter.findDeployment.hostOrId.retry (/snapshot/repo/dist/now.js:634:15)`

**Comment by alanrubin** [comment]
Same here, other people are experiencing that as well. I guess it is due to the DOS attack. Any estimation when that will be working again?

<img width="1070" alt="screen shot 2018-04-08 at 16 06 01" src="https://user-images.githubusercontent.com/41364/38467874-c154e692-3b46-11e8-96c3-242972168747.png">

**Comment by javivelasco** [comment]
This was due to an issue we had in our `bru` DC. It should work.
