### ISSUE TITLE
now alias should provide a flag to disable touching the scaling rules

### ISSUE THREAD

**Issue by OlliV** [vercel/vercel#1300]
For some users it's a very common use patter to first scale the deployment and then alias. We should probably provide a flag to disable copying the scaling rules.

**Comment by tima101** [comment]
@OlliV Yes, it is actually confusing to have scaling rules for both deployment and alias. What if only alias has scaling rules, will it cover all use cases? I could not think of case where I need to scale deployment on its own. 

Typical flow (for me): I deploy one instance, I test one instance of deployment, then I alias and scale based on alias scaling rules.

**Comment by javivelasco** [comment]
Actually @tima101 there are no scaling rules for an alias but for only deployments. What happens when you alias is that we _copy_ the scaling rules from the deployment where the alias was pointing. In your usual workflow the scaling would be automatic after assigning the alias to the new deployment.

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), there are no scaling rules anymore.

In turn, I'm closing this.
