### ISSUE TITLE
Potential bug: Error! Couldn't find a deployment to alias

### ISSUE THREAD

**Issue by trevordmiller** [vercel/vercel#1307]
I just upgraded to `now` `11.1.4`. I have the following config in my `package.json`:

```javascript
  "now": {
    "alias": "trevordmiller.com",
    "env": {
      "NODE_ENV": "production"
    },
    "scale": {
      "sfo1": {
        "min": 1,
        "max": "auto"
      }
    }
  }
```

After upgrading, I run `now` then `now alias`. Previously this would alias the latest deployment to my production domain. Now it gives me this error:

`Error! Couldn't find a deployment to alias. Please provide one as an argument.`

I know I can fix this with `now alias {deployId} mydomain.com`, but I have automation in place in CI for the alias. So, can the previous behavior of `now alias` using the latest deployment by default be restored? Or is there a way to automate getting the latest deployment ID for the `now alias {deployId} mydomain.com` command?

**Comment by javivelasco** [comment]
Hi @trevordmiller !

When you provide no arguments we still try to find the lastest deployment for the project. The fact that none is found means that you either are in the wrong `context` (maybe your user instead of your team?) or that we can find no deployments for the app name. Please make sure this points and if it still doesn't work, ping me in ZEIT Community Slack:
- The app name is the same as the one you have in `package.json` or the directory if there is none.
- You are in the right context. Verify that the deployment exists by running `now ls <appname>`.

Also, take into account that you can get the deployment url with `now alias $(now deploy) mydomain.com`

**Comment by trevordmiller** [comment]
@javivelasco I've been using now since when it was released so maybe I haven't upgraded something correctly over all the releases. I'm on `11.1.4` currently. The app name is the same as the `name` in the `package.json`. Is the `undefined` in `Deploying ~/repos/trevordmiller-website under undefined` here the problem? Is that the context? How do I fix that?

![image](https://user-images.githubusercontent.com/5497885/38894963-fab93d50-424b-11e8-94d9-1a68fb319ed8.png)

Here is my project repo if it helps (now config is in the `package.json`):
https://github.com/trevordmiller/trevordmiller-website 

Thank you for your time.

**Comment by javivelasco** [comment]
The problem is that your configuration is messed up for some reason. The fact that we are printing `undefined` as the context when you are deploying means that `~/.now/config.json` is corrupt. The deployment still work because the requests are authenticated using your token in `~/.now/auth.json` but we can't find the deployment because we have to use for example the `teamId` to know if you are currently in a team context.

You can `logout` and remove `~/.now/config.json`, then login back and everything should work like a charm. Remember to _always_ manage your config using the `CLI` instead of manually. In any case, I'm curious about how did you get to that situation, it might be related to #1299

Let us know if it works after doing this.

**Comment by trevordmiller** [comment]
@javivelasco Doing `now logout && rm ~/.now/config.json && now login` solved the problem; my context is no longer undefined.

I've never manually touched `~/.now/*` so I'm thinking my config got in a weird state because I've been using now for so long (since it was first released) and maybe something got corrupted along the way with the upgrades.

But no worries, it's fixed now. Thank  you!

![IT crowd](https://media.giphy.com/media/F7yLXA5fJ5sLC/giphy.gif)
