### ISSUE TITLE
Connecting a subdomain as domain to now

### ISSUE THREAD

**Issue by DrJume** [vercel/vercel#1309]
When you want to connect a subdomain, whose nameserver records point to zeit.worlds nameservers the now-cli ignores the subdomain part.

### Example:
I want to connect **now.mydomain.com** to now.
With this I want to have my now deployments accessible as subdomains of the subdomain.
- helloworld.now.mydomain.com
- test.now.mydomain.com

mydomain.com´s DNS is configured externally, so that **now.mydomain.com** points to the zeit.world DNS through NS-Records on the "now." subdomain.

When aliasing, the now-cli wants to _read_ **mydomain.com's** DNS settings and not **now.mydomain.com**'s ones. 
I think the problem is in: _src/providers/sh/commands/alias/setup-domain.js_, where you parse the domain given to the function. 
The parser cuts off all subdomains of the standard domain (mydomain.com), and not the subdomains of the configured now domain, such as **now.mydomain.com**.

**Comment by jch-gh** [comment]
I have also run into this.  The only way I was able to work around it was to instead create a `_now` `TXT` entry in the `mydomain.com` zone, and then a separate `*.now.mydomain.com` `CNAME` record pointing to `alias.zeit.co`, which works, but is less than optimal, given Now cannot manage the domain directly, nor does it take advantage of Zeit's DNS infrastructure.

**Comment by jpbow** [comment]
From Zeit support (which is the same as what @jchappell82 did): "We don't support adding subdomains with now domains, if you want to point your main nameservers somewhere else and use only a certain subdomain add it as external with [CNAME records](https://zeit.co/docs/getting-started/assign-a-domain-name#4.-using-a-custom-domain-with-a-cname)"

**Comment by jch-gh** [comment]
I guess it's good to see that clarified, however, it would be nice if it were documented so that people don't waste many hours trying to get it going in the future.

**Comment by DrJume** [comment]
The thing is, that it is technically possible to use a subdomain, because you can have it point to the zeit-world DNS by adding the NS entry for your sub-domain. 
It doesn't work, because the now cli always tries to contact the DNS of the main domain and not the specified subdomain. 
I think you can make it possible by changing little code ☺️

**Comment by flettling** [comment]
+1

**Comment by jch-gh** [comment]
@johnking I've not had any issues since setting it up with a `*.now.mydomain.com` style CNAME pointing to `alias.zeit.co` on my Route53 managed domain.  I'm on a paid plan with a scaling setup that doesn't allow my app to sleep.  

Do you have any details about what is only working intermittently?  Are you getting `NXDOMAIN` responses from your DNS provider or something else?  Is it possible you're running into timeouts waiting for the app to spin up, rather than actual DNS issues?

**Comment by barbalex** [comment]
this prevents me from using now

Edit: This worked: https://zeit.co/docs/v1/getting-started/assign-a-domain-name#4.-using-a-custom-domain-with-a-cname

**Comment by viztor** [comment]
It's better if we can use subdomain with now as sometimes we only have access to a ns-delegated subdomain.

**Comment by leo** [comment]
Adding subdomains to the dashboard is now possible. Simple click on a project, pick "Domains" in the menu item and then enter your domain.

Even even works with subdomains – in those cases you can use a CNAME:

![image](https://user-images.githubusercontent.com/6170607/64011324-bc95cc00-cb1b-11e9-845f-12e9bce7e5c2.png)

**Comment by viztor** [comment]
> Adding subdomains to the dashboard is now possible. Simple click on a project, pick "Domains" in the menu item and then enter your domain.
> 
> Even even works with subdomains – in those cases you can use a CNAME:
> 
> ![image](https://user-images.githubusercontent.com/6170607/64011324-bc95cc00-cb1b-11e9-845f-12e9bce7e5c2.png)

I'm aware of that. Domain name resolution uses a delegated-based model in its nature. We can't have example.com hosted on one nameserver, and dev.example.com hosted on zeit's nameserver right now. Though it is possible to set up NS record for subdomains in many DNS providers. Something like that would be extra useful for academia, as organizations within can usually get a subdomain's full control but never the root domain. It should be sweet if those can use zeit's NS service, instead of setting up CNAME one by one.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
