### ISSUE TITLE
Secure connection failed on naked domains (without www)

### ISSUE THREAD

**Issue by mojalil** [vercel/vercel#1380]
When assigning a deployment to a domain. The naked domain fails. According to the documentation, this shouldn't be the case. See the screenshot below:

![image](https://user-images.githubusercontent.com/10572843/40694902-46f918d6-63f1-11e8-8f81-4e222d9f5359.png)

* Assigning an alias
![image](https://user-images.githubusercontent.com/10572843/40694994-c33f6bb6-63f1-11e8-967a-c6068b04f1cc.png)

## Steps to replicate
1. Open Firefox
2. Enter metapair.com in the address bar
3. Hit enter

**Comment by javivelasco** [comment]
Hi! You were using an outdated version and it looks like, for some reason, the CLI was trying to request a certificate badly because that error means that there is already a valid certificate for the requested cns while it's not the case since you are getting an SSL error.

Please always update your CLI before opening an issue. This is working nicely in the latest version!
