### ISSUE TITLE
How to transfer out domains purchased through now

### ISSUE THREAD

**Issue by hongymagic** [vercel/vercel#1382]
Can't seem to find and docs online and in CLI. Is there a way?

**Comment by yieme** [comment]
Agree with @hongymagic. Not having easy way to move domains is one reason we don't purchase domains from zeit.

**Comment by willchertoff** [comment]
Any movement on this? I have a few domains I need to transfer out of zeit. I can't find any docs on the matter.

**Comment by paulogdm** [comment]
Please, send an email to support@zeit.co and we will take care of it.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
