### ISSUE TITLE
Use node-keytar for authentication

### ISSUE THREAD

**Issue by pranaygp** [vercel/vercel#1396]
Let's shift to https://github.com/atom/node-keytar for authentication (in addition to storing the `~/.now/auth.json`) file. 

* node-keytar will let us support all OS Specific auth things (like Face ID): For [reference](https://twitter.com/rauchg/status/1004753403795386369?s=19)
* having the `~/now/auth.json` file is important for existing integrations with now like [kap-now](https://github.com/lucaperret/kap-now)

cc: @rauchg

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
