### ISSUE TITLE
Improve confirmation prompt

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#14]
It should specifically buffer and wait for `\n` in all cases. Right now it's hit and miss and arbitrary, based on the `data` event alone.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
