### ISSUE TITLE
Have `now rm` check now.json for name

### ISSUE THREAD

**Issue by seejamescode** [vercel/vercel#1421]
Currently if I do `now rm -s -y`, I get `Error! `now rm` expects at least one argument`.

I would love for that command to read the `now.json` file for the `name` property. This makes it easier to have a single source of truth for the app name when you have multiple `now.json`s with different names.

**Comment by leo** [comment]
Sounds like a very good idea!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
