### ISSUE TITLE
Inconsistent results between ls and inspect

### ISSUE THREAD

**Issue by diogoviannaaraujo** [vercel/vercel#1427]
Hi im getting this strange behavior with scale and inspect:

```
$ now ls

> 28 total deployments found under XXXXX [1s]
> To list more deployments for an app run `now ls [app]`

  app            url                              inst #    type    state    age
  XXXXXX     xxxxx.now.sh         3    NPM     READY    18m

$ now inspect xxxxx.now.sh
> Fetched deployment "XXXXX" in XXXXX [3s]

  Meta
    uid         ASdfaSDfASdfasdfASDF
    name        XXXXX
    state       READY
    type        NPM
    url         xxxx.now.sh
    created     Thu Jun 28 2018 18:50:34 GMT-0300 (-03) [18m]

  Scale
    dc          min        max        current
    sfo1         0          1            1
    bru1         0          0            0

  Events
    2018-06-28T21:50:34.903Z state INITIALIZING
    2018-06-28T21:50:35.802Z build-start
    2018-06-28T21:51:06.914Z build-complete
    2018-06-28T21:51:07.000Z state READY
    2018-06-28T21:51:09.000Z instance-start (sfo1)
```

How can it be using 3 instances if the max is 1?
And why does it shows 3 concurrent instances on ls and just 1 in inspect?

**Comment by Zertz** [comment]
Interesting! I spent a few hours investigating what was wrong with our deployments yesterday 😭 

@rauchg From what I understand, we should take `now ls` (and the web dashboard) with a grain of salt and use `now inspect` to correctly monitor instance count?

**Comment by diogoviannaaraujo** [comment]
Actually, the free plan is considering the ls  for its limits and not the inspect.

 And since ls is not respecting scale rules it’s getting hard to not get an error message telling all instances are full, it fills all slots right after deploy and just a em will resolve

**Comment by JosephScript** [comment]
I'm seeing the same issue. Deployments show up in dashboard as double what is intended, which also reflects in our total number of instances.

**Comment by techno246** [comment]
Same here. 

What's more, if I go to the Usage screen, it gives me a different number each time I refresh the screen (fluctuates between 0, 3, 7).

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
