### ISSUE TITLE
Feature request: Add "--branch" option to cli.

### ISSUE THREAD

**Issue by etoxin** [vercel/vercel#1432]
**User story**
As a developer, I would like the cli option `--branch` that would set the `--name` to the name of the current git branch I'm on.

**Reasoning**
I produce many zeit deploys, normally of a feature or a bugfix in a branch, I normally attach these links to pull requests for review. It would be nice to have a `--branch` cli option that would name the deploy with the current branch I'm currently in.

**example:**
on my hypothetical CLI I'm in the current branch: `origin/feature/ZNC-456-new-component`

**When I run:**
`now --branch`

**it returns the url:**
`https://znc-456-new-component-wtuasd3tr.now.sh`

**Comment by kylemh** [comment]
If this could somehow integrate to also rm the instance when the PR is closed, this could be a really valuable feature.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2

**Comment by kylemh** [comment]
@leo are you certain this doesn't apply anymore? I had subscribed to this issue, because it was something I was hoping to see. I'm excited to see the secrets y'all have in store with Now v2+, but I dont believe anything in the announcement precludes, prevents, or discusses the original issue.

One benefit: instead of hard-coding aliases, it'd be nice to define them on branching strategies.
