### ISSUE TITLE
if a have an empty `now.json` on my projet, I can't run `now` commands

### ISSUE THREAD

**Issue by bukinoshita** [vercel/vercel#1434]
I can run `now` commands normally if I don't have a `now.json` on my project. But If I have an empty `now.json` file in my project, I get an error with `now`.

> Error! No data, empty input in now.json:1:1

Not sure if this is a bug or not, because if I have an object inside `now.json` it works normally. 

Eg: (it works)

```
{
  "name": "now"
}
```

![kapture 2018-07-03 at 13 06 16](https://user-images.githubusercontent.com/6929565/42231460-f7d12564-7ec1-11e8-919a-e8d526679bfb.gif)

**Comment by pranaygp** [comment]
That's expected behaviour @bukinoshita. A project should never have an empty `now.json` file because `now` doesn't know how to parse a file like that, and it was almost certainly created accidentally in the project.

Either delete the `now.json` file, or supply it with a valid configuration. You could also provide an "empty" `now.json` file by setting its contents to `{}`
