### ISSUE TITLE
Error: escSL is not defined

### ISSUE THREAD

**Issue by m-ermolaev** [vercel/vercel#1441]
Hi, could you help me with the error:
`$ now --docker`
`> Deploying C:\projects\app under my@mail.com`
`> Error! escSL is not defined`

I haven't found anything about this message.

I suppose that it can be missing sertificate or similar, but not sure.

PS. I'm using free plan.

Thanx in advance

**Comment by jamo** [comment]
Can you build the Dockerfile locally?

**Comment by m-ermolaev** [comment]
@jamo yes, I can

![ae04ab456bc94aee40431fd941241d98](https://user-images.githubusercontent.com/24371248/42375711-129f9cc6-8125-11e8-9e82-426b673ed6fc.png)

**Comment by jamo** [comment]
Oh, I might have misidentified the actual issue.

Can you share the following information:
- Operating system / version 
- output of `now -v` 
- the full debug output of the deployment: `now -f -d`

cc/ @igorklopov

**Comment by m-ermolaev** [comment]
@jamo sure

- Windows 10 Home / 1803
- 11.2.5 (also tried 11.2.6 on other machine - the same error message)
-
`> [debug] [2018-07-06T11:11:09.959Z] Selected `deploymentType` = "docker"`
`> [debug] [2018-07-06T11:11:09.965Z] Detected `deploymentName` = "films-app"`
`> [debug] [2018-07-06T11:11:09.966Z] Scale presets for deploy: {}`
`> [debug] [2018-07-06T11:11:09.968Z] Getting files`
`> [debug] [2018-07-06T11:11:09.975Z] Locating files C:\projects\films-app`
`> [debug] [2018-07-06T11:11:09.982Z] Error: ReferenceError: escSL is not defined`
`ReferenceError: escSL is not defined`
`    at IgnoreBase._compile (C:\snapshot\repo\node_modules\@zeit\dockerignore\ignore.js:271:23)`
`    at IgnoreBase._match (C:\snapshot\repo\node_modules\@zeit\dockerignore\ignore.js:218:19)`
`    at C:\snapshot\repo\node_modules\@zeit\dockerignore\ignore.js:183:28`
`    at Array.forEach (<anonymous>)`
`    at IgnoreBase._test (C:\snapshot\repo\node_modules\@zeit\dockerignore\ignore.js:182:19)`
`    at IgnoreBase._filter (C:\snapshot\repo\node_modules\@zeit\dockerignore\ignore.js:166:39)`
`    at IgnoreBase._filter (C:\snapshot\repo\node_modules\@zeit\dockerignore\ignore.js:315:19)`
`    at _createClass.value (C:\snapshot\repo\node_modules\@zeit\dockerignore\ignore.js:110:23)`
`    at accepts (C:\snapshot\repo\dist\now.js:16352:24)`
`    at list (C:\snapshot\repo\dist\now.js:16406:10)`
`    at Promise.all.all.map.file (C:\snapshot\repo\dist\now.js:16439:51)`
`    at Array.map (<anonymous>)`
`    at many (C:\snapshot\repo\dist\now.js:16439:39)`
`    at list (C:\snapshot\repo\dist\now.js:16429:14)`
`    at <anonymous>`
`> Error! escSL is not defined`

**Comment by jamo** [comment]
Looks like a bug in the library that parses `.dockerignore`.
https://github.com/zeit/dockerignore/issues/9

**Comment by m-ermolaev** [comment]
@pranaygp https://github.com/lainiwakurafan/films-app/blob/master/.dockerignore

**Comment by pranaygp** [comment]
@lainiwakurafan on an unrelated note, I noticed the [Dockerfile](https://github.com/lainiwakurafan/films-app/blob/master/Dockerfile) on the repo builds a Windows container image, which is something `now` doesn't yet support. You may want to look into building and running a linux container image (seems like it's [supported](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers)).

That said, this is still a bug (`escSL` is an undefined variable) and `dockerignore` shouldn't fail and so that'll be fixed on that repo (https://github.com/zeit/dockerignore/issues/9)

**Comment by eltNEG** [comment]
I had this problem too and I solved this temporarily by not not ignoring sub folders. My .dockerignore file contains somthing like client/node_modules. I needed only the build folder in the client folder. So I moved the build folder outside the client folder so that my .dockerignore file now has client only instead of client/ignored_file.txt and client/ignored_folder.

I hope this helps someone.

**Comment by shanselman** [comment]
I'm seeing this also. Here's my dockerignore.

```
bin\
obj\
out\
publish\
```
