### ISSUE TITLE
Release 11.2.6 is being flagged as a Trojan by my antivirus

### ISSUE THREAD

**Issue by jacklinton** [vercel/vercel#1444]
Or at least that's what my virus protection software seems to think it is. The release autoinstalls and then the virus detector deletes it a few moments after. They went bank and forth like that over 60 times before I woke up this morning.

Antivirus program is Bitdefender and I'm on MacOS High Sierra with a Macbook Pro.

Both of these programs have been running in tandem for at least a year with no problems.

Any advice, suggestions, or possible solutions would be greatly appreciated. I don't want to turn off the always-on virus protection, but I'd also like to use the CLI. For now it seems my computer ain't big enough for the both of 'em.

Thanks for your time.

**Comment by jacklinton** [comment]
@rauchg Sure no problem. It is definitely click-bait-y. I apologize.

**Comment by jacklinton** [comment]
```
7/6/18, 5:16 PM
 
Trojan.MAC.Generic.2690 deleted
 
/private/var/folders/ps/ztgqy3796qj34k7wbcjqg5bw0000gn/T/tmp-48242A0qtZExc61En/now-macos.gz
 ```

**Comment by jacklinton** [comment]
```
7/6/18, 5:17 PM
 
Trojan.MAC.Generic.2690 deleted
 
/usr/local/bin/now
 
 ```

**Comment by alecglassford** [comment]
Maybe you've already seen, but I'm guessing https://github.com/zeit/now-cli/issues/1433 is related.

**Comment by jacklinton** [comment]
I just installed the latest cli release and it hasn't been flagged by the antivirus protection. So, I assume the issue has been resolved, at least for the time being.

**Comment by danreeves** [comment]
I'm also having this problem with Bitdefender for Mac against all versions of now-cli I tried

``` 
Trojan.MAC.Generic.3603 deleted
 
/Users/danreeves/.nvm/versions/node/v10.11.0/lib/node_modules/now/download/dist/now
 
```

edit:

I sidestepped this issue by cloning this repo locally and linking it.

```sh
git clone git@github.com:zeit/now-cli.git
cd now-cli
npm install
npm run link

now --version # yay, it works

```

**Comment by bmv437** [comment]
I'm having the same problem with Bitdefender on macOS. It seems to detect the `now` binary as:
`Application.MAC.Miner.MI`

```
Application.MAC.Miner.MI deleted
 
/Users/bvandegrift/.config/yarn/global/node_modules/now/download/dist/now
```

I've tested with `now` at versions `11.2.5`, `11.4.6`, `12.0.0-canary.89`,
even the binary that's downloaded and installed by `Now Desktop`,
All get picked up by Bitdefender and deleted.

Looks like you can submit a report of a false-positive on Bitdefender's website:
https://www.bitdefender.com/submit/

Unfortunately I can't obtain a copy of the `now` binary to upload since Bitdefender would immediately delete it.
@rauchg Any chance you can work with Bitdefender to see why this get labeled as a virus?

Thanks!

**Comment by jamo** [comment]
Thanks for sharing the url; I just contacted bitdefender.

**Comment by leo** [comment]
@igorklopov What can we do about this? It seems to be a matter of fixing the `pkg` bundle?

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!
