### ISSUE TITLE
Improve error when attempting to buy a domain without cards

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#1456]
```
▲  front/ (master) now domain buy asjddjdasdija.online
> The domain "asjddjdasdija.online" is available to buy under superoxoooo! [1s]
> Buy now for $6 (1yr)? [y|N]
⠧ Purchasing> Error! An unexpected error occurred in domain: Error: No credit cards found (400)
    at responseError (/snapshot/repo/dist/now.js:2491:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
