### ISSUE TITLE
`now rm` output is too verbose when deleting multiple deployments

### ISSUE THREAD

**Issue by OlliV** [vercel/vercel#1473]
![image](https://user-images.githubusercontent.com/1401625/42726918-19e996e8-879d-11e8-9c57-70cb3904b22b.png)

**Comment by OlliV** [comment]
After giving a thought I think it happens because the cli prints out multiple competing spinners and thus the output grows somewhat exponentially. When I removed one deployment it was fine, when I deleted three it printed a bit too many stale lines and when removing over 13 deployments the number of lines printed exploded.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
