### ISSUE TITLE
Update CLI

### ISSUE THREAD

**Issue by bestwestern** [vercel/vercel#1499]
How do I update the CLI?
When I download  now-win.exe from https://zeit.co/download#now-cli
and run it, it tries to deploy (runs now-win...)

PS: the file format is in .gz format which I couldn't extract without downloading software

**Comment by pranaygp** [comment]
@bestwestern We recommend `npm -i g now` on Windows (if you can install Node.js) since it's the easiest way to install and update `now`.

However, if you'd like to use the prebuilt binary, perhaps try the following steps (I don't have a windows machine, so I'm sourcing these from memory/Google. Happy to help you debug problems you run into). I'm also assuming you're using `cygwin` (I'm not too familiar with the alternatives, but I believe there's also bash for windows now?)

1. Download the `.gz` file and place it somewhere (you've already done that)
2. Unzip the file. The preferred way to do so is `gzip -d now-win.exe.gz` (and `gzip` comes pre-installed with Cygwin afaik).
3. Move the `now-win.exe` file into your `C:\Windows\System32` directory
4. In a new Cygwin session, try running `now -v` to check the version and `now -h` to get help

**Comment by bestwestern** [comment]
Thank you - I used npm and succeeded in second attamp.
(I first got this:)
```
C:\Users\Rune\Desktop\Kode\pr\r2>npm install now -g
npm ERR! path C:\Users\Rune\AppData\Roaming\npm\now.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\Users\Rune\AppData\Roaming\npm\now.cmd: node_modules\now\download\dist\now symlink target is not controlled by npm C:\Users\Rune\AppData\Roaming\npm\node_modules\now
npm ERR! File exists: C:\Users\Rune\AppData\Roaming\npm\now.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rune\AppData\Roaming\npm-cache\_logs\2018-08-04T17_39_12_746Z-debug.log)
```
