### ISSUE TITLE
Naming a deployment

### ISSUE THREAD

**Issue by mrmartineau** [vercel/vercel#150]
Apologies if this has been answered already, but is it possible to name a deployment like we used to be able to do with `now-serve`? e.g

```
now -n foobar
```

I do a lot of work with jekyll sites, which all use `_site` as their output folder, so over a few projects, I have multiple items beneathc `_site` when I run `now ls`.

Any ideas?

**Comment by mrmartineau** [comment]
@leo thank you so much! 👏

**Comment by slorber** [comment]
@leo by chance isn't there a way to give a name, and not having the random string being added to it? I mean the randomness/avoiding conflicts can be handled on client side.

For example what if I want to have as name "myApp-gitSha1.now.sh"?

Also, isn't there a way to get deployment name after running now command?

For example, after running now command, I'd like to be able to publish the deployment url somewhere, but it's not really clear how I can do that because the name is random and I can't get the url easily from output

**Comment by mrmartineau** [comment]
@slorber it sounds like you after what now calls an alias. Aliased deployments look like `myApp.now.sh` 

Find out how to alias by running this command: `now alias -h`

Also, i usually alias by running something like this: `now --alias myapp`

Hope that helps

**Comment by slorber** [comment]
No @mrmartineau I am not looking to alias a deployment to a subdomain I own, but to get/control the original deployment url

**Comment by jamo** [comment]
This could indeed be a nice feature or have support for tags/labels for deployments 🤔

**Comment by dheerajmpai** [comment]
@leo  <3
