### ISSUE TITLE
`now aws` throws when no credentials are found

### ISSUE THREAD

**Issue by cangoektas** [vercel/vercel#1502]
When running `now aws` before running `now aws login`, a run-time error is thrown:

<img width="638" alt="screen shot 2018-08-04 at 10 34 25" src="https://user-images.githubusercontent.com/1178516/43674317-61e9b12c-97d2-11e8-89be-82ac874a789d.png">

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.

**Comment by iamstarkov** [comment]
@Leo Documentation says you can opt into AWS Lambdas https://zeit.co/docs/runtimes?query=aws#advanced-usage/advanced-node-js-usage/aws-lambda-api
