### ISSUE TITLE
Custom Domain Alias Setup Error

### ISSUE THREAD

**Issue by robertcoopercode** [vercel/vercel#1505]
I've tried setting up a custom domain with my now.sh deployment following [these instructions](https://zeit.co/docs/getting-started/assign-a-domain-name#4.-using-a-custom-domain-with-a-cname). I've got my deployment working at https://stranger-ipsum-filsjqovug.now.sh, but I'm unable to alias it to https://stranger-ipsum.robertcooper.me/, even after pointing a CNAME to `alias.zeit.co` (confirmed by using [DNS Checker](https://dnschecker.org/#CNAME/stranger-ipsum.robertcooper.me).

When I run the command:

```shell
$ now alias https://stranger-ipsum-filsjqovug.now.sh stranger-ipsum.robertcooper.me
```

I receive the following message in the terminal:

```shell
> Assigning alias stranger-ipsum.robertcooper.me to deployment stranger-ipsum-filsjqovug.now.sh
> Nameservers: dns2.registrar-servers.com, dns1.registrar-servers.com
> Error! No permission to access domain robertcooper.me under robertcooper
```

Any ideas on what needs to be done?

**Comment by timothyis** [comment]
Hi @robertcoopercode! Did you use `now domains add [your domain] --external` to add your domain? I'm sorry the docs are lacking in this area. I'm working on improving them this week.

Furthermore, I recommend using the zeit.world nameservers since it's much easier to control DNS that way and it allows you to enable the Now CDN to cache your assets in over 150 global locations. You can follow the guide here to set that up: https://zeit.co/world#get-started

**Comment by rootandleaves** [comment]
Please help me out !.. getting following error on running: now add domains "xyz.com" --external

`> Error! Unknown error: Error: Invalid serviceType provided
Error: Invalid serviceType provided
    at module.exports.EventEmitter.setupDomain.name.retry (/snapshot/repo/dist/now.js:1878:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
