### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by dieduro** [vercel/vercel#1522]
Trying to deploy an mdx-deck project with now-cli and deploy is ok but url throws me an "Upgrade Required" message on browser and this error in browser's console: `"Failed to load resource: the server responded with a status of 426 ()"`
URL is https://jspresentation-etgesdqdyu.now.sh/

Is there a way to fix this?

**Comment by matheuss** [comment]
It looks like you're running `mdx-deck` in dev mode, which is resulting on two servers: a WebSocket one and an HTTP one. My guess is that `mdx-deck` is first starting up the WebSocket server and only _later_ the HTTP server. Because of that, Now is detecting the WebSocket server and forwarding traffic to it.

I suggest you deploy it as a [Static Deployment](https://zeit.co/docs/deployment-types/static) 👍 It seems to me that [`mdx-deck`'s docs](https://github.com/jxnblk/mdx-deck#pdf-export) are a bit confusing there – they only teach you how to generate a static export way down there cc @jxnblk. Also cc @timothyis because our docs don't do a good job either on explaining how to create a static deployment if you have a `package.json`, for example 🙇

**Comment by jxnblk** [comment]
Yes @matheuss is correct, for a deployment, you'll want to export a static site and deploy the built version. I'll work on making the docs more clear for deploying to now
