### ISSUE TITLE
Optional environment variables

### ISSUE THREAD

**Issue by amio** [vercel/vercel#1524]
Hi there, I have an app using GitHub token (configed in `now.json`) for a higher api requesting quota, but the app works without a token. I wish people could deploy it to Now with:

```bash
now amio/badgen-service
```

It's blocked with an error:

```bash
> Error! No secret found by uid or name "badgen-gh-token"
```

Now I'm using this hack to make it optional:

```bash
now amio/badgen-service -e GH_TOKEN=''
```

But the command looks not sharp anymore, especially with more optional env vars.

Would it be possible to support optional env vars? Maybe like:

```javascript
{
  "env": {
    "GH_TOKEN": "?@badgen-gh-token",
    "TRACKING_GA": "?@badgen-tracking-ga"
}
```

**Comment by amio** [comment]
I can put it in a gitignored `config.json`, but then I have to sync it manually between multiple machines. Anyway, `now secrets` is mean to hold these token, right?

**Comment by sholladay** [comment]
You probably don't even need the gitignored `config.json` at all. Or at least you don't need that `env` section if the variables in there are optional. Think of `env` as _only_ being for required variables. Optional variables should _not_ be in `env`, they should be provided by `-e` instead when they are needed.

`now secrets` is the thing that lets you use the `@my-secret` syntax. You don't need to use that if you don't want to, it's a separate concept from `env` vs `-e`. But it does make it easier to share secrets across deployments, since you can refer to them by name.

In sum, forks of your repo should run this, as you wanted:

```
now amio/badgen-service
```

When they run it like that, `process.env.GH_TOKEN` will be `undefined` instead of an empty string. And that should be fine. If you really need it to be a string, you can do something like `const token = process.env.GH_TOKEN || ''`, but that's probably not necessary.

If people run this:

```
now amio/badgen-service -e GH_TOKEN='foo'
```

... then `process.env.GH_TOKEN` will be `'foo'`.

If they run this:

```
now amio/badgen-service -e GH_TOKEN=@my-secret
```

... then `process.env.GH_TOKEN` will be whatever value they set using `now secrets`. For example, it will be `'blah'` if they did `now secrets add my-secret blah`. If they forgot to use `now secrets` to set the variable, then now will freak out with an error like the one you posted, because it is referencing something that doesn't exist (similar to a `ReferenceError` in JavaScript).

As you can see, there are two different problems going on here. The first is that your users haven't been instructed to use `now secrets`. Currently, they need to use `now secrets` to provide the value because you are using the `@my-secret` syntax. The second problem is that you are making it a required variable by putting it in `env`, whereas you should tell them to provide it with `-e` if you want it to be optional.

**Comment by amio** [comment]
Aha, I see this is the solution:
```
now amio/badgen-service -e GH_TOKEN=@my-secret
```

Formerly I don't want to use `-e` option was because I'm using npm script to do regularly deployments:
```javascript
{
  scripts: {
    "predeploy": "now rm badgen-service --safe -y -T amio || true",
    "deploy": "now -T amio -e API_HOST='https://api.badgen.net'",
    "postdeploy": "now -T amio alias"
  }
}
```
So I didn't want to expose real token in deployment scripts (I think I haven't make this point clear at first). At that time I forgot the `-e` option shares same schema as `now.json`'s `env` (`@my-secret`), no risk to expose token. :D

Thanks!
