### ISSUE TITLE
Support yarn as a package manager

### ISSUE THREAD

**Issue by flintinatux** [vercel/vercel#153]
Was curious to know if there were plans to support [yarn](https://yarnpkg.com/) as a package manager?  We could just detect if a `yarn.lock` was present, and use `yarn install --pure-lockfile` and `yarn start` instead of `npm` commands.

**Comment by j** [comment]
Or delete NPM to get more yarn users ;)

**Comment by sedubois** [comment]
👍 Yes, right now the situation is confusing. I have a Next.js project (https://github.com/relatenow/relate) with a `package.json` and a `yarn.lock`. The `package.json` has script entries `"build": "next build"` and `"start": "next start"`. Locally I run things totally fine with `yarn dev`.

However, when I execute `now`, the console shows that it executes `npm install` anyway, meaning my dependencies aren't respected.

It should run `yarn install` if a `yarn.lock` is present.

**Comment by jewbetcha** [comment]
I'm having the same issue. It's weird, about 50% of the time when I run `now` I get a notice that it's "Using yarn.lock", the other 50% of the time it says "npm install".

**Comment by TooTallNate** [comment]
So, while the now deployment _says_ `npm install`, we're actually spawning our custom node module installer called `ace` which [as of recently has explicit support for `yarn.lock` files](https://zeit.co/blog/faster-javascript-deployments). You can tell when this happens in a deployment because the text `"Using yarn.lock"` is displayed right after the `npm install` line of the deployment, and the module versions in the yarn.lock will be respected.

Please create new issues for any problems you have related to this going forward!
