### ISSUE TITLE
Cannot register alias for deployment

### ISSUE THREAD

**Issue by faridhajnal** [vercel/vercel#1569]
Hello, I have my now deployment (node js) running perfectly. 
I am trying to use my recently acquired domain; however, when I run **now alias** <deployment> <mydomain> I get the following error:

_Error! We couldn't verify the propagation of the DNS settings for mydomain.com_

If i run the 'now domains ls' command, I see my domain listed with **dns external** and **verified true**

My domain was bought and is hosted on Amazon's Route 53, however I seem to not be able to find a good tutorial on how to glue Zeit and Route 53 properly.

On my domain's DNS records, I added a **CNAME** with the value **alias.zeit.co**, as well as a **TXT** record with the hex string given my the now-cli whilst trying to add the external domain to my account.

It has been around 15 hours since I linked the domain and updated its DNS settings.

Please, any help will be much appreciated!

Thanks

**Comment by faridhajnal** [comment]
I close it myself, in case anyone has the same problem.
When I registered the domain to Zeit , I used the naked domain (no www); however when I used the alias command via the now-cli, I was trying to use that very same naked domain. 
As soon as I added www to the custom domain when issuing the alias command, the operation was succesfully executed and now I am able to visit my custom domain and have my now deployment under it.

**Comment by tunnckoCore** [comment]
Doh. Yup, we always should have `CNAME` with `www`, later in page rules we can redirect it if we always want a naked domain.

I don't know how I configured it without much problems the last time before a few months, but now it drove me crazy.

I'm waiting to see if everything works - redirect to naked domain, `SSL: Off` for the acme challange, `SSL: Strict` for all other, `Automatic HTTPS Rewrites` disabled, `Always Use HTTPS` disabled.

This thread may help to someone too: https://spectrum.chat/zeit?thread=48a29851-6ef0-4a10-b546-aacb2c838c36

**Comment by jamo** [comment]
I just took a look into the issue, and it indeed seems that if we request the www.tunnckocore.com (with Cloudflare, and directly to our servers) it works great. 

However, as there is no alias nor a certificate for the tunnckocore.com, all requests targeting our servers will both fail in lack of SSL certificate and then it would 404.

So, we should get the alias for tunnckocore.com working in order to get the setup working as you intended.

**Comment by jamo** [comment]
Btw, what is the A record for tunnckocore.com for?

**Comment by tunnckoCore** [comment]
Thanks for the response!

> Btw, what is the A record for tunnckocore.com for?

It was there, I didn't set that. I think it's the NameCheap's IP (which is strange? because I don't have a hosting from them). I also tried to remove it and still not worked, so I set it back.

> seems that if we request the www.tunnckocore.com (with Cloudflare, and directly to our servers) it works great.

So it's just me and I should wait? Hm.

> So, we should get the alias for tunnckocore.com working in order to get the setup working

So... I should wait, wait and wait, and then remove the alias to `www` and try again to set it to the non-www?

**Comment by tunnckoCore** [comment]
Oh, I found that issue... Searched it for like an hour ;x

Still nothing.

**Comment by lovincyrus** [comment]
Any progress? @tunnckoCore

**Comment by tunnckoCore** [comment]
Oh it seems I didn't report back, but I handled it - `SSL: Off` in the "Page Rules" is the way to go.

Add a rule `*<your-domain>.com/.well-known/acme-challenge/*` with `SSL: Off` setting as a very first (on top) rule.
