### ISSUE TITLE
Chrome OS

### ISSUE THREAD

**Issue by kidandcat** [vercel/vercel#1626]
Hi, it would be awesome if now-cli could be executed as a Chrome App or similar, I would love to work on a Chromebook, I can code in codesandbox and use Zeit Now to launch dev builds, but if I cannot control  now a little bit more (remove older instances for example) from codesandbox, the now web UI and cannot execute now-cli on a Chromebook, I can't use Chrome OS for my workflow.

**Comment by markozxuu** [comment]
Hi, you do not have node js installed on **chrome OS** ? ^-^

**Comment by kidandcat** [comment]
I would need to turn on Developer mode and I don't want to do that. I actually work on Windows, but I use codesandbox and zeit now, the thing is I use now-cli to manage my deploys, but I will not have now-cli in Chromebook without turning it into developer mode (it's like rooting your Android) with the bad consequences it comes with. 

As the now-cli tool works, I think it should be possible to do a port to a chrome app or to the now web UI, for modifying and deleting instances for example.

**Comment by markozxuu** [comment]
@kidandcat I think it's a great idea, but at the moment I do not it's an urgent feature for `now-cli`. Thanks for making the suggestion 🙏 😄

**Comment by markozxuu** [comment]
@kidandcat  I have a surprise for you !! 😸 

## Deployments Web UI Improvements

The "Aliasing deployments" are the last iteration of a project in constant change before putting it into production. Today a Web UI is presented to administer its "deployments" 🎉 

- Create a new "alias" with just one button
- Eliminate their "deployments" individually or in groups (this is so useful because before it could only be done through the "now cli" 😍)

[more info](https://zeit.co/blog/new-deployments-remove-alias)

**Comment by markozxuu** [comment]
@kidandcat If this solves your problem, remember to close this issue 🙏  😺

**Comment by kidandcat** [comment]
Awesome!!
