### ISSUE TITLE
I get “Error! Instance verification timed out (3m)” when deploying

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#1627]
When I’m trying to deploy a Node app to `bru1` I get this error. I have previously done a number of successful deployments, and I have no idea why I get this error. There is nothing in the logs or output that suggests what is wrong.

I have tried `now --no-verify` as well, but no luck. It’s frustrating not being able to deploy my app – and I really don’t want to switch provider. Any idea what might cause this?

**Comment by ghost** [comment]
I can add that it works one in a few times. The only change I did was to change indentation of some code. (But it still doesn’t work most of the times.)

**Comment by kevinburke** [comment]
More debugging information would be helpful when hitting this issue, as well as some reassurance from the Now.js team that this is not an issue with the core software.

**Comment by simsketch** [comment]
I get instance verification timed out frequently, but 99% of the time there is a specific error that caused the timeout. My biggest issue is that things tend to work seamlessly locally but I've been having a lot of problems making a successful deployment. https://github.com/zeit/now-cloud/issues/67

**Comment by kevinburke** [comment]
We are not observing that timeouts are correlated with errors, for us maybe ~90% of the time a client timeout means the deployment succeeded.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2

**Comment by oddmouse** [comment]
I have been having this issue for sometime as well deploying with gitlab-ci. It is a nuisance having to retry the deployments each time to get a pass. Like @kevinburke said, ~90% of the time it deploys fine but it still fails the CI runner. I have noticed this seems to only occur consistently with my two express based deployments, one express and one graphql-yoga.

Closing this issue also concerns me that other v1 issues will not get attention because most of my deployments are Docker based and not compatible with v2 yet.
