### ISSUE TITLE
NOW env var not available when installing dependencies

### ISSUE THREAD

**Issue by brunolemos** [vercel/vercel#1677]
I have this on my `package.json` as a workaround to #1666/#1661:

```json
  "scripts": {
    "patch-package": "if test \"$NOW\" = \"1\"; then cd .; else patch-package; fi",
    "prepare": "yarn patch-package"
  },
```

But the deploy still fails with `**ERROR** patch-package requires Git`, which means the NOW env var is not set in the context of dependencies installation.

Changing to this works:

```json

  "scripts": {
    "patch-package": "cd .",
    "prepare": "yarn patch-package"
  },
```

But it's annoying to do this every time, so I was looking to a solution I can commit to source control.

Could you make NOW be set to 1 inside this context too?

**Comment by robcrocombe** [comment]
Not sure if this helps, but I found out the hard way there are two places to set env vars in `now.json`, and only one is available during the build step (nested inside `build`). So you might want to try setting your own as a temporary solution:

```js
"build": {
  "env": {
    "VAR": "value"
  }
}
```

**Comment by brunolemos** [comment]
~@robcrocombe that works, thanks :)~

~So it seems the issue is only with the built in env vars like `NOW`.~

**Comment by brunolemos** [comment]
Sorry I take it back, custom env vars didn't work on package installation either.

**Comment by robcrocombe** [comment]
Weird. I'm using Cypress's `CYPRESS_INSTALL_BINARY=0` env var to stop it installing and giving me the `"no space left on device"` error, and that seems to work well. This is using the `@now/static-build` builder so the behaviour might be different on others.

**Comment by matthiaskern** [comment]
```
$ now -v
15.5.0
```
Still running into this issue with now v2 only. The environment variables defined in `now.json` are not available at install time.
The culprit in my case is a dependency with a `preinstall` script that checks if a environment variable is set.

**Comment by TooTallNate** [comment]
For Now v2 deployments, you need to check for `NOW_REGION` instead of `NOW`. We decided that the `NOW` env var was redundant so it was not included in the v2 platform.

As far as env vars defined in `now.json`, I just tested build env and runtime env vars for both Now v1 and Now v2, and they are working as expected (the deployments are public, so check the build logs to verify the build-time env vars):

* https://env-vars-v1.n8.io
* https://env-vars-v2.n8.io

Closing this one. Please create a new issue if you are still experiencing any troubles.
