### ISSUE TITLE
Change HTTPS to HTTP

### ISSUE THREAD

**Issue by LintangWisesa** [vercel/vercel#1745]
I built a simple Node.js backend project (using Express.js) that connect to PostgreSQL database. It works fine when I POST to the API using HTTPS protocol. But, I would like to POST the data from my IoT device, that must be in HTTP protocol. How to do that? Thanks in advance.

**Comment by LintangWisesa** [comment]
Marco De Mitri has answered this question on Spectrum Chat Zeit Now. There is no way to disable SSL. All Now deployments are HTTPS by default. Source: https://zeit.co/docs/v1/other/faq#how-do-i-disable-https-and-just-use-http-instead

**Comment by internettrans** [comment]
I would love the ability to turn off https redirects in my Now app.

My app allows hundreds of devs to load js files from their localhost right into my deployed environment, and it's a huge pain walking all the devs through the process of generating ssl certs and getting their localhost server to do ssl, and to get the browser to accept the insecure cert. Might have to switch away from Now so that my users don't have to deal with ssl when locally hosting js files. 😭 😭 😭

**Comment by Abhay304** [comment]
Deploy on Amazon S3,  it provides Http protocol.

**Comment by alipetarian** [comment]
You could use cors anywhere for testing purposes. But its note recommend for production environments. 

https://cors-anywhere.herokuapp.com/

something like: https://cors-anywhere.herokuapp.com/http://yourdomain.com/api

**Comment by joeldenning** [comment]
> Deploy on Amazon S3, it provides Http protocol.

I know alternatives to Now

> You could use cors anywhere for testing purposes. But its note recommend for production environments.

The issue isn't CORS - it's untrusted localhost certificates.

**Comment by alipetarian** [comment]
@joeldenning cors anywhere is on https so, it resolves untrusted issue as well.

**Comment by internettrans** [comment]
@alipetarian cors-anywhere.com cannot retrieve resources from a developer's localhost.

I deleted my comment from before, since I think this conversation isn't very helpful. I've moved on from Now. I do not need help debugging or diagnosing errors, nor do I need suggestions for alternatives to Now.
