### ISSUE TITLE
Feature Request: Shorthand notation for last deployment

### ISSUE THREAD

**Issue by TimoStaudinger** [vercel/vercel#1789]
I might have missed an already existing feature that covers this, bit it would be great to be able to **refer to the most recent deployment with a short-hand notation** when using the CLI.

The use case that comes up most often for me is retrieving logs. I start deploying an app, something goes wrong, and I'd like to read the build logs. Currently, this requires me to either type or copy over the deployment id or URL: `now logs <deployment-id>`.

Instead, it would be awesome if there was a quicker way of saying 'show me the logs of my last deployment'. E.g. `cd` and `git` use a dash for this, [`cd` to represent the previous working directory](https://unix.stackexchange.com/questions/81224/how-to-go-to-the-previous-working-directory-in-terminal), and [`git` for the previous branch](https://github.com/git/git/blob/b21ebb671bb7dea8d342225f0d66c41f4e54d5ca/Documentation/RelNotes/1.6.2.txt#L85).

**What about something along the lines of `now logs -`?**

**Comment by juliangruber** [comment]
That's a great feature suggestion, one I would love to have too!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
