### ISSUE TITLE
Files configuration in now.json

### ISSUE THREAD

**Issue by Siilwyn** [vercel/vercel#1803]
It would be great to have a `files` similar to that in npm's `package.json` to include files. Now provides only a `.nowignore` it seems. Besides introducing another config file it has the downside of spreading related configuration. E.g. using `@now/static` giving it a `src` of `docs/.vuepress/dist/*` and then using the same base path in the ignore:
```
*
!docs/.vuepress/dist
```

**Comment by juliangruber** [comment]
@Siilwyn I'm not sure I understand what you're trying to achieve. Do you wish to supply arrays of files to the `"src"` field?

**Comment by Siilwyn** [comment]
Hi @juliangruber I basically want a whitelist instead of a blacklist, and instead of a seperate file I would like the configuration to reside under a key in the `now.json` file.

**Comment by juliangruber** [comment]
You can include files explicitly like this, although I agree it's awkward:

```json
{
  "version": 2,
  "builds": [
    { "src": "@(foo.txt|bar.txt)", "use": "@now/static" },
  ]
}
```

Would that work for you?

**Comment by Siilwyn** [comment]
That would still require `.nowignore` containing `*` right?

**Comment by juliangruber** [comment]
@Siilwyn sorry, you're right. I set up a test for this and while the `"src"` above will only expose those two files via static file serving, the deployed function will contain all of the files. Is that a problem for you however? Or is it just about not exposing those extra files via the static file server.

**Comment by Siilwyn** [comment]
@juliangruber no problem, both uploading unnecessary files and possibly exposing them are a problem but for me primarily the former.

**Comment by juliangruber** [comment]
Gotcha, I will label this as a feature request :)

**Comment by amccloud** [comment]
@juliangruber this might be a blocker for me too. I think I need the same behavior. Files should be able to be blacklisted by default and only the files references in `builds.src` are uploaded?

I have `monorepo/project-a/src` and it would be nice to not have to wait for all the code in the *monorepo* when I deploy my *project-a* from github

I only want *project-a* but right now I have to wait for all of the projects

```js
{
  "builds": [
    { "src": "./project-a/package.json", "use": "@now/static-build" }
  ]
}
```

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
