### ISSUE TITLE
Unable to deploy to 1.0

### ISSUE THREAD

**Issue by sikhote** [vercel/vercel#1805]
I am attempting to deploy the following:

https://github.com/sikhote/dougpalm.com/commits/master

As you can see from commits, they were deploying successfully a few days ago (via GitHub and via CLI on computer). At the moment, I am seeing this when deploying:

```
$ now
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Deploying ~/Projects/dougpalm.com under sikhote
> Error! You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade
```

Is this documented somewhere or was there notification this would change at a particular time? I saw a note in Spectrum that gave me a clue:
https://spectrum.chat/zeit/now?thread=5d1def00-3504-4618-9ef4-40d64e69f573

Responding to the Spectrum thread, which says that the error message is for new users: I have been using `now` for at least a month or two before this message.

**Comment by ghost** [comment]
I am also having this error.
See my Spectrum thread [here](https://spectrum.chat/zeit/now/cannot-create-now-v1-deployments~d206a0d4-5835-4af5-bb5c-a17f0171fb25).

**Comment by paulogdm** [comment]
Hello! I'm truly sorry to see that you are facing issues. We are not allowing new users to deploy under Now V1. We believe the future is serverless, and even without some features, we are encouraging users to move to our new V2 platform when possible. We will document this shortly.

If you need assistance migrating, you can ask in our [community](zeit.co/chat) or even email support@zeit.co

Please, let me know if you have any further inquiries.

**Comment by sikhote** [comment]
It is understandable to look to prevent more users from V1, but without a viable option for myself and others in this situation (blocked and trying to release a next+custom-node app), what are we to do, besides wait for an indeterminate amount of time before the V2 option is actually working? I suggest rolling back the V1 prevention until the V2 issues (https://github.com/zeit/now-examples/issues/196 and https://github.com/zeit/now-examples/issues/150) are resolved. Until then, I cannot change any current deployments. Is there another path? If I was using Now at work I would be a bit SOL it seems.

**Comment by Aid19801** [comment]
I am also facing issues. Frustrating that you've "closed" this issue. Why would you close it if it remains very obviously unresolved?

**Comment by sikhote** [comment]
There is now a [guide/blog post](https://zeit.co/guides/custom-next-js-server-to-routes/) for how to do server-side routing with Now 2...this was unknown to me before and resolves my issue.

**Comment by theoutlander** [comment]
Goodbye now!

**Comment by vanarok** [comment]
Goodbye

**Comment by mkvlrn-cm42** [comment]
> Hello! I'm truly sorry to see that you are facing issues. We are not allowing new users to deploy under Now V1. We believe the future is serverless, and even without some features, we are encouraging users to move to our new V2 platform when possible. We will document this shortly.
> 

This is what irks me about good platforms sometimes: someone somewhere makes a decision and suddenly the whole paradigm changes. This wouldn't be a problem _**if there was still a choice for the users,**_ but forcing people to migrate "because future lol" is just bad form.

Clearly some people would like to still deploy using v1, like they've been doing for years without issues.

Indeed, goodbye, Now. Hello, Heroku.

**Comment by paulogdm** [comment]
> This is what irks me about good platforms sometimes: someone somewhere makes a decision and suddenly the whole paradigm changes. This wouldn't be a problem if there was still a choice for the users, but forcing people to migrate "because future lol" is just bad form.
> Clearly some people would like to still deploy using v1, like they've been doing for years without issues.
> Indeed, goodbye, Now. Hello, Heroku.

I am truly sorry if our vision of the future doesn't match yours. It is ok to have a different opinion on this one and as a business, we take every bit of feedback into consideration.
Always-up servers have flaws. We always wanted a pure On Demand Serverless platform and we can see how Now 2.0 will bring us closer to that future.

**Comment by user00028** [comment]
Make 2.0 better before you go thrusting it upon us.

**Comment by encloinc** [comment]
I think this is so shady, people should not be forced upon a feature that they dont believe in, some just like the commodity the old now v1 offered. It shoudln't matter what "you" believe but instead what your CUSTOMERS want, the service isn't made or backed by your belifs its backed by the people that use it, and you just lost the trust of a lot of developers.

**Comment by alexw24** [comment]
Yeah lol it's a Friday evening and I have to wait till Monday till theres an engineer in the office with an older zeit account

**Comment by LDubya** [comment]
> Yeah lol it's a Friday evening and I have to wait till Monday till theres an engineer in the office with an older zeit account

That probably won't help you. Just tried to make a new deployment (slightly different version of a pre-existing app) and it says "Deploying to Now 2.0, because this project does not yet exist".

In addition, you can see in their source code [here](https://github.com/zeit/now/pull/2722/files) that they are explicitly deploying to Now 2.0 for any projects created after August 7, 2019:

src/util/prefer-v2-deployment.ts:

    if (project && project.createdAt > 1565186886910) {
        return `Deploying to Now 2.0, because this project was created on Now 2.0. ${INFO}`;
    }

In addition on [their website](https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#platform-version-detection), they now say "Now CLI will automatically upgrade your deployment to the latest platform version if you create a new project".

They also haven't responded to [my discussion on Spectrum](https://spectrum.chat/zeit/general/latest-now-cli-breaks-now-v1-deployments~cec25d1c-db81-42ee-b873-e9bcf53eba53), where I discuss how the latest CLI breaks Now v1 deployment.

It feels as though they have chosen to abandon Now v1 and those plans are in full swing. Even for pre-existing users who signed up when Now was v1 and who continue to use Now v1. I'd love to hear otherwise, but from what I'm seeing, this is my conclusion.

Taking out a napkin and taking some educated guess at the cost structure of running a serverless offering vs traditional, I could see why they'd think it's the move for them to make. The per-user costs of running a serverless hosting business are much lower, probably at least 10x. However, looks like early on they made the mistake of not accounting for the costs of running both a serverless offering and traditional. I know enough about such topics to know that if they're making the move to abandon traditional hosting, then it's because serverless significantly lowers their costs, but it only does so if they can get rid of the fixed costs of running traditional hosting. So, their goal is ultimately to abandon Now v1 entirely. Step one is to prevent new users from using Now v1. Then, as less and less users use Now v1, their fixed costs per-user for running Now v1 will increase to the point to where they will claim it's not profitable and just shut it down. So the best move for anyone using Now V1 (and would like to continue using Now v1 in the long term) would be to start looking for the door. It's highly likely given the facts at hand that Zeit won't be able to support Now V1 in the long term and will shut it down entirely, even for existing users.

**Comment by kelinwu** [comment]
problematic deployment
