### ISSUE TITLE
Create `now help config`/`now config help` command

### ISSUE THREAD

**Issue by timothyis** [vercel/vercel#1822]
We previously suggested using `now config help` to view how to use global configuration, from within the file itself, however, that command does not exist.

It would be useful to have a command that lists briefly what the configuration file does and what it supports to quickly get up and running with it.

Related: #85

**Comment by unitof** [comment]
Were/are you envisioning an API to create/remove/edit `~/.now/config.json` via the command line, or _only_ `now config help` to provide info on what's allowed it in?

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
