### ISSUE TITLE
You tried to create a Now 1.0 deployment. Please use Now 2.0 instead

### ISSUE THREAD

**Issue by Aid19801** [vercel/vercel#1843]
Re opening this as i can't see a resolution anywhere. 👎🏻
error: "You tried to create a Now 1.0 deployment. Please use Now 2.0 instead"

i am trying to deploy a CRON job to Now. First time doing so. It has to be _always up_.
Doesnt seem possible on v2. And v1 is now out of bounds. 

What is the ETA in either:
- allowing new users to deploy always-on to v1
OR
- updating v2 to permit always-up deployments?

Please advise.

**Comment by ll931217** [comment]
I would like to add WSS to this as well, since v2 doesn't support it yet where as v1 does.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
