### ISSUE TITLE
When doing a v1 deploy, throw an error if `.nowignore` is present

### ISSUE THREAD

**Issue by paulmelnikow** [vercel/vercel#1881]
Since `.nowignore` is ignored in a v1 deploy, it would be helpful to let the developer know at deploy time if they try to use it by mistake.

I don't see a reason not to throw an error, though if there is some reason, a warning could suffice!

c.f. https://spectrum.chat/zeit/general/troubleshooting-source-file-selection-in-v1~8dc07b08-99ac-4a02-bfc6-6d40d5e44792?m=MTU0OTQ5MDQ4MDAzNg==

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
