### ISSUE TITLE
Feature request: Build locally with now secrets

### ISSUE THREAD

**Issue by revskill10** [vercel/vercel#1887]
Does now-cli support ability to build locally with injected secrets from `zeit.co` ?
In some cases, we want to build locally the production application with production secrets.
In this case, i mean getting secrets into the `build.env` config from `now.json`.

**Comment by markozxuu** [comment]
@revskill10 Hi, is working on `now-dev` 😸

**Comment by TooTallNate** [comment]
We discussed this internally and decided that it's not a great idea to use production secrets locally. For example, you probably want to connect to a dev database rather than risk any corruption / accidental changes to your production database.

Instead, you're going to have to define a `.env` file in your project directory containing your development env vars for use with `now dev`. See #2048.
