### ISSUE TITLE
Monorepo - rebuild only changed services?

### ISSUE THREAD

**Issue by pie6k** [vercel/vercel#1905]
I've got monorepo with quite a few services.

Quite often I change only one of them and then deploy. Every time, however, all of services are rebuilded and it takes time slowing down entire process.

Is it possible in any way to cache such builds (maybe to 'copy' them from previous deployments)? Or even to update single service in current deplyment?

**Comment by paulogdm** [comment]
This is certainly in our optimization plans for the future!
No, we don't have anything like that at the moment since the platform is ~4 months old.

**Comment by ahmadawais** [comment]
@paulogdm any updates on this. It's useless to have a monorepo because of this behavior.

I have a JSON API and on adding a user, that API which is a static JSON file should only be uploaded.

But Zeit rebuilds 90 serverless lambdas on just one single API JSON static file change.

Also even though the static file is ready as soon as it's uploaded based on the `"@now/static"` builder — it doesn't deploy  right away. All the 90 pages are rebuilt  for no reason and deployed again and only then the latest static file appears.

Which means now I have to separate the Next.js site from all the other things in the monorepo.

**Comment by samohovets** [comment]
Hey @ahmadawais! But if i split my monorepo into different repos, how to deal with routes? For example I have Next.js site on main domain and Gatsby blog on /blog, so I have to proxy to /blog somehow?

**Comment by shayant98** [comment]
Hey everyone, any updates on this?

**Comment by dschoon** [comment]
@shayant98 I just had the same question and came across this: https://vercel.com/docs/monorepos#ignoring-the-build-step

It's located in your project's `/settings/git` view:

![image](https://github.com/vercel/vercel/assets/3638510/b351f160-c998-464c-95cf-cf9dd3100d50)

**Comment by MickL** [comment]
4 years later this is still not implemented. YES we have this "Ignored build step" option, but it is not a good option. From the docs:

> If the command exits with code 0, the build is immediately aborted, and the deployment state is set to CANCELED
> 
> Canceled builds are counted as full deployments as they execute a build command in the build step. This means that any canceled builds initiated using the ignore build step will still count towards your deployment quota.
