### ISSUE TITLE
Feature Request: Set request headers for routes destination

### ISSUE THREAD

**Issue by valoricDe** [vercel/vercel#1912]
Because some external servers need some special headers like `Host` it would be cool to be able to define a field like requestHeaders in now.json -> routes -> { src, dest }

**Comment by robbydooo** [comment]
Just run into this issue, I originally thought that was the purpose of the "headers" option but that is for the response and not the request. This is really needed during the process of migrating our old site to zeit now.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
