### ISSUE TITLE
`now rm` removes also ongoing deployments

### ISSUE THREAD

**Issue by Igloczek** [vercel/vercel#1919]
I'm deploying my apps to Now from Gitlab CI. after successful deployment, I'm aliasing it to dynamically created URL for each branch and then using `now rm -s` remove old not aliased anymore deployments, because are not useful anymore.

And there start the problem, because I can run multiple deployments at the same time, while now rm removes all not aliased deployments, even those not fully deployed with status "INITIALIZING", so it breaks ongoing deployments.

I'm planning to add metadata so these deployments might be reused or just be easier to target them, but still:
- after removing alias, I don't know what was the source of deployment, so it's useless
- after merging the freature, I want to remove all old deployments related to it
- it's waste of resources to keep deployments that are not being in use
- it's just messy when you need to check the admin area and have few hundrets of deployments, while for example only 5 really matters

**Why I'm facing such issues?**
CI pipelines are running concurrently, so even simple tasks like updating old feature branches with current develop can easily create few commits in a short period of time, so when the first deployment will be finished, will run `now rm -s` and break ongoing processes by removing all unfinished deployments.

**Proposed solution**
1. `--safe` shouldn't touch deployments with state other than `ERROR` or `READY`
2. Add new flag - `--finished -F   Skip ongoing deployments`
3. Combine it with metadata (#1917 ) - `now rm status=READY status=ERROR`

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
