### ISSUE TITLE
not work in git bash windows 10

### ISSUE THREAD

**Issue by AlexTexis** [vercel/vercel#1926]
Git version : **2.20.1**
Windows compilation version : **1809**

![now-cli](https://user-images.githubusercontent.com/43657490/53755040-2f7afe80-3e7b-11e9-9b43-5fb9f3c41591.PNG)

**POWER SHELL**

![power-shell](https://user-images.githubusercontent.com/43657490/53755076-40c40b00-3e7b-11e9-8a16-efddaddf9478.PNG)

**NODE COMMAND PROMPT**

![nodecli](https://user-images.githubusercontent.com/43657490/53755140-67824180-3e7b-11e9-9588-205e8f9e3d71.PNG)
 
also applies to version canary 14.1.0

**Comment by juliangruber** [comment]
@AlexTexis can you please share an error message?

**Comment by lfades** [comment]
@AlexTexis Can you try reinstalling git bash and make sure it has access to global scripts ? it has some checkboxes for it in the installation process (AFAIK)

@juliangruber You pinned the wrong person btw 👍

**Comment by fu-sen** [comment]
Until recently the same problem occurred even at npm:
https://github.com/zeit/now-cli/issues/1894

It might be a hint to solve the problem

**Comment by juliangruber** [comment]
@AlexTexis can you please try upgrading to `now-cli@14.1.0-canary.4`? It looks like that fixed it https://github.com/zeit/now-cli/issues/1894#issuecomment-469036886

**Comment by benjaminadk** [comment]
Ive had this problem with `now` and `prisma` as well. ive found that if i run `now.cmd` it works like it should.  i am on windows 10 with git bash for windows.

**Comment by AlexTexis** [comment]
@juliangruber I've already tried it with the version now-cli@14.1.0-canary.4 but it still persists,
I've even replicated it on another computer and there's no answer of git.

**Comment by albertosantini** [comment]
Basically this issue is the same https://github.com/zeit/now-cli/issues/1923.

I see also the issue in `now-cli@14.1.0-canary.4 ` .

**Comment by albertosantini** [comment]
Same issue with `14.1.0` under git bash.

**Comment by NonPolynomial** [comment]
Same issue with `14.2.3` under git bash.

**Comment by entrptaher** [comment]
I got even weirder issue on git bash.
![image](https://user-images.githubusercontent.com/8284972/54878319-1f8c8400-4e55-11e9-9d29-a8bce9edbbf7.png)

Whereas works flawlessly on cmd/powershell.
![image](https://user-images.githubusercontent.com/8284972/54878326-3206bd80-4e55-11e9-81e9-065d0e59c44d.png)

**Comment by lfades** [comment]
I spent some thing debugging this issue in my windows machine, and after doing a clean uninstall of Now and trying a new fresh install I found the following issue with `npm i -g now`:

![Captura](https://user-images.githubusercontent.com/4278345/54939858-97ab8600-4ef7-11e9-8a53-32ca8992214f.PNG)

Uninstalling the package is also not possible:

![Captura2](https://user-images.githubusercontent.com/4278345/54939882-a09c5780-4ef7-11e9-8eea-cf3e9ddb9e80.PNG)

I was unable to fix the issue by looking through the bin files, however to uninstall the package I removed the `now.cmd`  file inside `C:\Program Files\nodejs`.

**Temporal solution:**

Install `Now` directly from the [download page](https://zeit.co/download) instead of using NPM

@juliangruber Running the `now.exe` inside `node_modules`  works, it opens the script asking for a login first, and then it adds the `.now` folder to my user, if I don't do a login whoever it doesn't work again until I remove the `.now` folder

**Comment by NonPolynomial** [comment]
I found a workaround for me:
```
$ alias "now=now.cmd $*"
```

**Comment by mmaedel** [comment]
> alias "now=now.cmd $*"

I found a workaround for me: 

but this is only temporary per instance....

**Comment by NonPolynomial** [comment]
> > alias "now=now.cmd $*"
> 
> I found a workaround for me:
> 
> but this is only temporary per instance....

You can write that in your `~/.bashrc` and then its permanent

**Comment by tpage99** [comment]
Also running into this issue on Windows 10 using git bash. Doesn't respond at all in git bash but does appear to respond to prompts in PowerShell. 

Please don't make me use PowerShell 😢

**Comment by HugoOM** [comment]
Same issue here on Git Bash & Windows 10.

A simple workaround for me is calling it through "npx now" after having installed globally.

Command runs as it should and references the local global instance.

**Comment by albertosantini** [comment]
Here it works with `now 15.2.0` via https://github.com/zeit/now-cli/pull/2322.
