### ISSUE TITLE
deploy after sign up if command was `now [deploy]`

### ISSUE THREAD

**Issue by juliangruber** [vercel/vercel#1934]
This supports a single command sign up and deployment flow, so projects like [frontarm/navi](https://github.com/frontarm/navi/blob/9a87bcdcbfc0f37a24d9488616dff65407606370/examples/blog-typescript/package.json) can use `now` as their deployment script and it works in one command, even if the user doesn't yet have an account.

Currently if you issue `now` as a new user you get the sign up flow but need to run `now` a second time for it to actually do the deploy.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.
