### ISSUE TITLE
Read --token from environment variable

### ISSUE THREAD

**Issue by finnp** [vercel/vercel#1937]
Hey!

Currently our deploy scripts have `--token $NOW_TOKEN --team <team_name` for the `now deploy` and `now alias` commands.

It's a small thing, but I feel like having a standard environment variable like `NOW_TOKEN` and maybe `NOW_TEAM` that the cli would read from could be nice. Then the deploy script would only be `now && now alias`.

Let me know what you think.

**Comment by juliangruber** [comment]
Configuration is hard! I agree that this would be convenient to have, but there's already so many ways to configure the CLI. I've labeled this with `needs community feedback` so we can see how much this is requested.

**Comment by mtiller** [comment]
From my perspective, this is much more than an issue of convenience, it is a security concern.  With many CI systems the build output is logged.  And if it is a public project, often the build logs themselves end up being public.  I recently had this situation where my Now token was published in such a log.  The fact that I cannot hide it behind an environment variables but instead must put it on the command line makes it far too easy for these "secrets" to get exposed.  Just as a matter of best security practices, you should allow for an environment variable.  Yes, it is still possible for somebody to accidentally expose the information in a build log.  But they kind of have to go out of their way to do that while with the current approach, it is nearly impossible to prevent.  IMHO.

**Comment by 1oglop1** [comment]
I expected this a a default and found out it's not implemented yet?
I'd love to have this feature!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
