### ISSUE TITLE
Not found while downloading

### ISSUE THREAD

**Issue by bernardodsanderson** [vercel/vercel#1941]
**OS** - Android/Chrome OS
**Node** - 11.10.1
**`process.platform`** - 'Android'

Similar to #1592, anytime I try installing Now in Termux on my Pixel Chromebook I get the following warning:

![Screenshot 2019-03-10 at 10 28 24 PM](https://user-images.githubusercontent.com/5623786/54098886-80f82180-4384-11e9-90e4-3385121448d0.png)

**Comment by TooTallNate** [comment]
Closing because as of Now CLI >= v16.0.0, we no longer use `pkg` pre-compiled binaries, which was the root of this issue (we never had ARM binaries compiled for `android` platforms).

Please attempt to install Now CLI again (using the latest version) and it should work as expected, and open a new issue if there are still any problems that you experience.
