### ISSUE TITLE
Download secrets from now

### ISSUE THREAD

**Issue by revskill10** [vercel/vercel#1967]
Could now-cli offer ability to pull secrets into a json file ?
In my case, i use `ncc` to compile nodejs to deploy to now instead of using now to compile.

**Comment by tonytamps** [comment]
@revskill10 That compromises the idea of "secrets"
You could access the `process.env.SECRET` on the deployment.
If you needed it inside a specific file you can do something like 
```javascript
const config = require('./config.json');`
config.secret = process.env.SECRET;
otherfile.init(config);
```

**Comment by juliangruber** [comment]
@revskill10 maybe the right way to approach this is to get the Now CLI build step to work for you without having to interface with `@zeit/ncc` directly. Can you describe what isn't working?

**Comment by revskill10** [comment]
@tonytamps that's the point of this feature.
My secrets are saved on now.sh.
I built my application locally for production. So if the now-cli allow for pulling secrets at build time, i could inject them into my application without any `config.json`

**Comment by revskill10** [comment]
@juliangruber My pipeline is like this:
```js
ncc src/index.js > deploy/index.js
now 
```
So i think, with this feature, the pipeline could be
```js
now pull-secrets > secrets.json
ncc src/index.js > deploy/index.js
rm secrets.json
now 
```

**Comment by juliangruber** [comment]
Why are you running `ncc` before you run `now`? If you use any of the Now node bundlers it will run `ncc` for you, _and_ expose the secrets at build time.

You could have a config like this:

```json
{
  "version": 2,
  "builds": [
    { "src": "**.js", "use": "@now/node" }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "src/index.js" }
  ]
}
```

**Comment by revskill10** [comment]
@juliangruber Because i don't want to use `now` to build, i just use it to run my application only.
I could use `ncc` to build locally or on a separate CI instead of `now`.
So the built `index.js` must have injected `now secrets` at build time.

**Comment by TooTallNate** [comment]
Now Secrets support is on the roadmap for `now dev` (https://github.com/zeit/now-cli/pull/1883). I think that is ultimately the tool that you are looking for.

**Comment by revskill10** [comment]
@TooTallNate My use case, i think is simple. Maybe a subcommand like `now secrets download > secrets.json` might work.
In my case, if i work from multiple locations, it should be easy to pull secrets from anywhere.
For integration testing, i need to bundle my application locally to run the test with pupeteer before deployment.

**Comment by TooTallNate** [comment]
Closing because we won't be adding this feature after all. For `now dev`, you can create a `.env` or `.build.env` file in your project and `now dev` will use those values when running your project locally.

In general, you should also be using different API keys / databases / etc. during development vs. production, so that is another reason why pulling production secrets is not supported.

**Comment by chad-codes** [comment]
I hate comment on an old issue, but I think not enabling user's to view the secrets they add is a regression to having secrets in general. I don't know of any secrets tools that don't allow their users to view the secrets they created while having the correct permissions and roles. I've only worked with HashiCorp Vault, AWS Parameter Store, and AWS Secrets Manager, but they all allow for viewing of secrets so long as the correct roles and permissions are attached to the user that's trying to view them. But there may be other tools that are like a black box too, I just haven't used them.

Is the primary reason for not allowing for this because proper roles, policies, and audit logging aren't in place for Zeit Now? Is it to be opinionated? Or is to "re-invent" how secrets are thought of and used? Genuinely curious.

**Comment by revskill10** [comment]
@CGreenburg In this case, the only answer is: vendor lockin. As you said, it's not related to security concern. You're foced to use `now` to build application to run on zeit platform instead of building on your own CI and deploy to another hosting platform.

I have no comment on this, as it's Zeit's business decision. Hope to hear more from the team on this issue, too.

**Comment by tonytamps** [comment]
>In this case, the only answer is: vendor lockin - @revskill10

Haha, alright. Calm down.

>But there may be other tools that are like a black box too - @CGreenburg 

Most CI/CD pipelines work like this. It's really not that big a deal.
In my experience: if you need to be viewing them or fetching them you're misusing the tools. There are alternative methods to what you're trying to achieve that are safer.

**Comment by jaydenseric** [comment]
I'm trying to migrate a Now v1 GraphQL API to Heroku (v2/severless is not an option here due to poor multipart request support, etc.), and I'm struggling to dig out what the values for all 14 of my production secrets were. This is a form of lockin. Yes, I can figure out what they all were the hard way, but that's what lockin is: Inconvenience.
