### ISSUE TITLE
Managing secrets with the same name but different values across several apps

### ISSUE THREAD

**Issue by GaelS** [vercel/vercel#1986]
Hello,

First of all, thanks for your great work, **now** is an awesome tool to use. 
Regarding my issue, I might be doing something wrong or not seeing the obvious but I don't find a good solution: 

I have two apps, both using a variable `@client_id` with a specific value for each app. However, as I understand so far, when one runs `now secret add foo bar` the variable `foo` will be the same across all my apps deployed on my zeit account.

How would it be possible to set a different value of `client_id` depending on which app is using it ? Can it be namespaced in some way ? Is there something on the Zeit dashboard that I am missing ?

Thank you.

**Comment by OlliV** [comment]
I would prefix the secrets with something, e.g. `app1_secret` and `app2_secret` and configure those in the respective `now.json` files.

**Comment by GaelS** [comment]
Hmm...yes, this is my solution as well for now but I'm wondering if a "cleaner" solution exists :thinking: 
And if not, would it be an interesting feature to add ?

**Comment by homerjam** [comment]
This is really needed. I would even suggest different secrets per target. And we should be able to view these a la Heroku IMO.

**Comment by unr** [comment]
Another scenario: deploying multiple versions of the same app for testing stages. 

Our Development environment has different env vars than Production & Staging environments. ~Need a way of easily swapping these, other than simply prefixing everything / adding additional logic to check for which deploy type in our builds.~

I'm realizing now I could probably use `now.prod.json`, set up the secrets there, and deploy with `now --local-config=now.prod.json` 🤔

**Comment by homerjam** [comment]
> I'm realizing now I could probably use `now.prod.json`, set up the secrets there, and deploy with `now --local-config=now.prod.json` 🤔

I've done something similar - I have a script which reads an `.env` file and appends the values to `now -e`. Would be great to have an `--env-file` flag that did this within the cli itself.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
