### ISSUE TITLE
[now-cli] now inspect <deployment> should show deployment region

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#1999]
**Is your feature request related to a problem? Please describe.**
Right now it is impossible to see which region a deployment (v2) was deployed to.
In `now-cli` the `now inspect ...` command only shows

```
    version	2
    id		---
    name	---
    readyState	READY
    url		---
```

**Describe the solution you'd like**
Show show deployment region.

<img width="507" alt="Screenshot 2019-03-16 at 12 12 06" src="https://user-images.githubusercontent.com/179761/54470581-3db70c00-47e5-11e9-9d51-fde9871ecbb3.png">

**Describe alternatives you've considered**
Add a row to show region.

**Additional context**
In the web dashboard, is info is already showing under each deployment.

<img width="665" alt="Screenshot 2019-03-16 at 12 12 14" src="https://user-images.githubusercontent.com/179761/54470574-2ed05980-47e5-11e9-86fc-c9bec5bcbe2c.png">

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
