### ISSUE TITLE
`main` should support skipping the `.js` suffix

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#2]
Right now if a user specifies `main` in `package.json`, we expect it to have a `.js` suffix, but npm supports without.

**Comment by codyzu** [comment]
@rauchg I have been looking into this issue.

Can you clarify the expected vs actual behavior?

According the the [npm docs](https://docs.npmjs.com/files/package.json#main), `main` is only used to define the default import when a consumer requires (or imports) an npm module. This is also described in the [node.js module docs](https://nodejs.org/api/modules.html#modules_all_together).

Can you describe clarify the issue because it is not clear to me how this relates to now?

Thanks! and thanks for now, hyper, and everything zeit!!!

**Comment by leo** [comment]
@TooTallNate

**Comment by TooTallNate** [comment]
Is this related to file upload whitelisting, and forcing the `main` file to be included in that whitelist?

**Comment by leo** [comment]
@TooTallNate Two things:

1. Are we throwing an error if `.js` is missing, maybe?
2. Are we using the property to run `node <main-file>`, maybe (which then only works with the extension, not without it)?

I don't think it's about file upload whitelisting... 🤔
