### ISSUE TITLE
See lambda invocation count / usage information? 

### ISSUE THREAD

**Issue by josh-byster** [vercel/vercel#2001]
I'm not sure if this feature already exists but I've been looking and can't find it. I'd love to have some metrics on invocations for my lambda methods, bandwidth usage, etc. each day. It'd be nice to know how close I get to the free tier usage for my deployments.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.
