### ISSUE TITLE
inconsistent copy  to clipboard behaviour (now --target stage does not copy URL to clipboard)

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2008]
When a deployment is made with `now` or `now --target production`, the deployment URL is copied to clipboard.

When a deployment is made with `now --target staging`, the deployment URL **is not copied to clipboard**. 

<img width="756" alt="Screenshot 2019-03-22 at 15 57 04" src="https://user-images.githubusercontent.com/179761/54808429-2aabac80-4cbb-11e9-99c8-5e1b2f01721f.png">

**Comment by wiiiimm** [comment]
It is related to https://github.com/zeit/now-cli/issues/2007

When a deployment is made with `now` or `now --target production` only 1 alias is returned

When a deployment is made with `now --target staging`, more than 1 aliases is returned `aliasFinal.length > 1`

It confuses the `shouldCopy` logic at

https://github.com/zeit/now-cli/blob/master/src/commands/deploy/latest.js#L102

**Comment by andymckay** [comment]
Sorry, its been a while since this issue was filed. In the meantime the feature of copying to the clipboard has been deprecated and is no longer used as per the code here: https://github.com/vercel/vercel/blob/49f453742b190c989447bedf3c85947287086688/packages/cli/src/commands/deploy/index.ts#L202-L211.

So I think we can close this issue. Thank you for the original issue.
