### ISSUE TITLE
`now dev` routing errors

### ISSUE THREAD

**Issue by raulg** [vercel/vercel#2023]
Please assign now dev tag, and good work getting closer to public release.

Getting `Error: Unable to encode undefined of type undefined` when trying to navigate directly to a page defined in the routes, `/page?uid=$uid` in a project integrating Prismic. Client-side routing works as usual.
Issue seems to be when `getInitialProps` is called and tries to fetch using the Prismic API
```
const API = await Prismic.getApi(apiEndpoint, { req, accessToken });
const document = await API.getByUID('page', uid);
```
Works without any issues when deployed in Now v2.
Repository to replicate error
https://github.com/raulg/nextjs-blog/tree/Serverless-Now

**Comment by TooTallNate** [comment]
Thank you for the repro instructions, I am taking a look into this.

**Comment by raulg** [comment]
There are still some issues when converting to regexp for matching the routes. For the following routes configuration, it would catch routes beginning with `/preview?` as the second route `page?uid=preview` despite it being lowest priority

```
"routes": [
    { "src": "/preview\\?(?<query>.*)", "dest": "/preview?query=$query" },
    { "src": "/(?<uid>[^/]+)$", "dest": "/page?uid=$uid" }
  ]
```
Attempted to work around it by defining it more specifically 
```
{ "src": "/(?!preview)(?<uid>[^/]+)$", "dest": "/page?uid=$uid" }
``` 
which fixed the wrong routes issue, but it returned `/page?uid=undefined` for all regular pages. Figured it was a problem with regexp not handling well named groups, so modified it into `{ "src": "/(?!preview)(?<uid>[^/]+)$", "dest": "/page?uid=$1" }` which does work for this case, but is not the best, plus routes end up very different from the [Now definition](https://zeit.co/docs/v2/deployments/configuration/#routes)

There's also the difference in how querystring is handled, but that was an easy workaround, just capture and pass it.

**Comment by raulg** [comment]
@TooTallNate Could this issue be reopened?

**Comment by heysailor** [comment]
Hi @TooTallNate and @leo  - there is still an issue with `now dev` routing - capture groups are not being passed. I'm using now cli version 15.0.11-canary.3 dev with next.js version 8.1.0.

Given a `now.json` routes entry like this: 

```
  "routes": [
    {
      "src": "/redirect?dest=(.*)",
      "status": 301,
      "headers": {
        "Location": "https://google.com/$1"
      }
    },
    {
      "src": "/hello/(?<name>.+)$",
      "dest": "/hello?name=$name"
    }
  ]
```

and a simple `pages/hello/index.js` to display a parameter: 

```
function Hello({ name }) {
  return <div>Welcome to Next.js! | Hello {name}</div>;
}

Hello.getInitialProps = ({ query }) => {
  console.log('Query is', query);
  return { name: query.name };
};

export default Hello;
```

Loading the path `/hello/there` returns "Welcome to Next.js! | Hello " when served with `next dev`, and "Welcome to Next.js! | Hello there" when served from a now deployment. The query logged to console is `{}` with now dev.

Likewise, the redirect path loads the `pages/redirect` rather than sending a 301 Location header.

[Repro is here.](https://github.com/heysailor/now-dev-next.js-routing-error-example)

**Comment by paulogdm** [comment]
Closing in favor of https://github.com/zeit/now-cli/issues/2289
