### ISSUE TITLE
Allow route definitions to be defined in a separate file

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2029]
**Is your feature request related to a problem? Please describe.**
When using multiple config files (--local-config), routes definitions require manual duplication across all config files.

**Describe the solution you'd like**
Centralise the route configs as a separate route file, can make it optional (either inside now.json or as an external).

**Comment by ric2z** [comment]
This is also a problem on our end, and we've had similar problems around secrets. I created an issue about it here: https://github.com/zeit/now-cli/issues/2081

The same solution might apply to both issues.

**Comment by jaydenseric** [comment]
I have 20+ parameterized routes, so to duplicate them across `now.dev.json`, `now.staging.json` and `now.production.json` is ludicrous!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
