### ISSUE TITLE
now dns update / now dns add ... --force

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2033]
Allow dns records to be updated from now-cli.

Right now `now dns add` command will return an error if a DNS record already exists.
The existing record will have to be `now rm` first before they can be added again.

It will be a better UX if at `now dns add`, users are prompted to see if they want to overwrite their existing entry; and allow --force flag to be used with `now dns add` to answer YES to all overwrite. 

A separate `now dns update` can also be added.

**Comment by jeantil** [comment]
I would like to second this request. I know I can "update" a record by doing a remove then adding it back and that dns propagation times and caching rules make it highly improbable that the rule will "temporarily" disappear but having a more atomic operation would _feel_ better for me as a user.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
