### ISSUE TITLE
Better use of meta in now.json

### ISSUE THREAD

**Issue by muuvmuuv** [vercel/vercel#2065]
ATM it is not possible to set meta-tags as objects in `now.json`. `now` results in:

```shell
> Error! An unexpected error occurred in deploy: TypeError: e.forEach is not a function
    at parseMeta (/snapshot/repo/dist/index.js:1:2532430)
    at Module.main (/snapshot/repo/dist/index.js:1:2148102)
    at t.default (/snapshot/repo/dist/index.js:1:774007)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

IMO it would be better to allow meta as this (or allow both):

```json
{
  "meta": {
    "robots": "noindex,nofollow"
  },
}
```

We would need to edit this file: https://github.com/zeit/now-cli/blob/b51ceb26f8039cb59b875db5aea8a25dfd8c6bc5/src/util/parse-meta.js#L10-L17

**Comment by fregante** [comment]
I think you can achieve that specifically with:


```json
{
  "routes": [
    {
      "src": "(.*)",
      "headers": {
        "X-Robots-Tag": "noindex,nofollow"
      }
    }
  ]
}
```

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
