### ISSUE TITLE
Configurable ignore file

### ISSUE THREAD

**Issue by borekb** [vercel/vercel#2079]
Now's ignore file is hardcoded to be `.nowignore`. This has two problems:

- Even if my ignore rules in `.gitignore` are suitable for a Now deployment, I have to duplicate them (and remember to keep them in sync in the future).
- When I have multiple `now.json` files, possibly because I want to deploy to two domains from a single repo, I also likely need to be uploading two different sets of files. But I only have a single `.nowignore` to play with.

This would be resolved by a new `now.json` config value like:

```
"ignorefile": ".gitignore"
```

or:

```
// now.1.json
"ignorefile": ".nowignore-1"

// now.2.json
"ignorefile": ".nowignore-2"
```

This could also be a CLI flag (but not _only_ a CLI flag please!).

Originally discussed [on Spectrum](https://spectrum.chat/zeit/now/use-gitignore-instead-of-nowignore~51233bc3-3c31-429e-9940-50b914f6b1a8). Somewhat related is https://github.com/zeit/now-cli/issues/2074.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
