### ISSUE TITLE
Now-CLI on Termux

### ISSUE THREAD

**Issue by redreceipt** [vercel/vercel#2111]
Installing Now from Termux on Android is broken because `process.platform` is `android`, not `linux`.

![Screenshot_20190406-143331](https://user-images.githubusercontent.com/2659478/55673678-1817a280-5879-11e9-9a68-5c273f18cff9.png)

**Comment by rauchg** [comment]
Thanks @redreceipt – we'll fix ASAP!

**Comment by campbellgoe** [comment]
It is possible to get now working on Termux by cloning it with git, described in the main readme.md

1. clone it to your local device (git clone)
2. Install dependencies with yarn install
3. Link the package to the global module directory: yarn run link (not yarn link)
You can now start using now anywhere inside the command line

**Comment by TooTallNate** [comment]
Closing because as of Now CLI >= v16.0.0, we no longer use `pkg` pre-compiled binaries, which was the root of this issue (we never had ARM binaries compiled for `android` platforms).

Please attempt to install Now CLI again (using the latest version) and it should work as expected, and open a new issue if there are still any problems that you experience.
