### ISSUE TITLE
Feature Request: Link to Assist Buying Unavailable Domain

### ISSUE THREAD

**Issue by redreceipt** [vercel/vercel#2112]
No idea how this would work or if there is even a standard place for it but it would be really helpful to link a service that lets you inquire about unavailable domains.

<img width="640" alt="Screen Shot 2019-04-06 at 2 38 05 PM" src="https://user-images.githubusercontent.com/2659478/55673729-9ffdac80-5879-11e9-9bce-d36f9c8bb020.png">

I know it may be out of scope for Now but it would be a really helpful tool.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
