### ISSUE TITLE
Feature Request: Mail Forwarding

### ISSUE THREAD

**Issue by redreceipt** [vercel/vercel#2113]
Attaching an email to an owned domain in a simple way like Zeit does with everything else would be an amazing addition in my opinion. It's what's keeping me from transferring my domain from Google Domains because they offer free mail forwarding. Zeit could do something similar and not have to mess with mail servers. ex...

`now domain add-email michael michael@gmail.com` would add an MX record pointing to a server at Zeit that would the logic to simply forward michael@[MY_ZEIT_DOMAIN] to michael@gmail.com. Pretty sure that's how Google does it.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.
