### ISSUE TITLE
Ignore .well-known routes definitions

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2126]
Right now it is possible for people to be "too smart" and try to handle Let's Encrypt's well known challenge by attempting to setup routes like the following

```
    {
      "src": "^/(.well-known)$",
      "dest": "/$1"
    }
```

which will confuse the system and start serving well-known routes under HTTPS and breaking the Let's Encrypt certificate integrations.

We should look in to the possibilities of banning / ignoring `now.json` with .well-known defined in routes.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
