### ISSUE TITLE
[now dev] asPath is same as pathname

### ISSUE THREAD

**Issue by Gerrel** [vercel/vercel#2296]
my url in the browser is: http://localhost:3000/team/test-team, but the asPath in the context is /team/view. It is always the file-location on browser refresh.

Navigating to the page with Link button works fine and it also works on production.

**Comment by TooTallNate** [comment]
Hey @Gerrel, sorry for the late reply. Would you be able to create a repository demonstrating the issue that you are experiencing? Thanks in advance!

**Comment by jaydenseric** [comment]
Using `withRouter`:

```js
import { withRouter } from 'next/router'
```

The `router.asPath` in the server environment is incorrect; it shows the regular path. In my case,
it should be `/users/VXNlcjo1YmYzNjcxNGY1N2FlYzA1Y2QzYWMwNzQ` but I'm getting `/user?userId=VXNlcjo1YmYzNjcxNGY1N2FlYzA1Y2QzYWMwNzQ`.

This causes a server/client HTML mismatch error for my nav link active state (based on `href === router.asPath`) like this:

```
Warning: Prop `className` did not match. Server: "jsx-2426518903 " Client: "jsx-2426518903 active"
```

**Comment by jaydenseric** [comment]
I think maybe it's because the router `req.url` is being set to the `newUrl`, instead of the original request URL like in the regular next server:

https://github.com/zeit/now-cli/blob/370961e872a4637888fa0bec6c785bfe176ae751/src/commands/dev/lib/dev-server.ts#L781

vs:

https://github.com/zeit/next.js/blob/577cc7b6afb144c7bfe0755fb78edb9c6ae45e70/packages/next-server/server/render.tsx#L258

**Comment by Gerrel** [comment]
@TooTallNate  [https://github.com/Gerrel/now-dev-aspath-test](https://github.com/Gerrel/now-dev-aspath-test)

**Comment by TooTallNate** [comment]
Thanks for the repro @Gerrel, I am taking a look into this.

**Comment by Gerrel** [comment]
issue is fixed with next 9
