### ISSUE TITLE
`now dev` does not resolve Lambda routes for monorepo of CRA + Lambdas

### ISSUE THREAD

**Issue by ctrlplusb** [vercel/vercel#2336]
I have a monorepo containing a Create React App static build along with Node based lambdas.  Deploying the monorepo to Now works as expected, however, the lambda routes do not get resolved when running via `now dev`. Instead they always resolve the `index.html`.

**Actual**

<img width="984" alt="Screenshot 2019-05-10 14 06 29" src="https://user-images.githubusercontent.com/12164768/57531731-00c54c80-7332-11e9-9e65-68953c8f8571.png">

**Expected**

<img width="994" alt="Screenshot 2019-05-10 14 44 41" src="https://user-images.githubusercontent.com/12164768/57531793-2f432780-7332-11e9-9384-a70ac53bd9ac.png">

---

now: 15.2.0
os: Mac OS 10.14.4

Example repo: https://github.com/ctrlplusb/cra-monorepo

Example deployment: https://cra-monorepo.ctrlplusb.now.sh/ 
(the deployment works as expected, it's `now dev` that doesn't)

**Comment by jb-san** [comment]
could be the related to https://github.com/zeit/now-cli/issues/2323 ?

**Comment by ctrlplusb** [comment]
Interesting. My lambdas are first in the build array, but I will play with order. I would expect the route order would be more important though. 😀

**Comment by callain** [comment]
Hi @ctrlplusb, did you manage to make it work by playing with order ?

**Comment by ctrlplusb** [comment]
Hey @callain - yep, didn't have any effect. Same issue is experienced.

**Comment by callain** [comment]
Figure out the same thing. I can't develop in local because I absolutely need the lambdas to be working :/

**Comment by TooTallNate** [comment]
Ok so two things are going on here:

1. `react-scripts start` opens a browser window by default pointing to its own dev server port (which I think is the one from your screenshot). This is problematic because the CRA dev server doesn't know about the Now routes and thus serves your index page for the lambda URL.
1. Your example uncovered a bug in the `@now/static-build` dev server logic (thank you!), which I have fixed in https://github.com/zeit/now-builders/pull/499. Currently this change is on the `canary` tag of that builder.

I've submitted a PR to your example repo that includes changes that make `now dev` work as expected: https://github.com/ctrlplusb/cra-monorepo/pull/1

**Comment by TooTallNate** [comment]
Ok I published `@now/static-build@0.5.6` which includes the fix in https://github.com/zeit/now-builders/pull/499, so using `canary` is no longer necessary.

**Comment by ctrlplusb** [comment]
Hey @TooTallNate!

Awesome! That works 🎉

Thanks for looking into this so fast. Really appreciate it. 👍

One question on the side if you don't mind...

I got quite confused setting up the routes for the static build.

The file structure is:

```
|-www
| |- build
| |- package.json
|- now.json
```

In the `now.json` the builder is configured with the `distDir` set to `build`:

```json
{
  "src": "www/package.json",
  "use": "@now/static-build",
  "config": { "distDir": "build" }
}
```

I would have expected my routes to be defined as such:

```json
{
  "src": "/(.*)",
  "headers": { "cache-control": "s-maxage=0" },
  "dest": "/www/build/index.html"
}
```

However, instead of the dest being rooted at `/www/build`, it needs to be rooted at `/www`, like so:

```json
{
  "src": "/(.*)",
  "headers": { "cache-control": "s-maxage=0" },
  "dest": "/www/index.html"
}
```

This doesn't feel intuitive to me. I was wondering if you could provide me with some enlightenment why this is the case?

Thanks 🙏

**Comment by TooTallNate** [comment]
So the static builder expects the output files to be created in a directory separate than the entrypoint file, however the builder exports those files relative to the entrypoint file.

Consider if you didn't place them in the `www` dir and instead in the root of your project. You would want that generated `index.html` file to be exported at the root of your deployment so that it is served when you visit your deployment URL (rather than `${deploymentUrl}/build`).

Hope that makes sense. Let me know if you want additional clarification.
