### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by fibo** [vercel/vercel#235]
I tryed *now* with this package https://github.com/fibo/tris3d-server/tree/v0.6.0
which contains a *build* script, and a *postbuild* like

    "build": "npm run lint && npm run test && npm run webpack",
    "postbuild": "npm run git_add-f; git commit -m 'build'; git push origin master",

on deploy, I got an error like "git not found". I did not expect *now* would run the *npm run build* script, maybe it is documented, but I did not find it.

**Comment by jamo** [comment]
I wonder would the `git push` even work; are the git credentials included to the deployment?

**Comment by TooTallNate** [comment]
> I did not expect now would run the npm run build script, maybe it is documented, but I did not find it.

Right, you can specify `build` or `now-build` (later takes precedence over former) for your now deployment's build process. See: https://zeit.co/now/#how-do-i-run-my-build-process

As @jamo mentioned though, attempting to push a git commit from inside the deployment will not work since the `$HOME/.git` credentials would not be correctly set up. Aside from that, it's kind of bad practice to commit build files to a git repository like that (or at least, should be unnecessary in the case of deployments to Now).

I'd recommend dropping the `postbuild` step entirely and trying the Now deployment again.

**Comment by fibo** [comment]
Thanks for the answer, the build script was already there in the project, used by the developer do the git push works cause It runs on my laptop.

I tryed now, and the I discovered It runs the build script, so I remove d It.

Mea culpa, I missed reading the docs.

**Comment by fibo** [comment]
Sorry for typos I am on mobile, underground with anche italiano layout :P
