### ISSUE TITLE
Now (v2) Gatsby + lambdas, now-build always triggered / crashing with canary

### ISSUE THREAD

**Issue by mtt87** [vercel/vercel#2363]
Running `now dev` works fine for the Gatsby website and I can see it correctly at `http://localhost:3000`. But as soon as I browse to `/api/locations` it doesn't work anymore:
```
> GET /api/locations
> Building @now/node:api/locations/index.js
downloading user files...
installing dependencies for user's code...
installing to /var/folders/4y/mlqsnhbx4yx7kwfcg8s3b9880000gn/T/co.zeit.now/dev/workPaths/7fvnfnob/api/locations
running user script...
running "npm run now-build"
```
What is happening here is that the `now-build` step is being triggered again. The result is that the process is not working correctly and tries to rebuild again the "gatsby" part then eventually it crashes.

To see my `package.json` and `now.json` https://gist.github.com/mtt87/d4348511e3b2a32f051aee061fc6410b

## Issue with now@canary
I was suggested to try with `now@canary` but that doesn't work at all, the process is crashing with 2 scenario
### Project installed with NPM
It's weird that is trying to use yarn even if I'm not using it in my project.
```
$ now dev
> Now CLI 15.2.1-canary.2 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
⠏ Setting up Builder for package.json: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Project installed with Yarn
I tried `rm -rf node_modules package-lock.json && yarn` and the builder got further but eventually crashed (I cut some of the log)
```
$ now dev
> Now CLI 15.2.1-canary.2 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
downloading user files...
installing to /Users/mattia/Dev/adrenaline/now
yarn run v1.15.2
$ gatsby develop -p $PORT
success open and validate gatsby-configs — 0.004 s
success load plugins — 0.454 s
success onPreInit — 0.003 s
success initialize cache — 0.005 s
success copy gatsby files — 0.051 s
success onPreBootstrap — 0.009 s
success source and transform nodes — 0.044 s
success building schema — 0.176 s
success createPages — 0.000 s
success createPagesStatefully — 0.046 s
success onPreExtractQueries — 0.002 s
success update schema — 0.018 s
success extract queries from components — 0.097 s
success run static queries — 0.054 s — 3/3 57.05 queries/second
success run page queries — 0.011 s — 8/8 755.18 queries/second
success write out page data — 0.002 s
success write out redirect data — 0.000 s
success Build manifest and related icons — 0.116 s
success onPostBootstrap — 0.117 s

info bootstrap finished - 3.882 s

 ERROR  Failed to compile with 2 errors13:10:01
...
error ✖ ｢wdm｣: 
ERROR in ./.cache/app.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'eslint-config-react-app'
...
> Error! Failed to detect a server running on port 52052.
Details: https://err.sh/zeit/now-builders/now-static-build-failed-to-detect-a-server
```

**Comment by mtt87** [comment]
I've created a repo to reproduce
https://github.com/mtt87/bug-now-gatsby-lambda

Note that with this repo (gatsby starter kit + one lambda function) it does still trigger `now-build` again when calling the lambda url but it doesn't crash.
Tested with the stable version of `now@15.2.0`

**Comment by paulogdm** [comment]
Can you try the latest release (https://github.com/zeit/now-cli/releases) and let me know?

**Comment by mtt87** [comment]
Interesting...

If I decide to use `npm` with the latest version I can't even run the project as it gets stuck here:
```
$ now dev
> Now CLI 15.3.0 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
⠹ Setting up Builder for package.json: info Visit https://yarnpkg.com/en/docs/cli...
```
If I decide to use `yarn` instead (`rm -rf node_modules package-lock.json` and `yarn`) it runs BUT it's still re-building gatsby as `now-dev` is triggered also for `/api/` endpoints.
```
$ now dev
> Now CLI 15.3.0 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:52414/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use npm run build
⠀

info ℹ ｢wdm｣:
info ℹ ｢wdm｣: Compiled successfully.
```
Then I browse to `http://localhost:3000/api/locations` and I see again
```
> GET /api/locations
> Building @now/node:api/locations/index.js
downloading user files...
installing dependencies for user's code...
installing to /Users/mattia/Dev/bug_now/api/locations
running user script...
running "yarn run now-build"
yarn run v1.15.2
$ gatsby build
success open and validate gatsby-configs - 0.005 s
success load plugins - 0.303 s
success onPreInit - 0.066 s
success delete html and css files from previous builds - 0.012 s
success initialize cache - 0.006 s
success copy gatsby files - 0.059 s
success onPreBootstrap - 0.008 s
success source and transform nodes - 0.040 s

 WAIT  Compiling...14:41:27
⠀
info ℹ ｢wdm｣: Compiling...
success building schema - 0.169 s
...
```

**Comment by mtt87** [comment]
I have a feeling that using workspaces/lerna to manage the monorepo could help, I'll do some tests

**Comment by vuau** [comment]
I tried with the latest release 15.3.0. Same issue with now-build is triggered everytime lambda function is accessed

**Comment by michaellopez** [comment]
@mtt87 @phamvuau @paulogdm 
We got hit by this one too. It works as designed because `@now/node` executes/runs the `now-build` of the same `package.json` that runs for `@now/static-build` on changes. Meaning that the semantics for `@now/node` and `@now/static-build` are overlapping/clashing. You want the lambda to be rebuilt (like if you are processing them or whatever), but not Gatsby. Since both builders use the same script target to accomplish their job there is a conflict. To fix this the builders would need to introduce their own specific targets like `now-build-<BUILDER-NAME>` and use that over the generic `now-build` whenever it is specific. That would give:
```
"scripts": {
...
"now-build-node": ...,
"now-build-static-build": ...
...
}
```
Which would trigger `now-build-node` for changes to `@now/node` build targets and `now-build-static-build` for `@now/static-build` build targets **for the same `package.json`**

Our workaround for now is to have a sub package in `api` folder, basically its own `package.json` to define its own scripts. In the root `package.json` we are experimenting with:
```
"scripts": {
...
"postinstall": "cd api && npm i"
...
}
```
to make it more seamless for our developers.

We're still trying to figure this stuff out too 😅

**Comment by mtt87** [comment]
In the end I moved away from Gatsby and used next.js with the serverless target.
I had to setup a monorepo in order to make this work and I'm using yarn workspaces.
Add to the root `package.json`
```json
  "private": true,
  "workspaces": ["server", "www"],
```
Then you can create 2 directories `server` and `www` where you put your API server side code and your frontend.

You can see it here
https://github.com/mtt87/adrenaline-box-monorepo

I'm planning to try again this approach with Gatsby as well but don't have much time atm.

**Comment by sergeyfilimonov** [comment]
@michaellopez @TooTallNate @mtt87

I'm experiencing the same but with Gridsome.

I've tried the solution "To fix this the builders would need to introduce their own specific targets like now-build-<BUILDER-NAME> and use that over the generic now-build whenever it is specific. That would give:"

Now all API calls work independently and don't trigger the build script. But once I update any file in /api or the root (Gridsome project) the build script is triggered though it should be served in `gridsome develop` mode and update instantly instead of waiting for 30 seconds for the update. Let alone that updating /api files should never trigger any updates to the Gridsome project...

I believe this is something to be improved and should not be left "as designed". This just doesn't make sense — if I don't set a `package.json` in `src` I don't expect `project.json` to be involved at all.

My solution for now is to create separate `package.json` and `now.json` files in `/api`:

```json
{
  "name": "api",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "now dev --listen 3003",
    "stage": "now",
    "prod": "now --prod"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "moment": "^2.24.0"
  },
  "license": "UNLICENSED"
}
```

```json
{
  "name": "api",
  "github": { "enabled": false },
  "builds": [
    {
      "src": "index.js",
      "use": "@now/node"
    },
    {
      "src": "actions/**/*.js",
      "use": "@now/node"
    }
  ]
}
```

To create an experience close to what I expect from `now dev` I'm using `concurrently` package:
```json
"scripts": {
    "dev": "concurrently \"gridsome develop --port 5005\" \"cd api && now dev --listen 3004\"",
    "prod": "concurrently \"now --prod\" \"cd api && now --prod\"",
    "build": "gridsome build",
    "explore": "gridsome explore",
    "now-build-build": "npm run build"
  }
```

**Comment by rmariuzzo** [comment]
I'm in the same situation, I would like to be able to run `now dev` without automagically run my CRA.
