### ISSUE TITLE
[now dev] with https

### ISSUE THREAD

**Issue by alexluong** [vercel/vercel#2380]
Hi,

I wonder if we can do something to set up https server with command `now dev`. I'm building a Slack app, and it only works through https.

My workflow right now is to `ngrok` the local server and change the url from Slack every time I work. It would be great if we can implement this feature.

Just a suggestion, maybe we can take some inspiration from the way Gatsby CLI works to implement this. Thank you!

**Comment by krasimir** [comment]
~A PR for addressing this https://github.com/zeit/now-cli/pull/2382~ (I misunderstood the issue)

**Comment by styfle** [comment]
Hi @alexluong 

Currently, `now dev` mimics the cloud deployment locally and exposes a server on localhost.

We understand this use case, a publicly exposed development environment, is valuable for working with hooks like you described.

I think we need a flag that provides a similar experience to [ngrok](https://ngrok.com) with the same features you expect from Now such as [aliases](https://zeit.co/blog/automatic-aliasing), HTTPS, etc.

Then we could use `now dev --cloud` to create a demo URL like with `now` but it would rebuild on save. For developing web hooks that need a permanent URL, we could utilize `now dev --cloud --target staging`.

This would require changes to the CLI to talk directly to our Routing/Proxy layer since this is very different behavior than our current cloud deployments.

cc @leo @TooTallNate

**Comment by alexluong** [comment]
Thanks @krasimir for working on the issue. I apologized for the confusion. I'm new to Slack apps and thought that they only need an SSL cert. Regardless, that's an awesome PR in such a short amount of time!

@styfle, thanks for addressing the issue. Just wondering if the process you described would make it on the roadmap any time soon. That would definitely help the development workflow for Slack app and potentially other platforms too. In the mean time, I guess `ngrok` is the simplest solution.

**Comment by fabien-h** [comment]
There are other use cases for https.

For example, if you set a cookie with the `Secure` flag on, it won't be send over http. Which is a VERY good idea.

Not a big deal, you just check your environment and enable / disable the flag on demand. But that would be nice to have exactly the same env dev / prod (and https is a big deal in prod)

**Comment by darknoon** [comment]
Another use case for exposing localhost w/ `https://` is for testing APIs with iOS apps, where outbound non-TLS connections are prohibited by default.

**Comment by ibraelillo** [comment]
Hey, I'm also facing this issue trying to integrate a payment provider which by default only works on https connections.... I think this is more than justified to be included as a feature on the cli interface. 

Another solution is to integrate with some local nginx or something serving as upstream for now cli with ssl configuration.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by softmarshmallow** [comment]
I'm still having this issue. can someone from vercel help me?

**Comment by matepaiva** [comment]
Here I am... having this issue in 2021.

**Comment by gempir** [comment]
The best solution for this right now is to run ngrok

`ngrok http 3000` 

And use the https url from ngrok

I wrote a feature request to support@zeit.co incase nobody hadn't yet.

**Comment by TheJizel** [comment]
> The best solution for this right now is to run ngrok
> 
> `ngrok http 3000`
> 
> And use the https url from ngrok
> 
> I wrote a feature request to [support@zeit.co](mailto:support@zeit.co) incase nobody hadn't yet.

@gempir Awesome utility. Thanks for the info.
