### ISSUE TITLE
Allow GitHub merges to trigger new builds even when no changes in code

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2407]
Ref: https://spectrum.chat/zeit/now/now-for-github-can-we-force-deployment-building-upon-merges-to-master~71a27bb7-1b6a-4fdd-bcc6-8d9f1c39f0c0

Currently when branches are merged, an alias is added to existing deployments instead of rebuilding a new one. This does not work for some customers as they use branches to control build envs.

```
"now:env": "echo export STAGE=$([ \"$NOW_GITHUB_COMMIT_REF\" == master ] && echo prod || echo staging)",
``` 

Proposal: Add an extra configuration https://zeit.co/docs/v2/integrations/now-for-github/#configuration

`"mergeTriggerRebuild": true`

**Comment by wiiiimm** [comment]
Original internal discussion: https://zeit.slack.com/archives/C65QW9PN1/p1559812482165100

**Comment by inlife** [comment]
That feature would be super helpful +1

**Comment by liamdanielduffy** [comment]
@williamli 

Is there any ETA on this fix? 

The current workaround for our team involves either:
1) pushing a commit immediately after merging a PR from GitHub (so that Zeit will rebuild our site with `NOW_GITHUB_COMMIT_REF ` set to `master` for the latest commit)
2) completing all merges from the command line to ensure they are pushed to master as a new commit, meaning we can't use GitHub for merging PRs 😕

Is there any other workaround we can use in the meantime?

**Comment by inlife** [comment]
hey @liamdanielduffy 

Does manual local CLI `git merge` actually do it for you?

It seemed to me after all my attempts that even a merge with commit won't do it for me, and I would need to actually modify some part of the code itself to force `now` think that new deploy does indeed have a change.

**Comment by liamdanielduffy** [comment]
@inlife 

I should have clarified. For option 2, we complete the merge from the CLI, then introduce some meaningless diff so that the merge commit is treated by Now as a change in the codebase, allowing it to be rebuilt on `master`, with `NOW_GITHUB_COMMIT_REF ` set to `master`

Overall, this is a small but significant annoyance in an otherwise amazing product 🙂I hope that the Zeit team is able to improve the experience on this soon!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.

**Comment by developius** [comment]
Not sure if this is the place to comment, but could we expand this to cover GitLab too? I have exactly the same issue 😄

**Comment by jamesbvaughan** [comment]
Apologies for reviving an old closed issue, but was this feature ever developed after this issue was closed?

I'm asking here rather than contacting support like an earlier comment requested so that others in my situation who come across this issue will have an easier time.

_edit: After digging deeper into the issue I was facing, I discovered that it was actually caused by my Turborepo build caching, not Vercel. In case anyone else comes across this with the same problem I had, this is the issue that led me to a solution: https://github.com/vercel/turborepo/issues/401_
