### ISSUE TITLE
Feature Request: flags for lambda life-cycle stages

### ISSUE THREAD

**Issue by YuriGor** [vercel/vercel#2433]
I am not sure this is the correct place for such request:
It would be great to have some process.env flags to check if the current invocation is
- the first one after deployment
- the first one after waking up
- the last one before freezing
- the last one before deployment will be deleted.
last two cases now do not exist, but I hope it's not so difficult to make a dry shot with empty `req` argument right before lambda get frozen/deleted.

People [wait](https://spectrum.chat/zeit/now/now-2-0-connect-to-database-on-every-function-invocation~e25b9e64-6271-4e15-822a-ddde047fa43d) for this feature to be able to manage shared reusable resources, for example, to dispose of a database connection.

**Comment by varna** [comment]
In other words "Lambda Hooks"?

**Comment by samuelkarani** [comment]
I support, for the sake of mongoose and dreaded "Selection timeout error"

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
