### ISSUE TITLE
[now dev] Doesn't serve files in next.js `public` folder

### ISSUE THREAD

**Issue by carlesandres** [vercel/vercel#2434]
Serving a robots.txt file with `next.js` from the `public` folder works as expected when deploying with 'now' but errors (404) when serving locally with `now dev`. 

I'm not 100% sure it's not a problem in `next.js`. 

I've created an example here: https://github.com/carlesandres/now-monorepo-nextjs-public

**Comment by tannerlinsley** [comment]
Confirmed. `public` is served in production, but not in development. :(

**Comment by TooTallNate** [comment]
Closing because the static files directory is called `static`, not `public`, so the 404 is expected. After renaming the `www/public` directory to `www/static` in your example repo, I get the expected results with `now dev`:

<img width="853" alt="Screen Shot 2019-08-13 at 9 38 47 PM" src="https://user-images.githubusercontent.com/71256/62994868-ec9e5900-be12-11e9-953d-00931541a29b.png">

Please consult the [Next.js docs](https://nextjs.org/docs) for further details.

**Comment by khatkarr** [comment]
**Reason**: The files that get served from `static` folder has `static` in path.

**Expected Behaviour**: The URL should not have `static` in URL path. If files are put in public folder they should be served directly with URL path being decided by folder structure.
```
public:
   robots.txt
   .well-known
        achme-challange
            jdfhsdjkfhw34897dfjkdh87channlange-file
```
Urls generated should looks like this:
```
https://www.example.com/robots.txt
https://www.example.com/.well-known/achme-challange/jdfhsdjkfhw34897dfjkdh87channlange-file
```
**Benefit**: This way we can avoid having route setup in config file or using custom server.

Found some more info on `public` folder:
https://github.com/zeit/next.js/issues/751#issuecomment-511166039

**Comment by Abjuk** [comment]
For verify ssl certificate I should use this path: /.well-known/pki-validation/6377BE897262BF21456459DF909610333642.txt

If I put this file to /public/6377BE897262BF21456459DF909610333642.txt -> all ok
If I use /public/.well-known/pki-validation/6377BE89726456456F21C9DF909610333642.txt - I got 404 error.

I can't change this patch because it rule from SSL Certificate Center
Could you please help me.

**Comment by dr5hn** [comment]
Yeah nested public folder's route says 404.

For eg:
public/downloads/xyz.csv 
Accessing it like `https://xyz.com/downloads/xyz.csv` - Turns out 404 page not found.

**Comment by rajorpratyush** [comment]
is this problem still present in next.js or do i need to look into some other ssr libraries ?

**Comment by soumyadeeproyint** [comment]
I am unable to access a .txt file through a public folder. it is showing a 503 error. I am using Next.js 9.5.

**Comment by hendriku** [comment]
Problem still present! Any help??

**Comment by hendriku** [comment]
Upgrading from next 9.5.5 to 10.1.3 solved it for me. This indeed is a bug which is really weird and difficult to find!

**Comment by RemyMachado** [comment]
The problem's still there. I would suggest to reopen this issue.
Currently there's no way to access `/public/any/file.png` directly from the browser. You need to put it inside `/public/static/any/file.png` and the documentation isn't clear at all on this subject.
