### ISSUE TITLE
Different env configuration for multiple environments

### ISSUE THREAD

**Issue by flearsnetwork** [vercel/vercel#2452]
Hi there,

I have gone through a lot of documentation and forum discussions these days and could not find a proper solution for a seemingly widely used workflow.

The goal is to set up 3 stages that have automated CI/CD (also using ZEIT Github integration):
Development environment: localhost:3000
Staging: staging.project.com (deployed from the "staging" branch of our Github repo)
Production: project.com (continuously deployed from master branch)

Currently, there are a lot of variations out there on how to use environment variables (.env, now.json, next.config.json, ...) which we find somehow confusing.

Could someone be so kind and elaborate on a practical way to set up env variables that fits the infrastructure mentioned above? Which kind of env file do we have to set the values in for each stage?

Many thanks!

**Comment by callain** [comment]
Hello,

Here is how I do it:

**Development environment**: 
- Use your `now.json`file
- Start with `now dev`
- Environment variable in `.env` file
- Build environment variable in `.env.build`
- Now secrets does not work with `now dev` at the moment

**Staging environment**: 
- Create a `now.staging.json` file which is a copy of `now.json`
- Change the alias to `staging.project.com`
- Modify your `env` and `build env` variables if needed (you can create secrets prefixed by `staging`
 for example
- Deployment `now --target production --local-config now.staging.json`

(This is where it can be confusing because you target production but your production alias is actually your staging environment)

**Production environment**: 
- now.json with alias `project.com`
- Deployment `now --token $NOW_TOKEN --target production`

In this configuration your are using the same now.json for both dev and production environment.
But you could create a `now.production.json` if you need one, just add the parameter `--local-config now.production.json` when you deploy

Secrets are not per environment(yet ?), that's why prefixing them is useful.

I don't think you can do this with the Github integration... I personnally use an external CI.

Hope it would be useful to you :)

**Comment by flearsnetwork** [comment]
@callain thank you for the detailed description. This is definitely a viable - although not preferred - alternative until ZEIT will support multiple environments for their Github integration.

**Comment by flearsnetwork** [comment]
Update: ZEIT support provided an answer to this issue that they have a new format in the works called "now.js" that makes what is described in here possible.

**Comment by leo** [comment]
Thank you for your suggestions. We'll consider this as part of https://github.com/zeit/now-cli/issues/2613.

**Comment by alext234** [comment]
Happen to see this page when checking out how to have different environments.
Is @callain's approach (using different `now.json` files) the only approach as of now or are you guys working on a standardised way?

**Comment by ivan-kleshnin** [comment]
@alext234

Basically this is an unresolved issue and everyone does their own hacks to make it work :(
You can create multiple `now.json`s but nobody has the same idea of what to do with multiple `.env` files (if you want say to connect to the prod. database from a local machine).

**Comment by alext234** [comment]
I am curious about what tools Zeit team uses internally :)) are they also dogfooding now ?

**Comment by lirbank** [comment]
For anyone googling on this topic, @rauchg just made a statement https://github.com/zeit/now/issues/2613#issuecomment-594036619 a few days ago.

**Comment by L-u-k-e** [comment]
I tried using the method suggested by @callain above, adjusted for Zeit 2 and Now CLI v17 but when I run:

``` 
now --prod --local-config now.staging.json
```


I get a warning saying: 

>  Your project already has domains configured at https://zeit.co/lucasp/money-matters/domains, please remove `alias` from your now.json file.

and the build is deployed to my production (master) domain. I tried removing all domains from the project settings, but the Zeit Now web app stops me from removing them all. Apparently you have to have at least one domain configured. 

Is this possible to do today in Zeit?

**Comment by callain** [comment]
A log of things has changed since, I think this configuration was related to Now Cli V16.

Now v17 introduced projects and domains (on zeit.co), but was lacking configuration for environment variables.

With Now v18 (actual version), it seems you can configure them and link them to your project's domains (look in the settings of your project).

Meaning, you don't need a different now.json anymore, hopefully :) I did not test v18 yet but I am looking forward to upgrade.

The documentation is here: https://zeit.co/docs/v2/build-step#environment-variables

**Comment by L-u-k-e** [comment]
Well, I'm super happy that there's development on this front, but I do have some gripes and further questions...

First off, I dislike the fact that I have to use the zeit web app to configure the env variables and I cant just configure them at build/deploy time using a file (on my CI Server)... but furthermore, it seems we've lost some functionality here. Is there any way for me to do a production deploy to a non-production url. E.G. the Preview URL's or a persistent "staging" URL? 

What's the difference exactly between a production deploy and a non-production deploy? Does Zeit use different parameters when running build or does it only change the environment variables that are used?

**Comment by lucleray** [comment]
@L-u-k-e 

> I have to use the zeit web app to configure the env variables and I cant just configure them at build/deploy time using a file (on my CI Server)

You can still use the [`env`](https://zeit.co/docs/configuration#project/env) and [`build.env`](https://zeit.co/docs/configuration#project/build-env) attributes in now.json to configure environment variables for your deployment. You can also use [`--env`](https://zeit.co/docs/now-cli#commands/Now/unique-options/env) and [`--build-env`](https://zeit.co/docs/now-cli#commands/Now/unique-options/build-env) if you want to pass environment variables directly to the `now` command.

If you opt-in for one of these 2 options:
- the environment variables will not be set in your project, but only on the deployment
- the environment variables take precedence over the project's environment variables

> Is there any way for me to do a production deploy to a non-production url. E.G. the Preview URL's or a persistent "staging" URL?

If by production deploy you mean a deployment with production environment variables, you're right that we don't support that currently. Currently, you can manually supply environment variables to a deployment with the configuration and cli flags I shared above to achieve it.

> What's the difference exactly between a production deploy and a non-production deploy? Does Zeit use different parameters when running build or does it only change the environment variables that are used?

There's only two differences between Production and Preview deployments:
- the Environment Variables applied to the deployment
- the Domain that is applied to the deployment

We're looking at adding a new "Staging" environment, with custom environment variables, to solve some use cases that are not currently covered with Production and Preview. Would that help solve your use case?

**Comment by L-u-k-e** [comment]
@lucleray Thank you for the clarification. So basically if I run `now --local-config staging.now.json` I can put all of my staging environment variables in the `staging.now.json` file's `env` property. The deployment will be assigned a preview URL but the project will be built using production webpack settings. If that's correct than this works fine for my use case :)  

Only thing I'd add is ideally there would be a way for me configure another domain like: `my-project-staging.now.sh` and explicitly configure the domain during deployment either via the `now.json` file or via a command line flag.

**Comment by njbarrett** [comment]
> We're looking at adding a new "Staging" environment, with custom environment variables, to solve some use cases that are not currently covered with Production and Preview. Would that help solve your use case?

A staging environment would be super useful for us. Currently I am using a `now.staging.json` as advised above to get around this.

**Comment by tibotiber** [comment]
@lucleray, just want to clarify one thing:
> There's only two differences between Production and Preview deployments:
    - the Environment Variables applied to the deployment
    - the Domain that is applied to the deployment

I am reading [in the docs](https://vercel.com/docs/v2/platform/deployments#preview), that preview deployments also have `X-Robots-Tag = noindex` to avoid listing by search engines. Is that right? Is there a way to opt out of it?

**Comment by ivan-kleshnin** [comment]
@njbarrett how'd you describe a difference between Preview and Staging envs? 
As a customer of the platform, I'm personally against extra complexity and subtle nuances.

**Comment by njbarrett** [comment]
@ivan-kleshnin not really a subtle nuance - we use preview environments against a development database that gets cleared regularly, and a staging environment that uses the production data which we use to test right before a release.
That's why we need seperate sets of environment variables for both.
preview = dev database credentials
staging = prod database credentials
production = prod database credentials

**Comment by ivan-kleshnin** [comment]
Ok, makes sense, thank you for the clarification.

**Comment by lucleray** [comment]
@tibotiber You can overwrite the `X-Robots-Tag` header by using the [`routes`](https://vercel.com/docs/configuration#routes/headers) property in your now.json file:

```
{
  "routes": [
    {
      "src": ".*",
      "headers": { "x-robots-tag": "my custom value" },
      "continue": true
    },
    // your other routes
  ]
}
```

**Comment by tibotiber** [comment]
Thanks @lucleray.

**Comment by yannicktian** [comment]
> We're looking at adding a new "Staging" environment, with custom environment variables, to solve some use cases that are not currently covered with Production and Preview. Would that help solve your use case?

Hello @lucleray, is there somewhere where I can track this "Staging" environment progress? thanks 🙏

**Comment by styfle** [comment]
Hi @yannicktian 

This feature is available today: https://vercel.com/changelog/environments-variables-per-git-branch

Also checkout this guide: https://vercel.com/support/articles/set-up-a-staging-environment-on-vercel
