### ISSUE TITLE
now-alias should notify user of domain creation

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#248]
`now alias` performs (the equivalent of) a `now domain add` under the hood when the domain hasn't been added before.

To make this clear, we should add to the output:

```
> Domain zeithq.com created ($id)
```

Similarly, when the certificate is provisioned 

```
> Certificate for zeithq.com created ($id)
```

**Comment by OlliV** [comment]
Currently we only show
```
> mynowdomain.xyz is a custom domain.
> Verifying the DNS settings for mynowdomain.xyz (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for mynowdomain.xyz
> Success! mynowdomain.xyz now points to sse-test-eaxbahyvso.now.sh! [5s]
```

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
