### ISSUE TITLE
Windows x32

### ISSUE THREAD

**Issue by diegofazio** [vercel/vercel#2485]
Hi, Is there a version for Windows x32?

Thanks

**Comment by MAPESO** [comment]
Hi 👋!  unfortunately we do not have an **x32** version :/

**Comment by TooTallNate** [comment]
We only offer pre-compiled binaries for x64 operating systems, because the compilation tool [`pkg`](https://github.com/zeit/pkg) only supports 64-bit CPUs.

_However_, you could clone this repo, run `npm install` and `npm run build` to build the project and then `node dist` should run the CLI from the built output code. Hope that helps!
