### ISSUE TITLE
[now dev] Bug in variable 'process.title' on server

### ISSUE THREAD

**Issue by menberg** [vercel/vercel#2503]
When accessing the variable _process.title_ under **now dev**, the expected output should contain _"node"_, but I get strange results like _"�=���"_ (vscode terminal) or _";\u0002"_ (iTerm).

**console.log(process)** outputs `
process {
  title: ';\u0002',
  version: 'v10.15.3',
  ...
}
`

I'm using [Overmind](https://overmindjs.org/) as state management library with nextjs. Overmind detects server side rendering with `const isNode =
  process && process.title && process.title.includes('node')`, so having a correct _process.title_ under **now dev** would help.

Any hints on how to fix this? Thanks!

**Comment by TooTallNate** [comment]
This was likely due to `pkg`. Try using Now CLI >= 16.0.0 which no longer uses `pkg` pre-compiled binaries.

It works as expected for me. For example:

```js
module.exports = (req, res) => {
  res.setHeader('Content-Type', 'text/plain');
  res.end(`process.title = ${JSON.stringify(process.title)}`);
};
```

<img width="194" alt="Screen Shot 2019-08-15 at 9 14 24 PM" src="https://user-images.githubusercontent.com/71256/63143134-c22ed600-bfa1-11e9-919d-d5a9eb1145dd.png">
