### ISSUE TITLE
[now dev] Won't run from `npm start`

### ISSUE THREAD

**Issue by jessehattabaugh** [vercel/vercel#2511]
My package.json contains:
```json
{
    "scripts": {
        "start": "now dev"
    }
}
```
When I run it like so:
```sh
$ npm start
> now dev
```
Nothing happens. 

I'm using Bash on Windows

**Comment by TooTallNate** [comment]
Hey @jessehattabaugh, thanks for the report. Unfortunately, I think this is a peculiarity of Bash on Windows and/or npm (possibly due to how npm launches the child process), and not something that we can address in the now-cli codebase.

**Comment by jessehattabaugh** [comment]
Same problem with Yarn
![image](https://user-images.githubusercontent.com/17991/60920160-665b8980-a24c-11e9-8904-fa28714487ec.png)

**Comment by jessehattabaugh** [comment]
Also PowerShell
![image](https://user-images.githubusercontent.com/17991/60920274-a6227100-a24c-11e9-8308-5e4ca8c9db26.png)

**Comment by jessehattabaugh** [comment]
It does work on my Mac though, so it does seem to be related to Windows.

**Comment by jessehattabaugh** [comment]
Is this file supposed to be blank? This is from my `node_modules` on Windows
![image](https://user-images.githubusercontent.com/17991/60922673-1d0e3880-a252-11e9-9739-3f2cf540d15f.png)

**Comment by TooTallNate** [comment]
Closing because this was a bug related to the previous `postinstall` script that Now CLI used to download the pkg pre-compiled binary for your platform. As of Now CLI v16.0.0, we are no longer using `pkg` and relying on npm/yarn to set up the globally available binary.

Please try to re-install Now CLI latest verison, and if you are stil experiencing troubles then open up a new issue.
