### ISSUE TITLE
Release version numbers

### ISSUE THREAD

**Issue by ctrlplusb** [vercel/vercel#2586]
Hey team zeit;

Would you mind providing a brief description of the version number strategy you are employing. I seem to have confused myself a few times where you look to be releasing a new minor with some canaries, and then all of a sudden a patch release comes out of the work.

**Comment by leo** [comment]
Thanks for the question, @ctrlplusb!

We're already working on making the release process more transparent, but here's the TLDR:

In some scenarios, we've been releasing canaries that did not directly match the stable version that occured after them (e.g. `15.6.0-canary.1` and then `15.6.1` instead of `15.6.9` as stable). This occurs when we are the decision to make a commit a major/minor/patch change has changed. We're working on making this process more predictable in the future.
