### ISSUE TITLE
Functions in `now dev` waste 3 seconds on re-installing

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2605]
As you can see in the video below, we are spending about 3 seconds on installing dependencies every time you edit a function - we need to resolve this differently:

[slow_function_rebuilds_-_Screen_Capture_7-22-19_4.15.02_PM.mp4.zip](https://github.com/zeit/now-cli/files/3426531/slow_function_rebuilds_-_Screen_Capture_7-22-19_4.15.02_PM.mp4.zip)

**Comment by leo** [comment]
More details: https://github.com/zeit/now-cli/issues/2574

**Comment by styfle** [comment]
I started this in https://github.com/zeit/now-builders/pull/812

**Comment by michaellopez** [comment]
@leo Just wanted to leave a note here that `now-static-build` (e.g. Gatsby) also suffers from this in `now dev`, not only functions. As I mentioned in https://github.com/zeit/now-builders/pull/812#issuecomment-518584391

**Comment by donmccurdy** [comment]
I'm still seeing this issue with @now/node, using now v16.7.3 (latest).

Making two requests to my function:
![Screen Shot 2020-02-04 at 9 41 41 PM](https://user-images.githubusercontent.com/1848368/73814183-24b99f80-4797-11ea-98e7-4f501e2a6fc4.png)

Causes dependencies to reinstall twice:
![Screen Shot 2020-02-04 at 9 42 05 PM](https://user-images.githubusercontent.com/1848368/73814194-31d68e80-4797-11ea-84dd-6a2c5d976dc4.png)

Code: https://github.com/donmccurdy/msdf-bmfont-web

Should I file a new issue? Or has this fix not rolled out to the latest stable versions yet?

**Comment by styfle** [comment]
Its not installing, it just says its installing to match the production output.

You'll see additional logging if you add `now.json` with the following:

```json
{
  "build": {
    "env": {
      "NOW_BUILDER_DEBUG": "1"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/229881/73854596-c88b6580-4800-11ea-9b5f-acba1af8cf3a.png)

**Comment by donmccurdy** [comment]
I see, thanks. Full output from my app:

```
> Building @now/node@latest:api/create.js
Installing dependencies...
Skipping dependency installation because dev mode is enabled
Install complete [2ms]
Running user script...
Script complete [6ms]
Tracing input files...
Tracing input files: api/create.js
Trace complete [4065ms]
> Built @now/node@latest:api/create.js [9s]

Generation complete!
```

... that said, 10s is still a long time to wait every time a function is invoked, especially (but not only) when the function hasn't been edited between calls. Is there something I'm doing wrong, or another issue on general `now dev` performance I can upvote?

**Comment by jeantil** [comment]
@donmccurdy make sure you are not somehow making the requests with a devtool open which sends cache-busting headers ( `pragma: no-cache` for instance) since that forces a rebuild of the lambda (though the  documentation seems to have moved and I can't find the reference anymore and I never figured out the rationale for idoing a rebuild in the context of @now/node, it could make sense in the context of @now/next)

**Comment by donmccurdy** [comment]
That's it, thanks! I always develop with dev tools open (this is a requirement for me). I disable the cache in the _Network_ tab based on headaches I've had in past projects, although I guess I can do without that here.

Given the logged output `Installing dependencies...`, I'd never have guessed the "Disable Cache" option was to blame here... if that behavior needs to remain the default on `@now/node`, could we consider (a) logging a bit more info, like `Built @now/node@latest:api/create.js  because no-cache header was set [9s]`, or (b) giving an option to disable the no-cache rebuild?

**Comment by jeantil** [comment]
You have no idea how I would like that : our Typescript functions take 30s
to 1min to build :/.

Le mer. 5 févr. 2020 à 18:55, Don McCurdy <notifications@github.com> a
écrit :

**Comment by TooTallNate** [comment]
Note that the "rebuild upon `no-cache` header" functionality has been removed as of https://github.com/zeit/now/pull/3328.

**Comment by donmccurdy** [comment]
Glad to hear! I assume that'd be upcoming in now v17?

**Comment by TooTallNate** [comment]
Correct.
