### ISSUE TITLE
Spec out improved function configuration

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2643]
There are several items in `now.json` that are not yet spec'd out for function config:

- Maximum memory size
- Maximum duration

**Comment by ties-v** [comment]
Question that pops up in my head is what happens when such limit is hit by the application? I can understand that an out of memory exception or timeout results in a lambda in bad state, right?

So will the lambda be killed then, resulting in a cold start on the next request? This because when you have a slow process and stop the execution, it will continue next time if you enable it again, or fail randomly. 

--

Other thing is how fine grained the memory size should be. Steps of 256MB should be fine, I guess?
For the maximum duration I would suggest taking seconds as unit.

**Comment by styfle** [comment]
This feature was announced today!

https://zeit.co/blog/customizing-serverless-functions
