### ISSUE TITLE
Underline links for errors

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2647]
As you might know, we're showing links for e.g. when no `build` script exists.

We want to highlight the link there, as currently it's very easy to miss:

- Underline it
- Use the same color has the `localhost:3000` in `now dev` logs

**Comment by AndyBitz** [comment]
Since those errors can come from an API or a from a function from a different package, it might be a good idea to parse error messages and check for `http` or `https`

**Comment by leo** [comment]
@AndyBitz instead, i recommend setting a new field in the payload that can contain a error URL.

**Comment by AndyBitz** [comment]
@leo That would mean removing the URL from the `message`, which would cause older clients not to display it anymore

**Comment by TooTallNate** [comment]
@AndyBitz Not necessarily. The cli could use that field in the response and replace the plain-text link with the styled version. Something like:

```js
const message = err.message.replace(err.link, chalk.cyan.underline(err.link));
```

**Comment by AndyBitz** [comment]
@TooTallNate @leo that would work, but I think there are a lot of errors that originate from different utils which we would need to update and we would also need to make sure that this property is sent by the service, since some might just sent `code` and `message`.

We could do this over time, but it might get confusing, for us to keep track and for users who will sometimes see a styled link and sometimes not.

Maybe we could do it like this:

```javascript
const links = err.message.match(/(https?:\/\/[^ ]+)/g);

for (const url of links) {
  err.message = err.message.replace(url, link(url));
}
```
