### ISSUE TITLE
Comments in now.json

### ISSUE THREAD

**Issue by borekb** [vercel/vercel#2723]
Would be great to be able to add comments to `now.json`, similarly to what's possible in VSCode `settings.json` or TypeScript's `tsconfig.json`.

Right now:

```
$ now dev
> Error! Couldn't parse JSON file /Users/borekb/example/now.json.
```

**Comment by markozxuu** [comment]
@borekb  It's good idea, It would be excellent to implement it as a feature in the future. I guess it will be useful for some users. 

What you think ? @AndyBitz @leo

**Comment by wtgtybhertgeghgtwtg** [comment]
It was rejected over in #1673, but wouldn't allowing configuration to be done in a format that naturally takes comments (`now.yaml`, `now.config.js`) be neater?

**Comment by leo** [comment]
Thanks for reporting this. I think we can indeed look into making comments work.

**Comment by jjangga0214** [comment]
+1 for `now.config.js` or `now.yml`

**Comment by PutziSan** [comment]
Hi, would you be open to using [json5](https://github.com/json5/json5) instead of `JSON.parse`? 

Would it already be enough to exchange it [here](https://github.com/zeit/now/blob/c511147c7ccb614a37313093368088ba84ced80c/packages/now-cli/src/util/read-json-file.ts#L13), or is this a bigger undertaking?

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
