### ISSUE TITLE
Ability to add secrets without revealing the secret

### ISSUE THREAD

**Issue by tunjos** [vercel/vercel#2745]
OS: **Ubuntu 18.04.2**
Now CLI version: **16.1.1**

### Current situation:
When adding a secret
```bash
now secret add <name> <value>
```

- The value is exposed on the command line while typing
- The whole command(**including the secret**) is logged to the `.bash_history` file

### Proposed solution:
When adding a secret
```bash
now secret add <name>
prompt$
Enter value for <name>: ******
> Success! Secret <name> added (<user>) [500ms]
```

- The value won't be exposed on the command line while typing
- The whole command(**excluding the secret**) is logged to the `.bash_history` file

Cheers!✌️

**Comment by TooTallNate** [comment]
This is a nice idea, thanks for the recommendation. Feel free to take a stab at a pull request, otherwise we'll prioritize it appropriately at some point in the future.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
