### ISSUE TITLE
Allow multiple now.json config files and add a way to specify one.

### ISSUE THREAD

**Issue by saimeunt** [vercel/vercel#275]
Use case : I need to differentiate between staging and production environments so I'd like to use 2 different config files (`staging.now.json` and `production.now.json`).

The now CLI tool help indicates that you can specify a config file using `--config=FILE`:

```
    -n, --name                Set the name of the deployment
    -c FILE, --config=FILE    Config file
    -d, --debug               Debug mode [off]
```

But it looks like this is to set another config file (`.now.json`) which is used to store the account login token.

It would be super nice to allow another flag for the CLI in order to specify what `now.json` to use because this is hardcoded right now (https://github.com/zeit/now-cli/blob/cb7fb54805dcbdb2e876ff73d5cb76786e8b7334/lib/read-metadata.js#L32).

Thanks and keep up the good work :)

**Comment by bpartridge83** [comment]
What about adding a level to `env` to specify one set of key:value or another key:value set depending on which env is specified? My use-case is related to the `NODE_ENV` environment variable, so a specific implementation could be:

`
...
    "env": {
        "production": {
            "REDIS_URL": "redis://1..."
        },
        "staging": {
            "REDIS_URL: "redis://2..."
        }
    }
  }
...
`

I'd actually prefer to set most of my variables in secrets instead of committing them to the codebase.  I guess one workaround would be a secret key prefix, relying on a deploy environment variable. `now secret add production-acme-api-key value1` with `now -e SECRET_PREFIX="production"` and `process.env[process.env.SECRET_PREFIX + "-production-acme-api-key"]`... but that's kind of messy. 😄

**Comment by saimeunt** [comment]
I guess this new feature in 4.2.0 (https://github.com/zeit/now-cli/pull/284) pretty much addresses this feature request.

Now that env is taken care of by using dotenv, the only property from now.json that makes sense having different values in staging/prod would be aliases I guess.

**Comment by jamo** [comment]
Indeed adding a support for selecting to a now.json (for project configuration, not for auth) would be super cool. cc/ @leo

**Comment by saimeunt** [comment]
So now that `--alias` is being deprecated, we really need this feature to be able to automatically alias to different URLs depending on the environment.

I get the point of always getting a new URL for staging (https://twitter.com/zeithq/status/831282772618653697), but sometimes you need to refer to a fixed staging URL in third party services (slack integrations, oauth applications, etc...).

**Comment by jesseditson** [comment]
I needed this (I had the use case @saimeunt had above, staging needs a fixed API url), so I made this https://github.com/jesseditson/now-deploy while we wait for a first-party feature!

**Comment by leo** [comment]
This will be the solution: https://github.com/zeit/now-cli/issues/436. Please add any more suggestions there! I'll tackle it after you've all confirmed with it.
