### ISSUE TITLE
Upload .env to generate secrets automatically

### ISSUE THREAD

**Issue by ivoilic** [vercel/vercel#2758]
Right now if you have a lot of secrets it's tedious to add them one by one. Instead it would be cool to have them read from a .env file. They could be automatically saved with a name like this: `projectname-this_is_a_secret` that way they are unique to the project.

**Comment by nickredmark** [comment]
important: one should be able to define which .env file, since usually .env contains local versions of those secrets

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
