### ISSUE TITLE
Running a lambda during the build

### ISSUE THREAD

**Issue by vzaidman** [vercel/vercel#2790]
Hey!
I want to **save my website's HTML as a PDF file during the build process** by using a chrome aws lambda. Is this possible?

This is what I tried to do but it failed because the server running it had no chromium

```
const chrome = require('chrome-aws-lambda');
const puppeteer = require('puppeteer-core');

async function createPdfFile(html, dist) {
	const browser = await puppeteer.launch({
		args: chrome.args,
		executablePath: await chrome.executablePath,
		headless: chrome.headless,
	})

	const page = await browser.newPage()

	await page.setCotent(html);

	const file = await page.pdf({
		path: dist,
		printBackground: true,
		format: 'A4'
	})

	await browser.close()

	return file
}

module.exports = html => {
	const interval = setInterval(() => console.log('building pdf cv'), 2000)

	createPdfFile({html, dist: 'dist/vitali_zaidman_cv.pdf'})
		.catch((...args) => console.error(...args))
		.then(() => clearInterval(interval))
}
```
The repo can be found here:
https://github.com/vzaidman/vzaidman.com/tree/test

related issue: #1643

**Comment by ghost** [comment]
Hello! I would like to be able to let you know that I was able to run Chrome(‐ium) in a Now build by using  [`@serverless-chrome/lambda`](https://www.npmjs.com/package/@serverless-chrome/lambda).

The build environment is similar enough to lambdas’s. It seems to be running on AWS ECS Fargate. (Note that I don’t have much experience with AWS to be able to tell what this implies, but just as lambdas, it runs Amazon Linux.)

What I needed to do first, however, was to install a font for Chrome to use, as there are none present by default during the build. (There are, however, fonts installed in lambdas, at least if you don’t use Node 10.x, see alixaxel/chrome-aws-lambda#37.)

I have the following build script:

`build/build.bash`:
```Bash
#!/usr/bin/env bash

set -e

mkdir -p /tmp/.fonts
mv build/fonts/font.otf /tmp/.fonts

export FONTCONFIG_PATH="$PWD"/build/fontconfig

node --experimental-modules use-chrome.mjs
```

I needed to have a font in my input to Now. For that, I used a simple font I made earlier this year (since I was trying to render an SVG, and didn’t need Chrome to render text anyway), but you can use any font. I put the font file in the path `build/fonts/font.otf`, although you can use other path and/or format, just remember to change it in `build.bash` too.

I also needed to have a `fonts.conf` file present, to tell Chrome where the font I used was located.

`build/fontconfig/fonts.conf`:
```XML
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
	<dir>/tmp/.fonts</dir>
</fontconfig>
```

You can put it on a different path if you would prefer, but don’t forget to also change it in `build.bash`.

Finally, I was able to use Chrome from JavaScript:

`build/use-chrome.mjs`
```JavaScript
import puppeteer from "puppeteer-core"
import launch from "@serverless-chrome/lambda"
import fetch from "node-fetch"

let main = async () =>
{
	let browser = await puppeteer.connect(
	{
		browserWSEndpoint: (await (await fetch(`${(await launch({flags: ["--v=-99", "--headless"]})).url}/json/version`)).json()).webSocketDebuggerUrl
	})
	
	// Use 'browser' here.
}

main()
```

I passed the `--v=-99` flag to work around a current bug in `@serverless-chrome/lambda` (see adieuadieu/serverless-chrome#200). The `--headless` flag was so I could test my `use-chrome.mjs`  program locally without it opening a new Chrome window.

In case it wasn’t inferable, this is how my `package.json` looks:

`package.json`
```JSON
{
	"scripts": {
		"build": "bash build/build.bash"
	},
	"devDependencies": {
		"puppeteer-core": "1.7.0",
		"@serverless-chrome/lambda": "1.0.0-55",
		"node-fetch": "2.6.0"
	},
	"engines": {
		"node": "8.x"
	}
}
```

Notes:

+ I do realize I don’t need the `#!/usr/bin/env bash` line anyway (since I’m running the script by calling `bash` explicitly), but I decided to keep it out of habit.
+ For some reason, my build fails from time to time. I *think* this is because I am using an improper Puppeteer version for the Chrome version bundled with `@serverless-chrome/lambda`. (Puppeteer 1.7.0 is for Chrome 70, whereas `@serverless-chrome/lambda` 1.0.0-55 bundles Chrome 69.) If this is the case, then I could probably fix this by setting a `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` build environment variable in `now.json`, and installing an older version of puppeteer. (The lowest version of the `puppeteer-core` package on NPM is 1.7.0, although there are lower version of `puppeteer`).

I hope this helps!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
