### ISSUE TITLE
[Feature Request] logs by file path

### ISSUE THREAD

**Issue by Kikobeats** [vercel/vercel#2794]
<img width="854" alt="Screenshot 2019-08-18 at 18 28 35" src="https://user-images.githubusercontent.com/2096101/63327811-37e2cb00-c32f-11e9-9556-caf42f683d83.png">

Hello,

ZEIT website allows you to show logs associated with the deployed URL and filtering them by file path.

Just I want to do the same using Now CLI, something like:

```
now logs https://my.now.sh -f -p api/screenshots
```

**Comment by leo** [comment]
Thanks for creating the issue. I think this would be a great idea!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
