### ISSUE TITLE
List now secrets by name

### ISSUE THREAD

**Issue by glennreyes** [vercel/vercel#2803]
Running `now secrets ls` currently lists all secrets ordered by the date created. Since most of us have them prefixed, say eg. `google-client-id`, `google-client-secret`, etc. it would be helpful to have them displayed them sorted by the secret name (especially when having hundreds of secrets).

Is there any way you can list them like this?

**Comment by leo** [comment]
Really good idea, thanks! We'll look into this.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
