### ISSUE TITLE
Provide a `--skip-alias` or `--target none` option to allow aliasing to be skipped during deployment

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2807]
Allowing _stealth_ deployments to be made with only the deployment URL and no aliasing.

`now --skip-alias` or `now --target none`

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
