### ISSUE TITLE
Rendering wrong update message

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2811]
This should be rendering the update message with `-g` instead:

![image](https://user-images.githubusercontent.com/6170607/63459639-31e70a00-c455-11e9-92e8-fd8874bdc4a4.png)

**Comment by erikras** [comment]
Gonna throw this here since it's kinda related. `yarn global upgrade now` somehow doesn't update `now`. But `yarn global add now` does. Seems like `yarn`'s fault, but maybe change the message until it's fixed?

![web 2019-08-22 10-55-34](https://user-images.githubusercontent.com/4396759/63501202-8927c180-c4cb-11e9-8a4d-f33b98bbf630.jpg)

**Comment by AndyBitz** [comment]
@erikras The yarn update message was already changed in a newer version, the version in your screenshot `15.8.5`, showed indeed an incorrect command

**Comment by AndyBitz** [comment]
This probably only happens with `nvm`, for everyone else it will display the correct update message.
