### ISSUE TITLE
[now-client] Check ~/.now/auth.json for auth token

### ISSUE THREAD

**Issue by rtsao** [vercel/vercel#2820]
If the client isn't passed a token, it should use the token in `~/.now/auth.json` if it exists. Then this client can work just like the CLI if users are already logged in.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
