### ISSUE TITLE
Reading the project/deployment context from the current dir

### ISSUE THREAD

**Issue by nkzawa** [vercel/vercel#2822]
```sh
$ cd ./my-app
$ now
... 
> Deployed to https://my-app.nkzawa-zeit.now.sh

$ now logs 
# logs of the latest deployment for the current dir when no URL is specified

$ now inspect
# ditto
```

It might be great if it could work since it's annoying to copy-paste/type/remember urls.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
