### ISSUE TITLE
Using @now/node with transpiled code doesn't work as expected.

### ISSUE THREAD

**Issue by arcdev1** [vercel/vercel#2834]
I have included a build step in my deployment by adding a `now-build` script to my `package.json` as described at: https://zeit.co/docs/v2/deployments/official-builders/node-js-now-node/#build-step 

My `now-build` script uses babel to transpile my javascript code and output it to a new directory called `dist`. It is this transpiled code that I want to deploy, so I have specified this in my `now.json` by adding the following to the builds array:

```json
 { "src": "api/hello/dist/index.js", "use": "@now/node" },
```

Unfortunately, @now/node checks for the existence of `api/hello/dist/index.js` BEFORE executing the `now-build` script. This means that if I want the deployment to work I need to keep a `dist` folder with an `index.js` file lying around. This is not ideal, but not terrible when deploying from a local machine.

When adding GitHub integration, things get messy. Because now I have to check-in a `dist/index.js` to make sure that the automated build works. I don't want to have to checkin auto-generated, transpiled code. 

In my mind it should work the other way around. The build should run my `now-build` script BEFORE looking for the build's `src` file. Am I missing something?

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
