### ISSUE TITLE
Docker support at build time

### ISSUE THREAD

**Issue by hanabi1224** [vercel/vercel#2842]
It will be awesome to have the build utility to install docker on Amazon Linux AMI in build phase so that builders can use sdk docker image to build languages like rust, dotnet, etc.  Currently builders handle sdk installation by itself (like in rust-builder) which is not a scacalable solution for more statically compiled languages

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
