### ISSUE TITLE
Consider allowing `@now/node` to transpile via Babel

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [vercel/vercel#2851]
There's a slight discrepancy moving from a `next` API to a `now` API in terms of Babel support.

```js
import {NowRequest, NowResponse} from '@now/node';
// With `babel-plugin-macros` set up in `.babelrc`.
import preval from 'preval.macro';

// Works as expected  `pages/api/onePlusOne`, since `next` can use `.babelrc`.
// Does not work as expected in `api/onePlusOne`, since `@now/node` does not.
export default (_req: NowRequest, res: NowResponse) => {
  res.status(200).send(preval`module.exports = 1 + 1`);
};
```

Currently, `@now/node` can run its source through Babel, but it's limited to a `@babel/plugin-transform-modules-commonjs` transformation.  Would it be feasible to allow that to be overridden by a user-provided `.babelrc` or something?

This could also be a solution to zeit/now-cli#2834.

**Comment by larafale** [comment]
+1

**Comment by leo** [comment]
Thank you for this feature suggestion!

I do think it's a great idea. At the moment, however, our plan is to put more work on frameworks: For example, Next.js nowadays allows for adding an `api` directory and you can then configure all the Babel settings there.

I'm not 100% opposed to this, but I do think it's a great idea to leverage the existing systems frameworks provide and push more towards having them handle the APIs.

**Comment by larafale** [comment]
@leo is it possible to instruct @now/node to require a module (thinking of esm) ?

babel is great but i kind of like the simplicity of esm and being able to use es6 & more out of the box for small node apps.

Can I do the equivalent of `node -r esm` in the now.json @now/node builder ?

thanks for your feedback.

**Comment by larafale** [comment]
@styfle I'm talking about this module https://github.com/standard-things/esm
don't want to follow the esm spec with `.mjs` etc, just want to tell @now/node to require that module.

**Comment by larafale** [comment]
I know, but I want import/export, and esm provides it out of the box :)
also interesting to know beyond that use case if it's possible to inject modules to @now/node (via the builder config in now.json) the same way we can `node --require somemodule` with raw node binary.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
