### ISSUE TITLE
Zero-config support for Jekyll

### ISSUE THREAD

**Issue by sarupbanskota** [vercel/vercel#2852]
That will hopefully help us get rid of https://github.com/zeit/now-examples/blob/master/jekyll/package.json

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.

**Comment by pke** [comment]
So whats the current state on this? A jekyll deploy still needs the `package.json` I have just checked it. 
The [example](https://github.com/zeit/now/tree/master/examples/jekyll) describes it as "optional" which is misleading. It should include the `package.json` in the example folder so that running `now` actually deploys a useful jekyll static site instead of the `index.md` file verbatim.

And again, I really can't say I like your move towards "black-hole only email feature requests" that you only track in your internal tools.
