### ISSUE TITLE
Support Gatsby.js redirects out of the box

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2855]
Since [Gatsby.js](https://www.gatsbyjs.org/) allows you to configure redirects, I'd be great if we could automatically turn them into routes.

We first need to come up with a spec for this.

**Comment by leo** [comment]
Once this is done, we'll move [Dan Abramov's blog](https://github.com/gaearon/overreacted.io/blob/master/now.json) to zero config (no now.json).

**Comment by lucleray** [comment]
What I suggest is the following:
- create `gatsby-plugin-now` that hooks into gatsby system and extracts `redirects` created by the user into a "redirect-manifest.json" file
- automatically inject this plugin when running `now` on a gatsby website
- read the generated "redirect-manifest.json" file to generate `defaultRoutes`

I'd love to directly read gatsby redirects in the filesystem but I don't think that it is possible because redirects are dynamically generated (see https://github.com/gatsbyjs/gatsby/blob/master/examples/using-redirects/gatsby-node.js).

**Comment by leo** [comment]
Let's make the plugin work without injecting it for now! 👍

**Comment by lucleray** [comment]
@leo The plugin works without injecting (on `canary`). Now, do we want to inject automatically or document on adding the plugin?

**Comment by leo** [comment]
@lucleray We want to document the plugin.

**Comment by leo** [comment]
Closed in favor of https://zeit.atlassian.net/browse/PRODUCT-91?atlOrigin=eyJpIjoiODEzYjM5ZWZiN2Y3NGJkY2E1ZDJlNTc5M2I3OTQ3YTQiLCJwIjoiaiJ9
