### ISSUE TITLE
Set header for parent domain

### ISSUE THREAD

**Issue by akashdsouza** [vercel/vercel#2868]
I would like to set `includeSubDomains, preload` on `Strict-Transport-Security` header. While I'm able to set it on all pages using `routes`, I couldn't figure out how to do the same on the parent domain itself i.e., [example].now.sh

Setting it on a sub domain like `mysite.[ex].now.sh` is not valid as I checked at https://hstspreload.org/

**Comment by leo** [comment]
Hey!

In order to set the header on your parent domain, you need to deploy directly to the parent domain.

For example, if you want to send headers from `example.now.sh`, you need to add `example.now.sh` to the "Production Domains" section in your project. In turn, your deployment (the one sending the headers) will be available under that domain.

Let me know if you have more questions!
