### ISSUE TITLE
Basic HTTP auth guide

### ISSUE THREAD

**Issue by sergiodxa** [vercel/vercel#2869]
Document how to setup a basic HTTP auth layer over a Now deployment.

- [ ] Basic HTTP server
- [ ] Express app
- [ ] NGINX or Apache Dockerfile

**Comment by timothyis** [comment]
I've actually moved this to the ZEIT Now core repo since this is a platform feature request. cc @msweeneydev

**Comment by leo** [comment]
Just recently, @rauchg has written a spec (private) for adjusting the CDN in such a way that these kinds of features could be implemented. Once that's done, we will look into this.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.

**Comment by callumlocke** [comment]
@leo Is this feature still being worked on?

**Comment by timothyis** [comment]
We released a feature that allows baked in auth @callumlocke 🙌🏼 https://vercel.com/blog/protecting-deployments
