### ISSUE TITLE
Use a subdomain and its subsubdomains

### ISSUE THREAD

**Issue by lcswillems** [vercel/vercel#2952]
Hi,
If I push to Zeit, is it possible to use the subdomain that is given to me along with its subdomains?
My website is splitted over several subdomains.

**Comment by tedmiston** [comment]
I just tested and was able to successfully deploy to `foo.bar.<my domain>` as well as `foo.<my domain>` with Now.  I use external DNS for the CNAME but I imagine it should work for managed DNS as well.  I did have to add CNAME records for both `foo` and `foo.bar`.

**Comment by leo** [comment]
Thanks for reporting this. We'll take a look at whether this will make sense for us to support in the future.

**Comment by lcswillems** [comment]
Thank you @tedmiston for your answer!
When you say "I use external DNS for the CNAME", you mean you use your custom domain name, not the subdomain given by Zeit?

**Comment by tedmiston** [comment]
Yes, I use a custom domain name, and then with my custom domain name I use my domain registrar's DNS service.

**Comment by lcswillems** [comment]
Okay, thank you for your answer!! 

Could I ask you what is your domain registrar? Because, currently, I bought my domain name with my shared web hosting and I don't know how to use my domain name with Zeit.

Anyway, thank you for your help again :)

**Comment by tedmiston** [comment]
Sure, the registrar for this one is [Google Domains](https://domains.google/).  I am using a .dev domain, so in this case Google is also the registry for that TLD (though I don't think that makes a difference here).

Here's an example of how to do the CNAME in Google's DNS, but it is is pretty similar for most registrars.

https://support.google.com/domains/answer/9211383?hl=en&ref_topic=9018335

I used the Zeit guide on [Custom Domains](https://zeit.co/docs/v2/custom-domains/).  I went with Option 2 only because I'd like to have other DNS records on the domain outside of Zeit; if you don't need that, Option 1 is simpler and I've used it on other domains as well.

**Comment by lcswillems** [comment]
Thanks a lot for your help!!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
