### ISSUE TITLE
Support pnpm as an alternative to Yarn

### ISSUE THREAD

**Issue by elliottsj** [vercel/vercel#2973]
See https://spectrum.chat/zeit/now/now-dev-use-pnpm-install-rather-than-yarn-install~e685e0cf-1cd1-48ba-91f8-e74897db7a13

As suggested by @jamescoyle:

>Would this be possible to add in? Wouldn't something as simple as an option in the now.json file which specifies the install command work?
>Or even `now dev --install="pnpm install"` or something.

**Comment by styfle** [comment]
We used to install dependencies when you run `now dev`.

That is no longer the case in the latest release.

Please update to the latest CLI `npm i -g now` and you can use pnpm or your favorite package installation method with `now dev`.

**Comment by elliottsj** [comment]
I think that Now should also support using pnpm for deployments. It'll help avoid issues where a website works fine using pnpm locally with `now dev`, but fails in production after deploying.

pnpm has a stricter `node_modules` structure than Yarn, so package resolution behaves differently.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
