### ISSUE TITLE
Prevent using environment variables that don't match AWS' rules

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2982]
Currently, we accept variables that start with `_`, for example. In https://github.com/zeit/api/issues/862, the API will be fixed so that `now` automatically throws an error for those, as [AWS doesn't allow them](https://docs.aws.amazon.com/lambda/latest/dg/env_variables.html).

However, we still need to ensure that `now dev` prints a validation error and exits immediately if it notices a environment variable in `now.json` that does NOT comply with the [AWS rules](https://docs.aws.amazon.com/lambda/latest/dg/env_variables.html).

**Comment by TooTallNate** [comment]
I don't think we want `now dev` to exit immediately in this case. For other validation errors (i.e. no matching builds, syntax error in `now.json`, etc.) we print a warning to now dev and ignore the change, so that the user doesn't need to constantly be restarting the server.

In this case I think it's reasonable to warn that the env var name is invalid and will be ignored.
