### ISSUE TITLE
Now routes with subdomains

### ISSUE THREAD

**Issue by lcswillems** [vercel/vercel#3005]
Hi,

I have a folder with two Next.js apps in two subfolders: `test1` and `test2`. 

I would like the Next.js app in the `test1` subfolder to be reachable from `test1.mydomain.com` and the Next.js app in `test2` to be reachable from `test2.mydomain.com`.

I tried to put this in my `now.json`:

```
{
  "builds": [
    { "src": "test1/next.config.js", "use": "@now/next" },
    { "src": "test2/next.config.js", "use": "@now/next" }
  ],
  "routes": [
    { "src": "http://test1.mydomain.com/(.*)", "dest": "test1/$1" },
    { "src": "http://test2.mydomain.com/(.*)", "dest": "test2/$1" }
  ]
}
```

But it doesn't work. How could I do?

I also develop on my local machine using `test1.mydomain.**loc**` and `test2.mydomain.**loc**`. So, I would like the solution to be working locally (with `now dev` if possible).

**Comment by styfle** [comment]
Hi @lcswillems 

You might be able to achieve this by adding two aliases and then configuring routes.

```json
{
  "alias": [ "test1.mydomain.com", "test2.mydomain.com" ],
  "builds": [
    { "src": "test1/package.json", "use": "@now/next" },
    { "src": "test2/package.json", "use": "@now/next" }
  ],
  "routes": [
    { "src": "http://test1.mydomain.com/(.*)", "dest": "/test1/$1" },
    { "src": "http://test2.mydomain.com/(.*)", "dest": "/test2/$1" }
  ]
}
```

But I don't think `src` allows full URLs, only paths.

So at this time, you might have to create two separate deployments, each with their own domain.

**Comment by lcswillems** [comment]
Thank you for your answer!

The problem is that I am using a monorepo and my two folders share code. Is there a way to do it with monorepos?

It would be very convenient to allow url in routes.

Note : I use Yarn workspaces.

**Comment by styfle** [comment]
One solution could be looking at the [`host`](https://zeit.co/docs/v2/network/headers#host) header and perform routing in your own code.

This is what https://badgen.net and https://flat.badgen.net do to show different badges from the same deployment.

https://github.com/badgen/badgen.net/blob/90b1144062434373baf667f0b6fb2a30274faea9/components/badgen-title.jsx#L72

**Comment by lcswillems** [comment]
Thank you for sharing me this page!

However, this is not an example of "routing". It is done frontend. Is there a way (with micro for example) to choose which Next.js code to use given the host header?

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
