### ISSUE TITLE
Use environment variables in now.json routes

### ISSUE THREAD

**Issue by phuoccss** [vercel/vercel#3050]
Hi is it possible to embed environment variables into now routes?

For example
```js
  "routes": [
    ...
    {
      "src": "/api/subscribe",
      "dest": "https://backend.com/some_route/${@route}"
    },
    ...
```

**Comment by styfle** [comment]
Hi @universse 

No, this is not possible.

You can use named patterns to rewrite urls as seen in the docs: https://zeit.co/docs/v2/advanced/routes#route-parameters

Can you elaborate on your particular use case?

**Comment by phuoccss** [comment]
I am using now routes as proxy basically.

I want to add user to the subscriber list, using an email marketing service. They expose their api with a url something along the line of https://service.com/?api_key=API_KEY.

So the requests to `/api/subscribe` will be proxied to the above url. This way I don't have to create a server to handle subscription.

`API_KEY` shouldn't be exposed so I'm setting it as environment variable. The problem is I don't have any way to use it in `now.json`.

**Comment by lasersox** [comment]
@styfle We have a similar use-case. Our API server is presently mapped like: `{ "src": "/api/(.+)", "dest": "https://api.example.com/$1" }`

At deploy time I'd like to be able to substitute a different base path using an env variable. Eg, 

now deploy --env "API_HOST=https://api-v123.example.com" and have this substituted into the route like: `{ "src": "/api/(.+)", "dest": "${API_HOST}/$1" }`

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by botverse** [comment]
@leo is the roadmap publicly available? 

I am interested in the same feature, but feel that I have to ask directly because the discussion is not public like it would be in this issue.
