### ISSUE TITLE
`now inspect <id>` should be implemented

### ISSUE THREAD

**Issue by paulogdm** [vercel/vercel#3059]
## Motivation

When using the usage `.csv`, we can't get meaningful information because all the deployments have only the `id`. There are no commands to see the deployment URL (`.now.sh`) behind that `id` and it would be really useful to know that information.

## Proposal
```
$ now inspect dpl_3BsJHEkNkMkpTESLKaAreZMfduio
> Fetched deployment "nodejs-apamojuq4.now.sh" in pgdm [2s]

  General

    version     2
    id          dpl_3BsJHEkNkMkpTESLKaAreZMfduio
    name        nodejs
    readyState  READY
    url         nodejs-apamojuio.now.sh


  Builds

    ┌ yarn.lock           Ready               [0ms]
    └── yarn.lock
    ┌ api/index.js        Ready               [8s]
    └── λ api/index.js (8.73KB) [sfo1]
    ┌ api/date.js         Ready               [9s]
    └── λ api/date.js (238.5KB) [sfo1]
    

  Routes

    ╶ ^/api/(index|index\.js)?$      ->      /api/index.js      
    ╶ ^/api/(date|date\.js)$         ->      /api/date.js      
    ╶ /api(\/.*)?$                                              [404]
```

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
