### ISSUE TITLE
Unclear that yarn is being used in now-cli

### ISSUE THREAD

**Issue by sedubois** [vercel/vercel#310]
Taking over conversation from https://github.com/zeit/now-cli/issues/153#issuecomment-279761171

@TooTallNate the problem is that, whereas the web console shows that, the CLI version doesn't agree, it truncates the messages and this is all that's visible:
```
$ now
> Deploying ~/Documents/relate
> Using Node.js 7.0.0 (default)
> Ready! https://relate-nhxizwsjpv.now.sh (copied to clipboard) [3s]
> Upload [====================] 100% 0.0s
> Sync complete (6.46kB) [2s] 
> Initializing…
> Building
> ▲ npm install
>  ‣ react-no-ssr@^1.1.0
>  ‣ redux-thunk@^2.2.0
>  ‣ session-file-store@^1.0.0
>  ‣ eslint-plugin-react@^6.4.1
>  ‣ express@^4.14.1
>  ‣ next-routes@^1.0.14
>  ‣ react-intl@^2.2.3
>  ‣ smooch@^3.11.0
>  ‣ uuid@^3.0.1
```

**Comment by TooTallNate** [comment]
Right, good point. I guess this is happening because of the way scrollback is "deleted" by the `now` CLI during the npm install step.

Easiest solution would be to remove that behavior and just show all the output. This would be consistent with the web console output at least. Or other thoughts, @rauchg @matheuss @leo ?

**Comment by leo** [comment]
Should be [fixed](https://github.com/zeit/now-cli/commit/ea35eb19ee0ee2d6a177f91473abca811acfaaf3)!
