### ISSUE TITLE
Add `--target` value as build-time environment variable 

### ISSUE THREAD

**Issue by jasongwartz** [vercel/vercel#3119]
Possibly related to: https://github.com/zeit/now/issues/2192

When using the @now/static-build strategy, it would be ideal to have build-time access to the current target/environment (eg. 'staging' vs 'prod').

My intended use-case is for a payments frontend, where we will bake a different public key into the bundle (a test key vs. a production key), or add a UI element indicating that the currently-viewed deployment is a test environment - but I can imagine many cases where this would solve issues with simple production vs. non-production configuration diffs.

I'd suggest a simple implementation where the value of `--target` is simply added as a build-time environment variable, perhaps as something like `NOW_TARGET`. This could also be, in theory, added as a runtime environment variable too.

**Comment by jasongwartz** [comment]
I'm going to work on a proposed implementation on the following branch: https://github.com/zeit/now/compare/canary...jasongwartz:jg-target-env?expand=1

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
