### ISSUE TITLE
Stuck at Building

### ISSUE THREAD

**Issue by navdeepsingh** [vercel/vercel#3145]
Simple nodejs application with this command
`"build": "NODE_ENV=production PORT=1565 node index.js"`

It stucks at building. Help!

**Comment by styfle** [comment]
Indeed, this will never build because you are invoking node to listen instead of build.

It sounds like you probably don't need a build step. So instead you can create an api folder with an index file like this: `/api/index.js`

See an example introduction here: https://zeit.co/docs/v2/serverless-functions/introduction

**Comment by navdeepsingh** [comment]
Yeah, it makes sense. Its same alike AWS Lambda Functions.
