### ISSUE TITLE
Aliases keep reverting to much older version

### ISSUE THREAD

**Issue by tjkohli** [vercel/vercel#3146]
We're happy to provide more details. This affects all of our projects and has happened 4 times in past 24 hours!

**Comment by styfle** [comment]
Hi @tjkohli 

It would be great to get more details. Are you still having this problem?

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.
