### ISSUE TITLE
[now.json] Route `methods` not taken into account in Dev AND Prod

### ISSUE THREAD

**Issue by hormesiel** [vercel/vercel#3160]
One of my route's `"methods": ["POST"]` directive is completely skipped both when running `now dev` and when deployed.

## Reprod

- Deployment : https://issue-now-route-methods.flawyte.now.sh/api/contact
Should return a 404 but instead returns a 200 with the message from the lambda.

- Source : https://github.com/flawyte/issue-now-route-methods

## Additional info

- `now --version` : `16.3.1`

**Comment by TooTallNate** [comment]
Hey there @flawyte, thanks for the detailed repro instructions.

It turns out that this is a misunderstanding of how the `routes` array is processed. I have [created a PR on your repo](https://github.com/flawyte/issue-now-route-methods/pull/1) with my suggested fix and an explanation of the changes. Please take a look and let me know if you have any more questions. Cheers!
