### ISSUE TITLE
[@now/node] Body parser helper does not cast bracket notated fields to an array

### ISSUE THREAD

**Issue by josiahwiebe** [vercel/vercel#3161]
The built-in Node `querystring` package does not support arrays or nested objects. Perhaps this isn't something you'd want to support but I thought I'd open an issue to start the discussion. If this is the intended behaviour, then please disregard.

## Replication
Try POSTing a body using `application/x-www-form-urlencoded` with fields containing an array like so: 
```
options[0]=one&options[1]=two&options[2]=three
```

The values returned by `req.body` will be:
```json
{
   "options[0]": "one",
   "options[1]": "two",
   "options[2]": "three"
}
```

## Expected Behaviour 
The `req.body` object should contain a value of:
```json
{
   "options": [
      "one",
      "two",
      "three"
   ]
}
```

Relevant code in the `@now/node` builder here: https://github.com/zeit/now/blob/canary/packages/now-node/src/helpers.ts#L33

**Comment by styfle** [comment]
It was not implemented because it is considered an extended feature of Express.

https://github.com/expressjs/body-parser#extended

We will consider adding this feature in the future, thanks!

**Comment by josiahwiebe** [comment]
Makes sense! Is there a particular reason to mirror Express? I know it's probably the most popular but it's not exactly the most performant. 

I'd be happy to create a PR to help out. I could see it as another configuration setting in the `now.json` file – perhaps something like this, especially if you want to stay aligned with Express:

```json
{
  "builds": [
    {
      "src": "my-file.js",
      "use": "@now/node",
      "config": { "helpers": { "enabled": true, "extended": true } }
    }
  ]
}
```
For that example, you'd have to expose to config object to the `helpers.js` file, but it could be doable.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
