### ISSUE TITLE
Disable auto alias for file deployment

### ISSUE THREAD

**Issue by amio** [vercel/vercel#3165]
Auto aliasing for file deployment seems not that useful, while it will leak the latest deployed file which users might not expect.

Like, here's rauchg's lastest file deployment: https://files.rauchg.now.sh
and zeiter's: https://files.zeit.now.sh/

**Comment by styfle** [comment]
There was discussion to change `files.<username>.now.sh` to something like `<thefilename>.<username>.now.sh` but this would suffer from a similar issue.

Static deployments are always "public" in the sense that the source code is the output when viewing the URL, so I'm not sure if the alias is a problem in this case.

Are you planning to share private files by deploying to Now?

**Comment by amio** [comment]
Not strictly private, a random address is good enough.

While with auto aliasing to a guessable address, I have to think about the visibility of the file everytime after I publish something. I feel it cost more than it offers.

Anyway it's just my experience, not sure if this feature would be more useful in other cases.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
