### ISSUE TITLE
Question: Are there any plans to support HTTP2 server push?

### ISSUE THREAD

**Issue by ChristophP** [vercel/vercel#3216]
I recently found myself wanting to take advantage of HTTP2 server push. With `now` awesome CDN. A search through the docs and on google search indicated that this isn't yet supported https://stackoverflow.com/questions/58596759/http-2-server-push-not-working-with-zeit-now.
Are there any plans to add that in the future?

Thanks for making `now`. :-)

**Comment by isaumya** [comment]
Not just you. I've been been asking about it since the day I started using Zeit and I even talked about it heavily on Spectrum. Check: https://spectrum.chat/zeit/now/http-2-server-push-not-working-with-zeit-now~f58134c3-1c74-42b4-aa40-cb391a5a44b6

I've also tweeted about it but it seems Zeit team is intentionally paying no head to it. 
Checkout the tweet: https://twitter.com/iSaumya/status/1189907174866030593?s=19

HTTP/3 is around the corner. Everyone supports server push except ZEIT. Honestly this is one of the big 👎 for Zeit in my opinion. If it's still not enabled then when it is going to be? After HTTP/3 launch, when we might be taking about some other web perf thing? God knows....

**Comment by rauchg** [comment]
HTTP/2 is fully supported. **Push will be supported in the future**, but you have to keep in mind that it might not be as advantageous as you think it is:

- https://twitter.com/jaffathecake/status/1191068842249863169
- https://twitter.com/addyosmani/status/1191071410631798784

For the ZEIT dashboard we use `<link rel=preload>` at beginning of our HTML (which gets streamed from our CDN) and we are extremely happy with the results it provides, with a much simpler setup.

PS: HTTP/3 will be supported as soon as possible.

**Comment by isaumya** [comment]
@rauchg First of all I have read the articles that you have given link to and still think it is very bad that Zeit doesn't support HTTP/2 Server Push yet (talking about it in Nov 2019, I mean seriously).

Now honestly I do and don't agree with those articles in some extent. If you ever watch a Google Talk or seminar, you will see it is never ever suggested to over use HTTP2 Server Push. It was created only for the critical contents. So that's where it should be used.

Regarding using preload on the HTML head (even I do that) but in this case the browser can only read the preload after getting the HTML and not getting some critical resources along with the HTML.

Also adding HTTP2 Server Push isn't critical if you are using a framework like Nuxt JS or using some serverMiddleware. You simply need to pass a Link header in the response (check the spectrum conversation for the code).

Honestly as Zeit forces to use the Zeit nameservers for domains so I can't keep the domain in Cloudflare and take advantage of HTTP2 Server Push which it supports for ages now. Anyways is there any ETA on when important feature can be expected? In the Spectrum chat one person said it's in roadmap for some time now and other person said no ETA. So, if you can atleast provide some kind of timeline, it would be really helpful.

**Comment by ChristophP** [comment]
@isaumya Thanks for sharing your side of the story. I can tell that you're quite a bit frustrated about the matter. I believe though, that it's better to voice your frustration in a more friendly manner. This issue is about sharing not ranting. I don't know about you, but I happen to use `now` services for free. They don't owe use anything, so friendlyness in Open source is important, otherwise the makers will loose all motivation.
@rauchg Thanks for the update.

**Comment by isaumya** [comment]
@ChristophP man I did explained my frustration in a friendly way. I did not use any bad language or even ranted about anything. I simply stated the facts.  Also if you feel that I am frustrated with this matter, then yes and honestly the reason behind it is that I had spent many days trying to setup HTTP/2 Server Push and after multiple attempts when I could not understand what was happening I checked every possible doc including this page: https://zeit.co/blog/http2-uploads and the crazy thing is not a single place mention that it is not available or in the roadmap and will be released in future. If it was mentioned somewhere at least I would not have wasted so much time to figure out why it is not working. In fact, the StackOverflow link you mentioned in the post is also posted by me when I was fighting to figure out why it wasn't working. Also to be very honest in my mind it never came that in 2019 any service can provide HTTP/2 support without server push as almost everyone supports that.

I am really sorry if you feel bad by reading my comments, that was not the intention. The intention was to clarify why I am asking for server push and it is not a bad thing (if implemented correctly).

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
