### ISSUE TITLE
Support Gatsby path rewrites and client-only routes

### ISSUE THREAD

**Issue by phuoccss** [vercel/vercel#3220]
Previously I wrote a custom plugin [gatsby-plugin-zeit-now](https://github.com/universse/gatsby-plugin-zeit-now/blob/master/src/gatsby-node.js), based on `gatsby-plugin-now`. I wanted to add support for [client-only routes](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/) and path rewrites (for proxying purpose).

```js
  // redirects
  redirects.forEach(({ fromPath, toPath, force, isPermanent, statusCode }) => {
    let status = isPermanent ? 301 : 302
    status = statusCode || status

    // path rewrites
    if (status === 200) {
      pre.push({
        src: fromPath,
        dest: toPath
      })
      return
    }

    const route = {
      src: fromPath,
      status,
      headers: { Location: toPath }
    }

    force ? pre.push(route) : post.push(route)
  })

  // client-only routes
  Array.from(pages.values())
    .filter(page => page.matchPath && page.matchPath !== page.path)
    .forEach(page =>
      pre.push({
        src: page.matchPath.replace(/\*|:[^/]+/gi, '.*'),
        dest: page.path
      })
    )
```

Now that `gatsby-plugin-now` is injected automatically (#3212), is it possible to incorporate these features into `gatsby-plugin-now` itself? Happy to open a PR if necessary.

**Comment by michaellopez** [comment]
We are interested in this too. We'll help in any way we can.

We also have troubles with localised 404 pages which we describe in detail in #3207 

Currently, we are also maintaining our own gatsby plugin based on `gatsby-plugin-now` to alleviate some of the problems described in #3207 but it doesn't get us all the way. Currently we are doing some testing without "Zero Config" to see if we can manage to make it work that way...

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.
