### ISSUE TITLE
support multi-level subdomains on *.now.sh

### ISSUE THREAD

**Issue by knksmith57** [vercel/vercel#3251]
I'd like to alias `foo.my-app` to my `my-app` deployment on the default `now.sh` domain.

When attempting to do this in the web console, the following error message is rendered:
> Multi-level .now.sh subdomain is not allowed.

It seems like there are many related issues but none (that I could find) that are asking for _this_ ability --apologies if I overlooked a duplicate.

In an ideal world, I'd love to be able to request the entire wildcard when available, ie: `*.my-app`, but it's understandable if that's not possible.

what do y'all think? is there history / context for why this isn't supported?

**Comment by styfle** [comment]
This is a security issue because `*.now.sh` is shared between everyone using the platform.

However, you can use wildcards with your own domain.

See this blog post: https://zeit.co/blog/wildcard-domains

**Comment by knksmith57** [comment]
could you please provide a bit more color as to what the security risk is?

if I already have control of `my-app.now.sh`, how does preventing me from using `foo.my-app.now.sh` impact the security posture of the rest of the platform?

one of the reasons I'm interested in this is because it _improves_ my ability to create more secure applications by imposing stricter controls/policies (eg: CSP, cookies, CORS).

**Comment by styfle** [comment]
I must have misunderstood.

There is already a feature for generating preview domains based on your project name and username as well as git branches. For example:

```
packagephobia.styfle.now.sh
packagephobia-git-master.styfle.now.sh
```

I will mark this as a feature request, thanks!

**Comment by knksmith57** [comment]
awesome, thank you! if there's anything I can do to assist, please let me know :smile:

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
