### ISSUE TITLE
Add "now CLI version" to now.json file

### ISSUE THREAD

**Issue by StefMa** [vercel/vercel#3254]
### Short
I like to have a json-key like "now-version" (or something like this) in the `now.json` to give me a hint/warning/(maybe even an error) if I use another now CLI version which was mentioned there.

The hint/warning/error could be also configurable in an ideal world:
```
"now" : {
  "version":  "16.2.0",
  "report": "[warning|error]"
}
```

### Long
Why do I want to have this feature?
Because I like [reproducible builds](https://reproducible-builds.org/docs/definition/). Currently its not possible to tell the project for which now-cli version it was "designed". And this make a reproducible builds impossible.

I came up with the idea because of my previous issue here: #3172 

My project (I'm working on my own) requires now CLI 16.2.0. It's forbidden to install a newer version because it has a bug which will make the whole project useless.
That means I have to setup my CI server to install this specific version as well.

This is fine as long as I work alone on the project. But imagine a whole team work on it. Then each member will run into the same issue (and maybe spend some time to figure out why it's not working).
If we have this feature I could create a PR and add the explanation why we require version X for this project in the description. -> Problem solved.

But I also think a little bit further.
Imagine I release version 1.0 of my project with the CLI version X.
Then the times go on and on and after several month my version X requires a hotfix.
What I do? Checkout the tag, fix the problem, create a new tag, deploy.
What could be go wrong? The CLI tool (which was updated in the meantime to version Y) has a bug or something else  has dramatically changed so that it's impossible to deploy that hotfix without installing version X again.
State today: Nobody will know (or remember) which CLI version was required to build project 1.0.0.
But with that json-key property a hint (or a warning) will pop-up (while trying to deploy) that the CLI version doesn't match the version the project requires to build. -> Problem solved.

### Some more information
For Java projects (not related to **now** tbh) I use [Gradle](https://gradle.org/) as my build tool.
And Gradle is - lets say - injected into the project.
Therefore I do not have to care about the installed Gradle version on my machine. Because each build I do with the "[Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html)" will install the correct Gradle version on my local machine to build my project.
Each project can be reproduced with Gradle as a build tool because the projects know "with which Gradle version it can be build".

And this is something similar what I request here.

**Comment by styfle** [comment]
Thanks for the suggestion!

Today, you can install any version of Now CLI published to npm such as `npm i -g now@16.2.0` or `npm i -g now@16.1.4-canary.42` as seen on [npmjs.com](https://www.npmjs.com/package/now?activeTab=versions).

I think a new `version` property in `now.json` would only be applicable to automatic deployments from the [Git Integration](https://zeit.co/docs/v2/git-integration). I'll forward this feature request to the team to see how to best implement. We might need to use the [now-client](https://www.npmjs.com/package/now-client?activeTab=versions) version instead.

**Comment by leo** [comment]
Thank you for sharing this feedback!

We do see the need for this, which is why we're encouraging people to install Now CLI "locally", so that it's available within `package.json`. That way, every one of your team members always gets the same result that you're getting and the platform always behaves the same way.

However, we have not yet looked into making this possible for repositories that do not use `package.json`, which is why this feedback helps a lot! I don't see us making Now CLI download other versions of itself for this, but perhaps it could be possible by sharing Now CLI via other package managers, which would then let you use their own dependency locking system...

We'll think about it - thanks!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
