### ISSUE TITLE
`now dev` is forced rebuilding when using `cache-control: no-cache`

### ISSUE THREAD

**Issue by vorillaz** [vercel/vercel#3316]
I have a really weird issue with `now dev` while testing my app with Postman.
I am exposing a single API endpoint using the `node builder` and although I can test my endpoint from the terminal with no issues or delays when I am using Postman `now dev` is forced rebuilding.

Apparently, when using `cache-control: no-cache` (which is a default header for Postman) hot reloading is forced for my builds.

**Comment by vorillaz** [comment]
Apparently that behavior is expected as far as I can see but I don't get it and it's not even documented.
https://github.com/zeit/now/blob/897d11a1e13ffd52383c6a346ff9cb356beb01be/packages/now-cli/src/util/dev/server.ts#L873

**Comment by thasophearak** [comment]
👋Hi @vorillaz 
Thank for open the issue.

The reason why this is expected behavior, because we want the experience that "it's just work". From perspective that primarily use browser to testing thing out, it's working as expected.

Regular browser refresh to get what we expected to changes, and hard refresh to burst caches and rebuild.

However we acknowledged that, from perspective of users that use advanced tool like Postman, Insomnia, curl, httpie etc may find it a bit inconvenient.

I hope that answer your question.

**Comment by rauchg** [comment]
We will take a look at this however to see if it’s worth changing the behavior.

Thanks for filing!

**Comment by vorillaz** [comment]
Hello thanks for the quick response , I think that using a common header cache might be confusing . A dedicated header may be more appropriate

**Comment by leo** [comment]
Yep. Absolutely agreed!

It should be used for busting any response caches, but definitely not the build of the serverless function.

We'll fix it! Thanks so much for reaching out!

**Comment by leo** [comment]
We will be internally tracking the progress [here](https://zeit.atlassian.net/jira/software/projects/PRODUCT/boards/6/backlog), but we'll immediately ping you once the update is released.
