### ISSUE TITLE
How to stop a build

### ISSUE THREAD

**Issue by dtomvan** [vercel/vercel#3348]
i cant stop a build even if its removed. i want to stop the build so I can make a new version of my app.

**Comment by styfle** [comment]
Hi @18gatenmaker 

The build cannot be stopped _manually_ at this time.

It will _automatically_ stop when it succeeds, fails, or the timeout of 45 minutes is reached.

We plan to add a stop/cancel feature in the future. Thanks for the feedback!

**Comment by miteyema** [comment]
Yes, this would be an awesome feature to add!

**Comment by CrutchTheClutch** [comment]
+1 This would be a great feature!

**Comment by dtomvan** [comment]
"Awesome feature" or just something you need to have a good SaaS

**Comment by DEMORALIZ3D** [comment]
It has been over a hour and I even deleted the project and mine now just says queued and when I run now LS the state is UNKNOWN since re-adding the project and removed the buggy lines of code.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.

**Comment by Albert-Gao** [comment]
Is there an issue that we can track the progress of this feature? 

A simple implementation(might be hard): to enable the user to set the time out value, so it could be 5min depends on the actual length of build

I think it is important for the platform as well, as the platform, you don't want a failing build to consume the resource for up to 45 minutes, right? 😜

Furthermore, better to put the default timeout on the UI, previously, I ended up deleting the account and re-create a new one.

**Comment by dtomvan** [comment]
Ok I will get to it but for me it isn't really important.

Op vr 27 dec. 2019 16:20 schreef Leo Lamprecht <notifications@github.com>:

**Comment by aqzhyi** [comment]
ran into this issue, I am looking forward to this feature!

**Comment by lucasinocente** [comment]
+1 for this feature

**Comment by caleblawrence** [comment]
My build is stuck running even though there is clearly an error in the log. It's been going for 30 minutes. Why is there not a way to cancel?

**Comment by IanShaffer** [comment]
"This command requires Expo CLI." Build is now just hanging for I expect 45 minutes. I tried again and build says "queued". I built to a new project and now that build is queued as well. Now I have to wait for 135 minutes?

**Comment by Ryzzuh** [comment]
+1

**Comment by stanlee321** [comment]
+1

**Comment by cristigoia** [comment]
+1

**Comment by styfle** [comment]
This feature is available as an experiment 🧪

You can enable the flag for "Cancel Deployment Button" by visiting https://zeit.co/_flags

**Comment by dtomvan** [comment]
Yaay

Op wo 18 mrt. 2020 16:37 schreef Steven <notifications@github.com>:

**Comment by styfle** [comment]
This feature is stable!

Read more: https://zeit.co/blog/canceling-ongoing-deployments
