### ISSUE TITLE
[now dev] Functions request body is always base64 encoded

### ISSUE THREAD

**Issue by remorses** [vercel/vercel#3355]
This has been reproduced using the `now-python` runtime but it happens with all function runtimes,
The problem is here, the function request is always encoded as 64
https://github.com/zeit/now/blob/49cba94178dd26ef13cb16d6e656e53d51b8b70b/packages/now-cli/src/util/dev/server.ts#L1335
This really adds a lot of overhead, i hope the production server doesn't do this.

The base64 encoding was probably done to avoid problems with binary data, but this can be solved encoding to base64 only when the `content-type` header is binary like

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.
