### ISSUE TITLE
Using Zeit NOW with GitLab CI

### ISSUE THREAD

**Issue by ajhalili2006** [vercel/vercel#3395]
If I am deploying my code to Zeit Now using GitLab CI, do I need to add my token into one of my GitLab's project's Variables under CI/CD settings?

**Comment by ajhalili2006** [comment]
Follow-up question: Can I add my GitLab groups or did I need to use my service account (@RecapTimeBot) instead to deploy from GitLab (because of API access permissions)?

**Comment by styfle** [comment]
Hi @AndreiJirohHaliliDev2006 

You should connect your ZEIT Account to your GitLab account and then you can import projects that you wish to deploy. Once its linked, any push to that project will create a ZEIT deployment.

Take a look at this page to get started: https://zeit.co/gitlab

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.
