### ISSUE TITLE
Are aliases being (slowly) phased out in favor of Production Domains?

### ISSUE THREAD

**Issue by unitof** [vercel/vercel#3433]
I just re-deployed an old v2 project with a single alias specified in now.json and got the log:

```
> NOTE: Production domains can be configured at https://zeit.co/unitof/big-banger/domains. No need to use the `alias` property.
```

([Big Banger](bigbanger.jacobford.com) is a fun little universe simulator I did in CSS as a student project.)

I also noticed a new note in the now.json alias [specification](https://zeit.co/docs/configuration/?query=alias#project/alias):

> NOTE: Aliases from a now.json file will be ignored when there are domains that have been configured for the project through the dashboard.

…leading me to believe that the preferred workflow is to set a Production Domain for each project, and move away from Aliases.

That's all fine, but I really would miss being able to specify/manage my Project's domains from my CLI, instead needing to use the dashboard every time. I *really* liked that my `now.json` represented a 1:1 mapping of exactly the final deployment, including the domain it lived at (assuming that domain was registered to the account I was deploying it).

 Is there a plan to support managing Production Domains from `now-cli` and/or `now.json`?

Note: I asked a version of this issue [on Spectrum](https://spectrum.chat/zeit/now/confustion-between-production-domains-aliases~fd8fc8c3-f69f-47d6-aafe-d75590e62b3f) but it didn't get any traction, so re-asking here.

**Comment by styfle** [comment]
Hi @unitof 

Indeed the `alias` property is ignored when there are domains configured at the Project level. The problem with `alias` is that you could have multiple but its not clear which one is considered production. It also doesn't work well for open source projects when someone forks or clones a repo with an `alias` because they don't own that domain. 

Thanks for the feedback, I'll forward it to the rest of the team.

Also see changes being worked on in PR #3325.

**Comment by unitof** [comment]
Thanks @styfle! Agree it probably makes sense for domains to be moved out of source, since in theory a web project (especially open source) should be domain-agnostic.

But some way to attach or specify one via something like `now domains attach` or `now --prod --domain="example.com"` would be _wonderful_.

And personally I strive to get my projects to the point where they can be updated/deployed with a single command immediately after cloning (that command often being `now --prod`), so _some_ way to specify a domain in `now.json`, or maybe a Now ENV variable type-thing(?) would be great.

#3325 looks really good—I'll ask @AndyBitz some questions about it there. And of course see if I can help!

Always be'sing and do'sing (never cheesing or choosing),
@unitof

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.
