### ISSUE TITLE
Yarn install executed multiple times during build

### ISSUE THREAD

**Issue by pvdlg** [vercel/vercel#3454]
Might be related #3432, however in my case I don't use multiple builders nor do I have a monorepo.

Here is my `now.json`:
```json
{
  "name": "project-name",
  "version": 2,
  "functions": {
    "api/list.js": {
      "memory": 256
    }
  },
  "routes": [
    {"src": "/list", "methods": ["GET"], "dest": "/api/list.js"}
  ]
}
```

And here is the build logs:
```
Downloading 10 deployment files...
Installing build runtime...
Build runtime installed: 557.283ms
Looking up build cache...
Build cache found [42.50 MB, 18237 files]
Build cache unpacked: 1745.040ms
Installing dependencies...
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @babel/register@7.7.7" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 12.58s.
Build completed. Populating build cache...
Build cache uploaded [42.50 MB]: 725.583ms
done
Installing build runtime...
Build runtime installed: 534.338ms
Looking up build cache...
Build cache found [42.50 MB, 18227 files]
Build cache unpacked: 1685.265ms
Installing dependencies...
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @babel/register@7.7.7" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 5.00s.
Running "yarn run build"
yarn run v1.17.3
$ copy api/** public/api
[32m✔[39m public/api/api/list.js
Done in 0.11s.
Build completed. Populating build cache...
Build cache uploaded [42.50 MB]: 703.135ms
done
```

As you can see the dependencies are installed twice (we see twice `[1/4] Resolving packages`, `[2/4] Fetching packages`, etc...).

If I add more serverless functions, the whole dependencies install happens one more time for each additional function. So for each build we get N + 1 `yarn install` execution where N is the number of functions (i.e. 2 functions => 3 `yarn install`, 3 functions => 4 `yarn install`, etc...) 

Those additional `yarn install` do not take that much time, however the total build time is linked to the price paid for Now (10 hours per month on the Pro plan). So all this "wasted" time doing unnecessary `yarn install` during the build end up eating up the allocated time of the plan and might forces users to upgrade plan...

**Comment by styfle** [comment]
Hi @pvdlg 

It sounds like you have multiple files in the `/api` directory.

This is similar to #3432 because a separate build is executed for each serverless function.

This was necessary for monorepos which have multiple package.json files.

We have some changes on the radar to improve build times when there is a single package.json file.

Thanks!

**Comment by pvdlg** [comment]
I tested with both 1 file in `/api` and multiples. With one file `yarn install` is still ran twice. With multiples it's ran <number of files> + 1.

Do you have an issue I can track with the progress of the build time improvement for single `package.json` project? If yes I can close this one.

**Comment by styfle** [comment]
The root package.json will also be install in addition to the api directory.

The "ideal" setup today is to have a root `/package.json` with a `build` script that generates html, usually with a static site generator.

Then you can optionally add functions in the `/api` directory and use the `/api/package.json` file to defined a different set of dependencies for the backend.

I think #3432 is a good place to track this feature request.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.
