### ISSUE TITLE
Build environment variable undefined in the API serverless function

### ISSUE THREAD

**Issue by fromi** [vercel/vercel#3455]
I am creating a project based on the latest version of Now and Next.js
I am integrating Pusher. The pusher key is a public information, and I need it both on the client side and on the server side (inside '/api'). However, I need to use different keys for local and production environments, and I prefer not to commit the keys in my code.
Therefore, I used a build environment key, and put the key in '.env.build' file for local usage.

I managed to get the key in my Next.js application on the client side, however, the key was undefined on the API side. I think it's a bug.

Workaround: duplicate the key from '.env.build' file into '.env' file.

**Comment by styfle** [comment]
Hi @fromi 

The build environment variables are separate from the runtime environment variables to avoid leaking build secrets that don't need to be exposed to the runtime.

If you need the env var in both build and runtime, you'll need to define it twice.

**Comment by fromi** [comment]
Hi, that makes sense.
It took me a while to figure out how to create public configuration available both in the frontend and in the backend: add to '.env.build', configure 'now.json', configure 'next.config.env' to access it in the frontend, and then also add it to '.env' to have it in the backend API.

Maybe a specific feature for public configuration would be a simpler solution (something like '.env.public' available at build time & run time, both on client and server side).
Or, at least, some documentation with all the steps for public configuration to save some time :)

Thanks for the great work! You can close this feature request if you want 👍

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.
