### ISSUE TITLE
Sporadically display source code in an html page instead of executing the function

### ISSUE THREAD

**Issue by pvdlg** [vercel/vercel#3473]
Instead of executing the function, Now return an html page with the source code of the lambda function.
Here is an example: https://api-dev-abc42n9d8.now.sh/list

This issue is not systematic. Using the exact same code and config some deployment works as expected some other present this issue. In order to test that, I am doing a deployment, delete the whole project from the UI and redo the deployment again without changing anything. Some deployments present the issue, some other are fine.

Here is my `now.json` file:
```
{
  "name": "api-dev",
  "regions": ["iad1"],
  "version": 2,
  "public": false,
  "functions": {
    "api/list.js": {
      "memory": 128
    },
    "api/publish.js": {
      "memory": 128
    }
  },
  "routes": [
    {"src": "/list", "methods": ["GET"], "dest": "/api/list.js"},
    {"src": "/publish", "methods": ["POST"], "dest": "/api/publish.js"}
  ],
  "env": {
     // redacted
  }
}
```

Let me know if you need more informations.

**Comment by styfle** [comment]
It looks like your `package.json` file has a build script that copies the api directory into the public directory.

```json
{
  "scripts": {
    "build": "copy 'api/**' public/api",
  }
}
```

Since `public` is the default Output Directory, you're serving `list.js` as a static file.

You can configure your Output Directory using Project Settings if this is not correct.

https://zeit.co/blog/advanced-project-settings
