### ISSUE TITLE
Increase Environment Variables Space

### ISSUE THREAD

**Issue by MattGould1** [vercel/vercel#3474]
Hello,

I've run into a problem recently with some of our Zeit builds. A little background. We are base64 encoding our `google-services.json` and also a `jwt` private key. This allows us to add the secrets to Zeit. These two environment variables together take up 3.8kb of the available 4kb environment variables limit. I've added a little `now.json` demo with the `env` section.

```
{
  "name": "example",
  "version": 2,
  "env": {
    "JWT_PRIVATE_KEY": "@jwt_private_key",
    "GOOGLE_SERVICES": "@google_services"
  },
  "builds": [
    { "src": "./src-to-deploy/**/*.route.ts", "use": "@now/node" }
  ],
  "routes": [
    { "src": "/", "dest": "/src-to-deploy/lib/index.route.ts" },
    { "src": "/(.+)", "dest": "/src-to-deploy/lib/$1.route.ts" }
  ],
  "regions": ["all"]
}
```

I have two questions:

1) Is there a better way to store complex secrets with Zeit?
2) Is it feasible to increase the 4kb environment variable limit?

Thanks,
Matt

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
