### ISSUE TITLE
ZEIT Now directory listing - lack of trailing slash breaks documents

### ISSUE THREAD

**Issue by connorjclark** [vercel/vercel#3477]
There is a document at `/viewer/index.html`.

https://lighthouse-52bt5b3pt.now.sh/viewer (broken) vs https://lighthouse-52bt5b3pt.now.sh/viewer/ (works). Unfortunately, the [index page](https://lighthouse-52bt5b3pt.now.sh/) uses the former URL.

This breaks because the document uses relative URLs for its resources.
![image](https://user-images.githubusercontent.com/4071474/71537646-d5e53400-28d3-11ea-9dff-537e9bdd7a5e.png)

A workaround for us would be to generate our own index page. A reasonable solution for Zeit might be to make the `viewer` folder open up into a new directory listing (only containing `index.html`), or to open directly to `viewer/index.html`

See: https://github.com/GoogleChrome/lighthouse/pull/10151

**Comment by styfle** [comment]
Thanks, this seems to be a bug with the [directory listing](https://zeit.co/docs/directory-listing) feature. It should probably differentiate between a file and directory so that it could add a trailing slash to the directory.

As a workaround, you could configure `now.json` by setting [`trailingSlash`](https://zeit.co/docs/configuration#project/trailingslash) to `true` which will always redirect every request to a trailing slash.

**Comment by connorjclark** [comment]
Thanks for the workaround!

**Comment by styfle** [comment]
Closing as won't fix since we have directory listing disable for new projects https://vercel.com/changelog/the-directory-listing-feature-will-be-disabled-for-older-projects
