### ISSUE TITLE
Can't unlink from an org I no longer have access to, so all Github repos I create have build failure

### ISSUE THREAD

**Issue by corysimmons** [vercel/vercel#3480]
1. Join org
2. Create Now "Git Integration" with it
3. Leave org
4. Can never get rid of the "Git Integration" in Now. If I click the "To disconnect, go to the app settings on GitHub." link to disconnect it, it 404's. Just have to suffer with seeing red `x` to signify build failure next to literally every repo I ever make unless I remove Now integration completely.

![image](https://user-images.githubusercontent.com/224636/71527995-c3ef9b00-28ab-11ea-8971-14c5ff85268d.png)

Going through and removing every association to Zeit and my Github now.

**Comment by styfle** [comment]
Hi @corysimmons 

Since ZEIT Now is installed as a GitHub App, you need to have the correct permissions in your GitHub Org to add or remove the integration.

It looks like your screenshot is not an Org but a personal GitHub account so perhaps there is something else wrong.

Please contact [support](https://zeit.co/support) with your ZEIT username and GitHub username and we'll get it fixed, thanks!

**Comment by corysimmons** [comment]
Already got back in touch with the org owner and had them manually remove the Zeit integration so I'm back to normal. The bug still exists. Close if you want.

**Comment by styfle** [comment]
I'm glad you got it back to normal! Let me know if there are any other problems, thanks!
