### ISSUE TITLE
Custom 404 page - "cannot mix legacy routes with new keys"

### ISSUE THREAD

**Issue by iinfin** [vercel/vercel#3491]
Trying to set a custom 404 page as shown [here ](https://khrome.dev/blog/custom-404-pages-on-zeit-now-v2-platform) and [here](https://spectrum.chat/zeit/now/custom-404-page~1f921045-60d9-477b-b23c-1626c9fa1565), getting this:

> Deployment failed with the following error:
> ```
>     Cannot mix legacy routes with new keys:
> ```

I'm using Hugo static generator, and here's the 404 routing part in my `now.json`
```
"routes": [{
	"src": "/.*",
	"dest": "/$1"
}, {
	"handle": "filesystem"
}, {
	"src": "/.*",
	"status": 404,
	"dest": "/404"
}
```
I also tried: 
```
}, {
	"src": "/(.*)",
	...
```

I've looked around for other examples, maybe missing a difference between now v1/2?
Thanks in advance

**Comment by jasondibenedetto** [comment]
Having a similar issue, unsure how to redirect all 404 pages to the home page. Previously used the following solution...

```
"routes": [
  { "handle": "filesystem" },
  { "src": "/(.*)", "status": 404, "dest": "/index.html" }
]
```

Now that routes is deprecated unsure what the implementation should be.

**Comment by nickgrealy** [comment]
I had the same issue, dug into the code (it's very readable) - turns out this is symptomatic of another underlying issue (some config is not inter-compatible). Check here -> https://github.com/zeit/now/blob/9d0b0c6e410343eead5e43f650c942d4b301f84a/packages/now-routing-utils/src/index.ts#L187-L211

To fix, I removed `cleanUrls`.

**Comment by ivan-kleshnin** [comment]
> Now that routes is deprecated

Since when does "Deprecated" == "Suddenly stops working"?

I assume Zeit team will release breaking changes under `version: 3` in `now.json`.

I also see some bugs with 404 handling though... 

`"status": 404` doesn't seem to apply with `now dev`.

**Comment by cryptiklemur** [comment]
routes hasn't "suddenly stop[ped] working"

**Comment by ivan-kleshnin** [comment]
@aequasi just some examples of serious bugs related to routes: 1) https://github.com/ivan-kleshnin/zeit-routes 2) https://github.com/zeit/now/issues/3659 And there are many more (look at the Issue threads at Next / Now GH and Spectrum).

**Comment by styfle** [comment]
Hello,

The error message is intentional. We don't plan on mixing `routes` with the new properties (redirects, rewrites, headers, cleanUrls, and trailingSlash).

### Background

When `routes` was introduced with 2.0, it was the same mindset has "this can do anything" kind of like `builds`. It is powerful but it is not intuitive. Few people could truly grok `handle: filesystem` or `continue: true`. It was mostly copy paste.

### Why not version 3?

Both `builds` and `routes` are more like primitives that we can build on top of. So the newer properties, `functions` and `rewrites`/`redirects` respectively, build on top of these primitives to provide a more intuitive experience. Because they're additive, we don't need a new major.

### What's new?

No more `handle: filesystem` or `continue: true`. Those are baked in so that the filesystem always has priority. If you have a file `/public/user.css` then you can't override it, you can only rename the file. This matches the behavior introduced with [zero-config announcement](https://zeit.co/blog/zero-config) that the filesystem is the routing layer. Adding rewrites is adding additional routes if you wish.

Also, we added the `/:path/:segment` matching which analogous to Express' path segment matching. These matches will end up in the query string so you can have pretty API URLs that don't expose a query string.

### How do I define a custom 404 page?

This is not implemented yet, so you would need to continue using `routes` or use Next.js which supports a [Custom Error Page](https://nextjs.org/docs/advanced-features/custom-error-page) out of the box. We want to make sure that defining custom errors is also an intuitive experience, so we're still working out the details. Rest assured that `routes` isn't going to be deprecated until we have feature parity with newer properties.

**Comment by cryptiklemur** [comment]
> Also, we added the /:path/:segment matching which analogous to Express' path segment matching

🔥 

Is that live now?

**Comment by styfle** [comment]
@aequasi Yes. This is also coming to Next.js as seen in this RFC https://github.com/zeit/next.js/issues/9081

**Comment by dangarfield** [comment]
Hi, although this functionality is not expressly available (interrogate the status code of the response), simply add a few catch-all redirects at the end of your `redirect` list (1 or 2 may do, depending on the 'depth' of your folder structure). Eg, something like:
```
"rewrites": [{
    "source": "/my-app",
    "destination": "/app.html"
  }, {
    "source": "/another-page",
    "destination": "/page2.html"
  }, {
        ...
  }, {
    "source": "/:a",
    "destination": "/404.html"
  }, {
    "source": "/:a/:b",
    "destination": "/404.html"
  }]
```

This is at least a temporary workaround for those wanting to get a 404 experience whilst still using `rewrite/redirect` config.

**Comment by maiertech** [comment]
@styfle When will an alternative way to define a custom 404 be rolled out?

**Comment by SukkaW** [comment]
> We want to make sure that defining custom errors is also an intuitive experience, so we're still working out the details.

What about something like this?

```json
"errorPages": {
  "404": "/path/to/404.html",
  "403": "/path/to/403.html"
}
```

Which is simple and easy to use.

**Comment by nkuehn** [comment]
@styfle  how about adding a plain sentence on https://vercel.com/docs/configuration  telling that "routes" can't be mixed with the newer expressivity?  

I agree that it's not a breaking change, it's "just" undocumented behaviour.   

(and yes, it would be nice to explicitly configure error pages - would be in the spirit of the new more use-case specific flags)

**Comment by mcsdevv** [comment]
Closing as the original issue has been resolved. Also, the feedback provided was rather useful and has been addressed with this PR: https://github.com/zeit/docs/pull/1830

**Comment by yaroslav-ilin** [comment]
I wonder if it's intuitive enough to use `404.html` file (if there is any) from the deployment directory for custom 404's by default. I think I've seen this convention in some other static hostings, seems fine to me.

What's the consideration against that?

**Comment by styfle** [comment]
You can now emit a `404.html` file in your Output Directory. This supports most frameworks with zero configuration.

https://vercel.com/docs/configuration#routes/advanced/custom-404

We also update the error message when `vercel.json` contains both `routes` and the newer routing properties.

**Comment by SukkaW** [comment]
@styfle So, I just need to make sure `/404.html` is accessible, and all 404 will be served with that page, right?

**Comment by iinfin** [comment]
Thank you for this @styfle!
