### ISSUE TITLE
Strip protocol and path when adding domain

### ISSUE THREAD

**Issue by albinekb** [vercel/vercel#353]
Just a minor UX thing:

```sh
❯ now domains add http://example.com/
❯ Error! The supplied value "http://example.com/" is not a valid domain.
```

What do you think of supporting that, just stripping away the protocol and path?
Since when you copy/paste from chrome, it will add that http(s):// and the trailing slash.

Maybe even add an extra confirmation (if/when) the domain extracted so the user can confirm it's correct.

Just a minor thing that would make it a tiny bit more awesome 🎉 

If you think it's a good idea, I'll send a PR

**Comment by leo** [comment]
Let's just normalize it by default! 😊

**Comment by albinekb** [comment]
Awesome, fix incoming 🎉  @leo

**Comment by leo** [comment]
@albinekb Status? 😊 Would love to merge a PR.

**Comment by albinekb** [comment]
Oh sorry, totally forgot! Will look at this tonight 😁  @leo

**Comment by leo** [comment]
@albinekb Still interested in looking into this? 😊

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
