### ISSUE TITLE
Rewrite from root path doesn't work

### ISSUE THREAD

**Issue by stophecom** [vercel/vercel#3543]
**Description**
The rewrite configuration from the root path to a subfolder doesn't seem to work properly. The "rewrite" works using `now dev`, but once deployed it doesn't. 

The `now.json` looks like this:
```json
{
  "version": 2,
  "rewrites": [{ "source": "/", "destination": "/foo" }]
}
```

Am I doing something wrong? Or is this even supposed to work from the root path?

Reproduction repo: https://github.com/christopheschwyzer/next-rewrite-test
Deployed: https://next-rewrite-test.creadi.now.sh/

**Comment by styfle** [comment]
This is intended behavior.

The new `rewrites` only appends to the existing filesystem, it doesn't overwrite. Since Next.js emits an index file in your example repo, that index file will always be served because the filesystem is checked before `rewrites` are processed.

If you really need to rewrite `/` and keep an index file, you'll need to use [`routes`](https://zeit.co/docs/configuration#routes) instead.

A better solution is to rename `/pages/index.jsx` to something else. Or better yet, rename `pages/foo/index.jsx` to `pages/index.jsx` and then you don't need any configuration.

**Comment by stophecom** [comment]
@styfle thank you very much for the explanation. 

I'm closing this one.
