### ISSUE TITLE
Support for `now alias <domain.tld>`

### ISSUE THREAD

**Issue by leo** [vercel/vercel#361]
In cases where you can't have a configuration (like when running `now user/repo`), we still need a way for aliasing the latest deployment easily.

In turn, this need to work:

```bash
now && now alias domain.tld
```

And it should deploy + assign the alias "domain.tld" to that deployment.

**Comment by leo** [comment]
As @matheuss suggested it, this is how you can do it at the moment:

```bash
now alias `now` domain.tld
```

**Comment by jamo** [comment]
Except when you are not on a mac...  (for the previous comment using `pbcppy`)
The challenge with doing `now` is that you have absolutely no output from `now`

**Comment by hugomd** [comment]
@leo If you want to assign this to me, I can give it a go tonight 👍 

Would support for performing `now alias domain.tld` on it's own be required? E.g. instead of `now && now alias domain.tld`, using `now alias domain.tld` — where it would have to perform a look up of the latest deployment?

**Comment by slorber** [comment]
Hi,

This ability to alias latest deployment is something I'd really like.

Consider that I have 2 frontends for productions: `prod-all` and `prod-next`. The way we stage is not by using aliases: we deploy first for the team, and if it works fine for us we deploy for all.
Sometimes, we are confident enough to deploy for both at the same time. So basically we make a deployment and alias it to 2 domains in a single command.

The `--alias` option did the job for a while but now it seems to act weird (it sometimes does not create the alias).


Here's what my npm scripts look like:


```
    "release-web-next": "npm run build && gulp uploadRelease && npm run deploy-prod-next && ./chatMessage 'Web release deployed (team only)'",
    "release-web-all": "npm run build && gulp uploadRelease && npm run deploy-prod-next && npm run deploy-prod-all && ./chatMessage 'Web release deployed (everyone)'",

    "deploy-prod-next": "./node_modules/.bin/now build --config zeit.json --alias frontend-prod-next.stample.co",
    "deploy-prod-all": "./node_modules/.bin/now build --config zeit.json --alias frontend-prod.stample.co",
```

What I really need is to be able to create a deployment, and alias it to 2 subdomains (or more) dynamically (not static in now.json, because there's not only production), from a single command.


From the above scripts, sometime I run it and it does not create alias. For example here's an output I get where the alias did not get created:

![image](https://cloud.githubusercontent.com/assets/749374/24205228/14a7f180-0f1b-11e7-8a89-864012d8d66c.png)

**Comment by slorber** [comment]
Not really related, but also when doing multiple attempts to deploy with --alias, sometimes it does not keep the same deployment url and do a new deployment while the files (static build) are exactly the same. Here's a [Gist with logs](https://gist.github.com/slorber/7f59bdff579aa89c7f3700a4c96a071a) where running the same command `./node_modules/.bin/now build --config zeit.json --alias frontend-prod.stample.co` on a static folder (with unchanged content) 4 times does seem to produce, not 4, but 2 deployments (switching randomly from one to the other), and where aliasing does not work in the end.


(Note I'm not really looking for bugfixes, because ability to easily alias latest deployment will indeed solve my problems in a simpler way)

**Comment by hawkins** [comment]
What about piping into `now alias`?

For instance, you can already see running `now | less` will pipe the new deployment URL. What if we allowed `now alias domain.tld` to read stdin for a deployment url to alias if one is not provided?

Thus, users could alias new or latest deployments with `now | now alias domain.tld`

**Comment by southpolesteve** [comment]
I've opened a PR that I believe closes this issue: https://github.com/zeit/now-cli/pull/467

**Comment by leo** [comment]
This is [now possible](https://github.com/zeit/now-cli/releases/tag/5.1.0)! 🎉

**Comment by roopemerikukka** [comment]
Hmm is this still working? If I use `now alias domain.tld` I just get the help output of the `now alias` command. Or should I use the pipe to make this work?

**Comment by backflip** [comment]
Same issue as @roopemerikukka, stopped working for me, too. Not sure about the version where it changed.

**Comment by backflip** [comment]
Would we have to change https://github.com/zeit/now-cli/blob/301166831afceff07f5bb1f2f164651d0fda59b0/bin/now-deploy.js#L857 to `String(argv._[0])`?

**Comment by leo** [comment]
As far as I know, we removed this because it made our system very unclear (we've had a long internal discussion about this, can't fully recall its content).

Please use the `alias` configuration [option](https://zeit.co/docs/features/configuration#`alias`-(string|array)) or run `now alias <deployment> <domain>`.
