### ISSUE TITLE
[Feature Request]: Git LFS

### ISSUE THREAD

**Issue by drewwyatt** [vercel/vercel#3716]
is this already a thing? If it is, I just may not how to enable it, but all of the files I am storing in LFS are not being checked out in my deployments.

🙏 🙏 🙏

**Comment by johnchristopherjones** [comment]
Someone mentioned [proxying with serverless functions](https://spectrum.chat/zeit/now/git-lfs-large-file-storage~7e6b7a3a-53a5-41d8-bd25-32b36d288496), but I haven't yet worked the details of that out.

**Comment by goodhoko** [comment]
This is currently the only thing that keeps from migrating to Vercel. Is this feature is on the roadmap? If not, is there any workaround that would make the LFS files available during the build process? Since my app does an image processing during the build, proxying via serverless functions does not seem as a feasible solution.

**Comment by pklepacki** [comment]
There is already a one closed issue for this. For refference: https://github.com/vercel/vercel/issues/2783

**Comment by srcnalt** [comment]
Just hit this issue right now, wondering when would this be available?

**Comment by masakudamatsu** [comment]
I hit this issue right now as well...

**Comment by Giorat** [comment]
I hit this issue too, will need to switch to other hosting providers unluckily if there won't be a public workaround or fix to this.
