### ISSUE TITLE
Trying to deploy a ReactXP app

### ISSUE THREAD

**Issue by GoldevLab** [vercel/vercel#3721]
hello im trying to deploy a cross platform using ReactXP(https://microsoft.github.io/reactxp/)  but i need to run a command to build and then a command for start node server.. how i can do that?..
my package.json is something like that:
  "main": "index.js",
    "scripts": {
        "start-web": "npm install && npm run gulp-web",
        "gulp-web": "cross-env NODE_ENV=development node node_modules/gulp/bin/gulp run --platform=web",
        "start-windows": "npm install && npm run gulp-windows",
        "gulp-windows": "cross-env NODE_ENV=development node node_modules/gulp/bin/gulp run --platform=windows",
        "start-ios": "npm install && npm run gulp-ios",
        "gulp-ios": "cross-env NODE_ENV=development node node_modules/gulp/bin/gulp run --platform=ios",
        "start-android": "npm install && npm run gulp-android",
        "gulp-android": "cross-env NODE_ENV=development node node_modules/gulp/bin/gulp run --platform=android",
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "generate": "gql-gen "
    },

So i need to deploy a web directory from the root directory and then execute  npm run start-web  & node nodeserver.js..

**Comment by styfle** [comment]
A few things I see:

1. You don't need to run `npm install`, our platform will do that automatically.
2.  `platform=windows` won't work because our platform does not run Windows, you probably want `platform=web`.
3. If the gulp command is running a server, then it will not work with ZEIT Now. You will need to use [Serverless Functions](https://zeit.co/docs/v2/serverless-functions/introduction).
