### ISSUE TITLE
Private github package installation

### ISSUE THREAD

**Issue by samuelcastro** [vercel/vercel#3728]
Hi, I haven't find a way to install a private github repo/package with ssh. I'm getting this build error on *now*: 

```
error Command failed.
--
02:06:53 PM | Exit code: 128
02:06:53 PM | Command: git
02:06:53 PM | Arguments: ls-remote --tags --heads ssh://git@github.com/samuelcastro/my-private-package.git
02:06:53 PM | Directory: /zeit/6903c4f2
02:06:53 PM | Output:
02:06:53 PM | Host key verification failed.
02:06:53 PM | fatal: Could not read from remote repository.
02:06:53 PM | Please make sure you have the correct access rights
02:06:53 PM | and the repository exists.
02:06:53 PM | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
02:07:10 PM | Error: Exited with 128
02:07:10 PM | at ChildProcess.<anonymous> (/zeit/8fa4fb30d2598703/.build-utils/.builder/node_modules/@now/next/dist/index.js:47050:24)
02:07:10 PM | at ChildProcess.emit (events.js:210:5)
02:07:10 PM | at ChildProcess.EventEmitter.emit (domain.js:475:20)
02:07:10 PM | at maybeClose (internal/child_process.js:1021:16)
02:07:10 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

Thanks.

**Comment by styfle** [comment]
### Update June 2020

Please see this guide: https://vercel.com/knowledge/using-private-dependencies-with-vercel

My answer below is a bit outdated.

-----

Hi @samuelcastro 

You can publish a private package to the [Github Package Registry](https://github.com/features/packages) and then configure npm or yarn to install your package.

This will usually involve modifying your `~/.npmrc` file so that your private scope is mapped to github and all others are mapped to npm (so you can mix and match).

```
@styfle:registry=https://npm.pkg.github.com
//registry.npmjs.org/:_authToken=NPMTOKENHERE
//npm.pkg.github.com/:_authToken=GHTOKENHERE
```

With the config above, can run `npm i @styfle/copee` to install [styfle/copee](https://github.com/styfle/copee/packages/12506) from github.com instead of npmjs.com.

To get this to work in the cloud, you'll need to add a secret.

```
now secrets add my-app-npmrc "$(cat ~/.npmrc)"
```

Then add a `now.json` to assign the `NPM_RC` environment variable as seen in the [docs](https://zeit.co/docs/runtimes#advanced-usage/advanced-node-js-usage/private-npm-modules-for-node-js).

```json
{
  "build": {
    "env": {
      "NPM_RC": "@my-app-npmrc"
    }
  }
}
```

**Comment by turaling** [comment]
Hi @styfle 
Could you also explain how to install private packages during local development? Currently, my app is successfully installing private deps in the cloud but `now dev` throws `Cannot find module '@username/package-name'` error. I have created a `.env.build` file with the contents below and I suspect that I might be doing a syntax error there. Btw, I'm using pnpm as the package manager.

```
NPM_RC=@username:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=GHTOKEN
```

**Comment by styfle** [comment]
Since `now dev` doesn't install packages, you'll need to run `npm install` or `yarn install` once locally to install packages. Then you can run `now dev`.

**Comment by turaling** [comment]
OK, I think I figured it out. 
I have already had the packages installed and could confirm that the node_modules directory contains my private packages, at least the symlinks to that packages. Then I wiped out the node_modules directory and ran `npm install` this time, instead of `pnpm install` as I used to. And it worked. So, the issue seems to be related to pnpm — pnpm in a monorepo setting, to be more precise. The project I'm working on was a standalone project and used to work fine with pnpm by itself. Now, it's a part of a monorepo installed also with pnpm and it's not behaving as expected anymore. It's time to switch to yarn I guess.

Thanks anyway.

**Comment by abarax** [comment]
Did anyone get this working with Bitbucket?

**Comment by lmatheus** [comment]
Hi @styfle,

I've tried the approach proposed on  https://vercel.com/knowledge/using-private-dependencies-with-vercel by using my `.npmrc`

```
@username:registry=https://npm.pkg.github.com
//registry.npmjs.org/:_authToken=NPMTOKEN
//npm.pkg.github.com/:_authToken=GHTOKEN
```
Of course, replacing @username, NPMTOKEN and GHTOKEN with the relevant data and then running `vc env add NPM_RC production < ~/.npmrc`.

After I force a rebuild, the private package registry still points to the npm registry as opposed to github's and I get a 404 on that installation.

Anything you can think I can be missing here?

Thanks a lot in advance

**Comment by agcty** [comment]
> Hi @styfle,
> 
> I've tried the approach proposed on https://vercel.com/knowledge/using-private-dependencies-with-vercel by using my `.npmrc`
> 
> ```
> @username:registry=https://npm.pkg.github.com
> //registry.npmjs.org/:_authToken=NPMTOKEN
> //npm.pkg.github.com/:_authToken=GHTOKEN
> ```
> 
> Of course, replacing @username, NPMTOKEN and GHTOKEN with the relevant data and then running `vc env add NPM_RC production < ~/.npmrc`.
> 
> After I force a rebuild, the private package registry still points to the npm registry as opposed to github's and I get a 404 on that installation.
> 
> Anything you can think I can be missing here?
> 
> Thanks a lot in advance

Did you manage to get it working? I'm getting the same error

**Comment by styfle** [comment]
Did you add to preview too? `vercel env add NPM_RC preview < ~/.npmrc`

**Comment by tettoffensive** [comment]
@styfle @agcty Same for me. I also tried: "add the key NPM_TOKEN with the your private token for the npm registry as the value." from the approach from https://vercel.com/knowledge/using-private-dependencies-with-vercel. And still get the error. I've added to preview as well

**Comment by styfle** [comment]
Are you able to run `npm install` locally without error? What about `npm i -g vercel` without error?

**Comment by tettoffensive** [comment]
Thanks, @styfle. I was just not paying attention and copied the line `vc env add NPM_RC preview < ~/.npmrc` but that was the wrong `.npmrc` file for me. I needed  `vc env add NPM_RC preview < .npmrc` and it worked.

**Comment by goz** [comment]
Any pointer for golang private package?

**Comment by styfle** [comment]
@goz For golang, you can use the `GIT_CREDENTIALS` environment variable key with value `https://username:token@github.com`

https://vercel.com/docs/runtimes#advanced-usage/advanced-go-usage/private-packages-for-go

**Comment by cookcc** [comment]
even though vercel offical document support to use the GIT_CREDENTIALS environment variable key with value https://username:token@github.com，but it failed when i tried.Ffinally the correct way is use the NPM_RC environment variable key with value @OWNER:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=yougithubaccesstoken

**Comment by tirrth** [comment]
### For Yarn Folks:

What I found from my observation is to remove yarn.lock file from the project, and adding the given snippet below to `.npmrc` or `NPM_RC env variable` works just fine. Nothing else suggested here worked for me though😕

```
<ORGANIZATION>:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken=<TOKEN>
```

**UPDATE:** Rather than removing the yarn.lock from repo itself, We can even override the default install command - `yarn install` to `rm -rf yarn.lock && yarn install` or `yarn install --no-lockfile` from Vercel settings, and it will do the work for us

**Comment by mgmgus** [comment]
> yarn install --no-lockfile

I wasn't able to make it work: 

As specified in: https://vercel.com/support/articles/using-private-dependencies-with-vercel

The `NPM_RC` env in vercel:

```
//npm.pkg.github.com/:_authToken=${NPM_TOKEN}
@my-org:registry=https://npm.pkg.github.com
```

But I've got:

> error An unexpected error occurred: "https://npm.pkg.github.com/@org/package: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.".


Event hough the `NPM_TOKEN` env is also set to the 3 environments.

**Comment by tirrth** [comment]
> > yarn install --no-lockfile
> 
> I wasn't able to make it work:
> 
> As specified in: https://vercel.com/support/articles/using-private-dependencies-with-vercel
> 
> The `NPM_RC` env in vercel:
> 
> ```
> //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
> @my-org:registry=https://npm.pkg.github.com
> ```
> 
> But I've got:
> 
> > error An unexpected error occurred: "https://npm.pkg.github.com/@org/package: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.".
> 
> Event hough the `NPM_TOKEN` env is also set to the 3 environments.

I am not sure why it did not work-out for you! The only difference I could see here is the order of lines. Try changing the order of lines in .npmrc and keep the **_@my-org:registry_** on the first line and the _**authToken**_ line after that. Maybe that would be causing the issue...

**Comment by beaumontyun** [comment]
I experienced the same problem today but after ```npm i -g vercel``` and then deploy over the command line by simply ```vercel```, it worked. No idea where the problem was exactly but worth giving it a try if people encounter issue with deploying from private repository.

**Comment by th-m** [comment]
like @caglarturali I am experiencing the same issue with `pnpm` in a nx monorepo setting. Using `npm i` works great, but `pnpm` fails. 

If anyone knows how to get this to work with `pnpm` that would be great.

**Comment by airtonix** [comment]
> ### For Yarn Folks:
> What I found from my observation is to remove yarn.lock file from the project, and adding the given snippet below to `.npmrc` or `NPM_RC env variable` works just fine. Nothing else suggested here worked for me thoughconfused
> 
> ```
> <ORGANIZATION>:registry=https://npm.pkg.github.com/
> //npm.pkg.github.com/:_authToken=<TOKEN>
> ```
> 
> **UPDATE:** Rather than removing the yarn.lock from repo itself, We can even override the default install command - `yarn install` to `rm -rf yarn.lock && yarn install` or `yarn install --no-lockfile` from Vercel settings, and it will do the work for us

I know this a while ago, but i just want to highlight that any solution that involves removing your lockfile is a **huge** red flag. 

You'd have to be making an enormously good case for doing so and I'm 100% sure there are better ways to solve the problem.


I mean you have to understand that by removing your lockfile you essentially destroy any assurance that packages you installed up until now remain the same ones you install in future.

**Comment by boylec** [comment]
We are on yarn v1.x

NPM_RC doesn't appear to be actually doing anything when we run vercel build.

As a result we are forced to specify an explicit .npmrc file at our project root with secrets inside of it.

**Comment by hungdoansy** [comment]
Where should I put `vc env add NPM_RC preview < ~/.npmrc` to?

**Comment by akarmes** [comment]
Spend a day working on it, trying to setup Github NPM registry with yarn 1. In the end tried  `npm` and `pnpm` - worked like a charm. Then I've removed whole Vercel project, recreated - and it started working with `yarn`. My `NPM_RC` variable in Vercel looks like this:

```
@{GITHUB_ORGANIZATION}:registry=https://npm.pkg.github.com/
//npm.pkg.github.com/:_authToken={GITHUB_NPM_TOKEN}
always-auth=true
```
You'll need to replace {GITHUB_ORGANIZATION} and {GITHUB_NPM_TOKEN} with your values. 

My advice to you:
- Yarn 1 is old, it's time to retire it and switch to another package manager
- When nothing helps, double check if all symbols present in .npmrc
- As a last resort try recreating your Vercel project

**Comment by dylangolow** [comment]
For anyone coming here in 2024 or later, here is a more precise answer around using multiple tokens, one for org-level and another for a specific package when using vercel. I had to try a handful of variations to get this to work on a preview environment. I used this page in the docs for reference: https://vercel.com/guides/using-private-dependencies-with-vercel

Here is the .npmrc format which can be copied into an environment variables in vercel with your own values replaced as required. You may not require all sections, due to NPM_ORG_1 having many packages I wanted to determine the recipe to have one entry at the org level and another at the package level but both coming from npmjs as the registry.

```
registry=https://registry.npmjs.org

@{NPM_ORG_1}:registry=https://registry.npmjs.org
//registry.npmjs.org/:_authToken={NPM_ORG_1_TOKEN}

@{NPM_ORG_2}:registry=https://registry.npmjs.org/{NPM_ORG_2}/{PACKAGE_NAME}
//registry.npmjs.org/{NPM_ORG_2}/{PACKAGE_NAME}/:_authToken={NPM_ORG_2_TOKEN}
```

Some key things to notice here to get the build to work:
- The first listing is for the vercel build dependencies to find the canonical registry
- Ensure there is a forward slash "/" before the `:_authToken...` in any org or package specific entry

**Comment by ashbuilds** [comment]
Having the same issue while trying to use github private repo, nothing works when using `pnpm install` in Vercel, spent my whole night and day.
Would be great if this configuration exist in the Vercel dashboard and we don't have to push these sensitive keys to our repository.

**Comment by en3sis** [comment]
What worked for me after many attempts, was setting the `NPM_RC` with the following value.
```ts
@org_name:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=TOKEN_HERE/NOT_ENV
registry=https://registry.npmjs.org/
always-auth=true
```

I think the important part is the `always-auth=true` and the default registry since without it did not work.

What I did notice is that the build time is way longer now, just as sidenote.
