### ISSUE TITLE
Support for deploying with React Concurrent Mode

### ISSUE THREAD

**Issue by samcx** [vercel/vercel#3754]
I'm trying to get a personal React project deployed using the `react@experimental` version, which supports React's upcoming Concurrent Mode.

I was using this hack explained in this Spectrum [post](https://spectrum.chat/zeit/now/react-concurrent-on-now~07078587-25ef-4399-a04c-83e2e8132458).

```javascript
process.env.NODE_ENV === 'development'
  ? ReactDOM.createRoot(document.getElementById('root')).render(<Root />)
  : ReactDOM.unstable_createRoot(document.getElementById('root')).render(
      <Root />,
    );
```

Current React docs for Concurrent Mode only uses `ReactDOM.createRoot(...)`.

After upgrading to `now@17.0.0`, this hack no longer works. Here is the error:

![Screen Shot 2020-02-05 at 4 32 26 PM](https://user-images.githubusercontent.com/28912696/73895654-26d23b80-4835-11ea-9922-72fe79db731d.png)

 Tried version `now@16.7.3`, to no success. Only going back to `now@16.6.3` has let this hack work. Local production builds (CRA) using `yarn build` do not give me this error.

Thanks!

**Comment by styfle** [comment]
Are you seeing this behavior with `now dev` or production deployments (or both?)

**Comment by samcx** [comment]
I have not tried with `now dev` (I am using CRA’s `yarn start`). I am seeing this behavior on production deployments.

**Comment by styfle** [comment]
Are you assigning `NODE_ENV` in `now.json`?

Try assigning the desired value for for both [build time](https://zeit.co/docs/v2/build-step#using-environment-variables-and-secrets) and [runtime](https://zeit.co/docs/v2/serverless-functions/env-and-secrets).

```json
{
  "env": {
    "NODE_ENV": "development"
  },
  "build": {
    "env": {
      "NODE_ENV": "development"
    }
  }
}
```

Or perhaps you want `production` instead of `development`?

**Comment by styfle** [comment]
The problem is that the React team is publishing `experimental` as a randomly generated version instead of incrementing the version to follow [semantic versioning](https://semver.org/).

![image](https://user-images.githubusercontent.com/229881/74686773-82d78100-51a0-11ea-9df1-2a2dcca88ce5.png)


This means that you can't use `^` when defining the react version in `package.json` or else `npm install` may use an _older_ version, something that would never happen when following semver.

The solution is to pin to the exact version in `package.json`.

### Before

```json
{
  "dependencies": {
    "react": "^0.0.0-experimental-241c4467e",
    "react-dom": "^0.0.0-experimental-241c4467e"
  }
}
```

### After

```json
{
  "dependencies": {
    "react": "0.0.0-experimental-241c4467e",
    "react-dom": "0.0.0-experimental-241c4467e"
  }
}
```

Notice the lack of `^`. You should also delete `yarn.lock` or `package-lock.json` and regenerate if you have one.
