### ISSUE TITLE
Creation of new project linked to GitLab (GUI)

### ISSUE THREAD

**Issue by bsalim97** [vercel/vercel#3779]
Hello while trying to link my GitLab to my zeit project I cannot press the button continue after importing my project even tho my project is already to the root of the project and it is not empty.

I can push the project through my prompt directly but i don't understand why not through the GUI.

![image](https://user-images.githubusercontent.com/48190855/74159715-81480f00-4c1c-11ea-856f-ef0a45e37883.png)

**Comment by colinhemphill** [comment]
I'm seeing the same! Had a brief conversation about it on Spectrum, but no updates.

https://spectrum.chat/zeit/now/gitlab-integration-cant-import-my-project~99963859-fcbd-41f7-b262-029f7ff9d9fd

If I try to deploy from the CLI, I get this error:

<img width="570" alt="Screen Shot 2020-02-10 at 9 39 53 AM" src="https://user-images.githubusercontent.com/1854690/74164377-50021b80-4be9-11ea-93a5-9ce29be18fe2.png">

Never seen this before on this same project, so there's a chance they're related based on the error messages both indicating a problem with the Git repo.

My website is still down after 2 days because of this 😞

**Comment by colinhemphill** [comment]
Migrated the project to GitHub and everything works. The deploy builds fine and no issues with the git repo. Definitely seems like a related issue where GitLab projects are not pulling in the Git repo correctly.

**Comment by bsalim97** [comment]
problem solved : 
Apperently renaming the GitLab project made everything work properly

**Comment by colinhemphill** [comment]
It does look like the issue was resolved, but it is definitely _not_ from changing a project name.
