### ISSUE TITLE
Alternatives to `name` property in config

### ISSUE THREAD

**Issue by ohager** [vercel/vercel#3789]
Hi,

I have a project for which I need to make deployments with different configurations to different urls
Example:

`now.a.json --> https://a.now.sh`
`now.b.json -->  https://b.now.sh`
`now.c.json --> https://c.now.sh`

```
{
  "version": 2,
  "name": "a", // or "b", or "c"
  "env": {
     // my config
    ...
  },
}

```

Before V17 I simply used the `name` property in the configuration, which gives me complete control over the generated urls.

I tried to figure out how to do this with the latest version, but no luck.

Any suggestions?

**Comment by iPwnPancakes** [comment]
+1

I also used the --name property when using Travis CI as my CI/CD solution. 

After the tests had all run successfully, it would deploy to certain projects depending on if a commit was on the master branch or not. Now I cant name the project that they deploy on

**Comment by sdornan** [comment]
This is a huge problem for me too.

**Comment by zlwaterfield** [comment]
I also need `--name` since we are deploying use CI/CD and `.now` won't exist so it won't select the correct project to deploy too.

**Comment by chrnorm** [comment]
FYI reverting to now@16.7.3 has temporarily solved this for me in my CI pipelines.

eg for GitHub actions:
```
      - name: Install Now CLI
        run: sudo npm i -g now@16.7.3
```

**Comment by ohager** [comment]
@chrnorm Of course, I did a downgrade... as you said: _temporarily_

**Comment by michaellopez** [comment]
You might be able to use https://github.com/zeit/now/issues/3767#issuecomment-588060864

**Comment by borekb** [comment]
Could someone from ZEIT explain the motivation for the change, please? The way I see it:

- Last summer, I was able to configure Now deployments easily via `now.json`.
- Then, "zero config" became a thing – most `now.json` files were removed from now-examples (https://github.com/zeit/now-examples/pull/423) etc.
- (**My speculation, or what it seems like:**) Then, the team realized that there needs to be _some_ config, and UI screens / project linking was added.

However, I don't quite understand how gitignored `.now/project.json` that contains only a subset of what used to be configured in `now.json` is better. Will all the other (sometimes quite complex) configs move to a UI as well? Will everybody on the team need to set it up manually since it's git-ignored? What was wrong with `now.json`?

CLI v17 seems to have caused quite a few issues:

- This one.
- "Broken" (more complicated) `now dev`: https://github.com/zeit/now/issues/3767
- Rewrites and redirects are ignored in dev: https://github.com/zeit/now/issues/3777
- Env vars are ignored in dev: https://github.com/zeit/now/issues/3758

Common workaround is to downgrade to CLI v16 which is what we're doing with our team.

For me, the disruptive nature of v17 came "out of the blue" so I'm surprised. Maybe I missed some earlier communication about this but if not, I'd really like to see the motivations behind this explained – I'm sure they are well-intentioned.

**Comment by willemliu** [comment]
> Hi,
> 
> I have a project for which I need to make deployments with different configurations to different urls
> Example:
> 
> `now.a.json --> https://a.now.sh`
> `now.b.json --> https://b.now.sh`
> `now.c.json --> https://c.now.sh`
> 
> ```
> {
>   "version": 2,
>   "name": "a", // or "b", or "c"
>   "env": {
>      // my config
>     ...
>   },
> }
> ```
> 
> Before V17 I simply used the `name` property in the configuration, which gives me complete control over the generated urls.
> 
> I tried to figure out how to do this with the latest version, but no luck.
> 
> Any suggestions?

I've created a workaround using NOW_PROJECT_ID and NOW_ORG_ID environment parameters. So I can use a single command line and multiple now.json files to achieve the same effect.
For more details you can follow this Spectrum.chat thread: https://spectrum.chat/zeit/now/solved-project-linking-and-ci-cd-pipelines~5e6eb62a-9d56-47ac-9e32-0d973a523787

Ultimately my command-line command looks as follows when running in a CI pipeline:
DEV:
```
npx cross-env NOW_ORG_ID=$NOW_ORG_ID NOW_PROJECT_ID=$NOW_PROJECT_ID_DEV now -d -f --prod -t $NOW_TOKEN
```
ACC:
```
npx cross-env NOW_ORG_ID=$NOW_ORG_ID NOW_PROJECT_ID=$NOW_PROJECT_ID_ACC now -d -f --prod -t $NOW_TOKEN
```
In both examples above I copy the `now.dev.json` and `now.acc.json` to `now.json` prior to running the command.

**Comment by marcofranssen** [comment]
For the time being I resolved by just using the *deprecated* name property in my now.json.

Then in my github action I use the following.

```bash
now --token=${{ secrets.my_token }} --confirm --debug
```

Please note. Without the `name` property the confirm will fail. It seems zeit now has completely forgotten about people with more advanced workflows who rely on the now cli.

**Comment by robertcoopercode** [comment]
As others have suggested above, it's possible to deploy to different ZEIT Now projects by specifying the `NOW_ORG_ID` and `NOW_PROJECT_ID` environment variables. For a detailed walkthrough on how to deploy to multiple environments/domains with Now CLI v17, you can read this post: https://www.robertcooper.me/deploy-app-to-multiple-environments-zeit-now

**Comment by styfle** [comment]
Multiple environments are available in [Now 18.0.0](https://github.com/zeit/now/releases/tag/now%4018.0.0) and on the dashboard today!

This should solve most use cases where you might have been using multiple `now.json` files. You can now delete those config files and take advantage of the [Git Integration](https://zeit.co/docs/v2/git-integrations).

**Comment by robertcoopercode** [comment]
> Multiple environments are available in [Now 18.0.0](https://github.com/zeit/now/releases/tag/now%4018.0.0) and on the dashboard today!
> 
> This should solve most use cases where you might have been using multiple `now.json` files. You can now delete those config files and take advantage of the [Git Integration](https://zeit.co/docs/v2/git-integrations).

Nice! I love the environment variable section in the dashboard page. It looks like we can now remove the environment variable mappings in our `now.json` files. However, if we want to deploy to different projects, I'm guessing we will still need to set the `NOW_ORG_ID` and `NOW_PROJECT_ID` environment variables when running the deployment commands with now.

**Comment by jdinhify** [comment]
> Multiple environments are available in [Now 18.0.0](https://github.com/zeit/now/releases/tag/now%4018.0.0) and on the dashboard today!
> 
> This should solve most use cases where you might have been using multiple `now.json` files. You can now delete those config files and take advantage of the [Git Integration](https://zeit.co/docs/v2/git-integrations).

Thanks for the update @styfle 
However, I don't think multiple environment variables will solve this issue, as it's addressing a different problem. To be able to pull environment variables, it looks like we'll have to be in a configured project already.

The problem we're having in this issue is that we won't be able to easily deploy/configure a project using the (deprecated) `name` property (we might still be able to do it now, but won't when it's removed).
I understand the intention of using `NOW_ORG_ID` & `NOW_PROJECT_ID` to identify a project and I think it's a good move. Not having a proper/recommended way of getting them and using them to deploy in a CI/CD pipeline is frustrating though.
Yes, the work around mentioned above works, but it's still only a work around until there's official recommendation.

Also, using Git Integration should be a choice, not forced on users. I personally come to use `now` a few years ago because it's a great cli tool, and the configurations are meant for cli, but now it seems to be moving to a different direction.

Please correct me if there's anything wrong.

**Comment by marcofranssen** [comment]
@jdinhify I'm also heavily in the need to be able to use the now cli in my github actions. Now 18.0.0 does not resolve this issue for me. Due to the `name` thingy.

**Comment by Ziltosh** [comment]
Same here, I am using Now/Vercel with now cli and need to create and deploy project with the name property.
