### ISSUE TITLE
Q: How to do a node + ts API

### ISSUE THREAD

**Issue by donifer** [vercel/vercel#3808]
Hi, I'm pretty new to `now` and I'm having a hard time getting started.

What I'm trying to do should be simple: a serverless node API using typescript. 

Bonus: Support reloding my server when using `now dev`.

But I honestly have no idea how to start, I can't find any example and the docs are pretty confusing if you are not using next.js

Tried adding `@now/node` but then what? Seems like I need to setup a build script, a start script define some routes, etc.

Extra question: does it make sense to run express on top of `@now/node` I know that is not needed but the ergonomics IMO seem a bit saner than having routes defined by directories and files named with `[brakets]`.

**Comment by michaellopez** [comment]
@donifer First of all, this type of question is more suited for [Stack Overflow](https://stackoverflow.com/questions/tagged/zeit-now) as this issue queue is for handling bugs in the Now platform.

But I'm all too familiar with your situation so I thought I'd offer some guidance despite the above.

The Now platform favours the Serverless architecture, meaning you can run express on Now but it won't be the best experience/performance. You don't need to buy into the zero config approach that uses the `[brackets]` syntax (among other things). If you prefer you could setup your own structure and leverage [routes](https://zeit.co/docs/configuration#project/routes) to map it out, kind of like in express. But you can also go with express in [a serverless environment](https://medium.com/@bmikkelsen22/designing-a-serverless-express-js-api-using-zeit-now-6e52aa962235) or [a serverfull-ish environment](https://zeit.co/docs/runtimes#advanced-usage/advanced-node-js-usage/legacy-serverful-behavior).

We used express previously but since embracing serverless fully Now 2.0 makes sense to us.

To get you started with a serverless approach to a TS API you should do the following:

1. Create a new folder, name it something short and descriptive like "my-ts-api".
2. Create a .ts file for each endpoint in your API (can be nested in folders and what not, you decide). For example I created these:
```ts
// deep/sub/folder/endpoint.ts
import { NowRequest, NowResponse } from '@now/node';

export default (request: NowRequest, response: NowResponse) => {
  response.status(200).json({
    deep: true,
  });
};
```
```ts
// users/create.ts
import { NowRequest, NowResponse } from '@now/node';

async function createUser() {
  // logic goes here
  // fake it in this example
  return new Promise((resolve, reject) => {
    const user = { uid: 1 };
    setTimeout(() => {
      resolve(user);
    }, 2000);
  });
}

export default async (request: NowRequest, response: NowResponse) => {
  const user = await createUser();
  response.status(200).json(user);
};
```
```ts
// greet.ts
import { NowRequest, NowResponse } from '@now/node';

export default (request: NowRequest, response: NowResponse) => {
  const { name = 'World' } = request.query;
  response.status(200).send(`Hello ${name}!`);
};
```
3. Create a `now.json` and fill it with the following:
```json
{
  "version": 2,
  "builds": [{ "src": "**/*.ts", "use": "@now/node" }],
  "routes": [
    {
      "src": "^/my/ts/api/user$",
      "methods": ["POST"],
      "dest": "users/create.ts"
    },
    {
      "src": "^/my/ts/api/user$",
      "methods": [
        "GET",
        "HEAD",
        "PUT",
        "DELETE",
        "CONNECT",
        "OPTIONS",
        "TRACE",
        "PATCH"
      ],
      "status": 405
    },
    {
      "src": "^/users/create(\\.ts)?$",
      "status": 403,
      "dest": "does-not-exists"
    },
    {
      "src": "^/my/ts/api/(.*)$",
      "dest": "$1.ts"
    }
  ]
}
```
4. Adjust the above to match your desired structure

You can view and test a deploy of the above here https://my-ts-api.now.sh/

You can [inspect the source](https://my-ts-api.now.sh/_src) and [check the logs](https://my-ts-api.now.sh/_logs)

I'm showing off some of the Now platform features, like only allowing POST methods to create a user for example, and returning a proper 405 for any other method (unfortunately Now doesn't do that automatically) and also returning 403 if trying to run the lambda directly at its source instead of its exposed alias.

Of course, in a production environment, you would turn off directory listing, I'm leaving it on so you can more easily inspect the deploy. You can disable directory listing by adding a `index.html` in each folder or adding routing rules to match directories and denying access similar to what we are doing with `/users/create/` in the above example.

Note that `users/create.ts` uses async/await.

Note that `greet.ts` accepts a query parameter, `name` e.g. https://my-ts-api.now.sh/my/ts/api/greet?name=Michael

Note that the final route is a catch all for mapping out the end of the incoming path to a file in the same location. So a file in `my-ts-api/deep/sub/folder/endpoint.ts` will be accessible at https://<deployment url>/my/ts/api/deep/sub/folder/endpoint

[The docs for TS with Node.js lambdas](https://zeit.co/docs/runtimes#official-runtimes/node-js/using-typescript-with-the-node-js-runtime)

If you want more control you can view the [documentation for routes](https://zeit.co/docs/configuration#project/routes) and [the rest of the docs on Now](https://zeit.co/docs) for go even further.

These are some of the tips and tricks we've learnt while growing with Now over the years.

Hopefully that can get you started with Now. Let me know if you have any questions and I'll be glad to answer them when I get the time :)

UPDATE: Also a note on `now dev` it works great with the above approach.

**Comment by paulogdm** [comment]
Thanks @michaellopez

**Comment by donifer** [comment]
@michaellopez This is fantastic! Thank you so  much for taking the time to give such a detailed answer.

Been playing with your example for a couple of hours now and got it to do what I wanted so far. IMO this should be in the documentation or an example / blog.

**Comment by michaellopez** [comment]
@donifer You're welcome. I'll see what I can do for a blog post :)
