### ISSUE TITLE
Redirect not working for gatsby __now_routes_g4t5bY.json

### ISSUE THREAD

**Issue by alesanchezr** [vercel/vercel#3818]
Hello, I have this website deployed on Now: 
https://dev.4geeksacademy.co

I have this dynamically generated redirection file:
https://dev.4geeksacademy.co/__now_routes_g4t5bY.json

Th redirects are not working, it just gives a 404 or 200 instead of 301.
Here is my code: 
https://github.com/4GeeksAcademy/website-v2/tree/80a54a9ee88327bde3c813ab0263674b99f0145f

**Comment by alesanchezr** [comment]
Anyone? @zeke @juliangruber @rauchg @remy

**Comment by coetry** [comment]
Hi @alesanchezr I'm unable to access your repo to take a look at your code. Is it a private repo perhaps? Also can you elaborate more on how you are trying to redirect? Dynamic redirects should be done on the client, and if you need server-side redirects, they should typically be a static decision made ahead of time.

**Comment by alesanchezr** [comment]
Hey @coetry thanks for the reply! Yesterday I made it private (bad luck 😓). I just made it public again.

I am using the `createRedirect` function available as a gatsby action, here is an example inside my code:
https://github.com/4GeeksAcademy/website-v2/blob/80a54a9ee88327bde3c813ab0263674b99f0145f/gatsby-node.js#L104

I want to avoid having to add all the redirects manually on the now.json. Is it mandatory to add them on the now.json?

Because I though I could dynamically create this json file during build time:
[__now_routes_g4t5bY.json](https://dev.4geeksacademy.co/__now_routes_g4t5bY.json)

**Comment by phuoccss** [comment]
`__now_routes_g4t5bY.json` will be deleted by Now once the build completes. Can you give an example of a page that doesn't redirect correctly?

**Comment by alesanchezr** [comment]
Well its not being deleted, here it is on the production environment: https://dev.4geeksacademy.co/__now_routes_g4t5bY.json

Here is an example of one redirect that is supposed to return `301`:
![Screen Shot 2020-04-12 at 5 22 26 PM](https://user-images.githubusercontent.com/426452/79080362-33b25600-7ce2-11ea-9f8c-82ec976485fe.png)

From `/en/apply` to `/us/apply`

Instead of returning a `301` redirect it's returning a 200 and printing a front-end redirect like this:
```
<meta http-equiv="refresh" content="0; URL='/us/apply/'" />
```
It's doing that because I also added front-end redirects in case the backend redirect didn't work.

**Comment by phuoccss** [comment]
What do you mean it's not deleted? It's returning 404, meaning the file is not there, as it's supposed to.
<img width="270" alt="image" src="https://user-images.githubusercontent.com/15166715/79086327-39557d80-7d6e-11ea-8a06-7392190f44dc.png">

Can you try removing `redirectInBrowser`? It's only needed when server cannot handle redirects. And maybe you need to delete the original page too, using gatsby's `deletePage`.

**Comment by alexander-r-jaimy** [comment]
Good afternoon, I have similar issue:
serverless function that runs in getInitialProps respond with correct status code:
![Screenshot from 2020-05-19 13-25-23](https://user-images.githubusercontent.com/60174868/82326789-ab5c5a80-99dd-11ea-8325-1f426f6cb101.png)
However, now server responds with 404:
![Screenshot from 2020-05-19 13-25-48](https://user-images.githubusercontent.com/60174868/82326829-ba430d00-99dd-11ea-8911-a2f2ba8ed96c.png)
And finally my code is like:
![Screenshot from 2020-05-19 13-30-11](https://user-images.githubusercontent.com/60174868/82326845-c29b4800-99dd-11ea-8979-7e87e2b9a8bc.png)

I'm unable to understand what's missing

And it doesn't matter where I'm trying to redirect, inside or outside the application, I see that location header is being added but status code is 404 instead of 301/302.

It looks like this solution is no longer working:
https://github.com/zeit/next.js/issues/649

**Comment by trek** [comment]
Hi @alesanchezr,

Thank you for the bug report. We're closing out older issues that have probably been addressed by now.
