### ISSUE TITLE
not work with local yarn workspaces package

### ISSUE THREAD

**Issue by bluelovers** [vercel/vercel#3819]
~~when a package is only exists in yarn workspaces (not publish to npm)~~

~~import file will fail~~

```
Cannot find module 'build-json-cache/.cache/temp/titles.json'.
```

test repo
https://github.com/demonovel/opds/tree/now/issues/3819

https://github.com/demonovel/opds/blob/now/issues/3819/packages/web/pages/api/search.ts

----------

looks like is can't import json

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/75101104-6a3cf000-5612-11ea-9485-c82d918bbb7f.png)

build is work when running local pc, but build is fail on now server

**Comment by momakes3** [comment]
**Update 2**: The problem was it was accidentally using `npm` because there was a package-lock.json within a package of the monorepo.

**Update**: Actually tried an older commit that was deployed before and it deployed, so it might be something else, I'll update this.


Same. 
It compiles successfully locally: 
![image](https://user-images.githubusercontent.com/56743114/76899119-2b662700-68ac-11ea-9f20-193ee25ef75a.png)

But when deployed it always fails with the error from the workspace package that I import in the next project.
![image](https://user-images.githubusercontent.com/56743114/76899226-5ea8b600-68ac-11ea-93c0-bcb4c768f6af.png)

It started happening 4 days ago, wondering why. I was on next 9.1.5, upgraded to latest (9.3.x) and still no difference.

**Comment by hoangvvo** [comment]
I am also having similar problems with Yarn workspace. I set Root Directory to point to the folder of the package in the monorepo. Since it is a package of a Yarn workspace, it does not have a lock file.

The build fails at step 3/5

```
13:15:13.615  
[3/5] Fetching packages...
13:15:14.607 
error https://registry.yarnpkg.com/regenerate-unicode-properties/-/regenerate-unicode-properties-8.2.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, chmod '/zeit/.cache/yarn/v6/npm-regenerate-unicode-properties-8.2.0-e5de7111d655e7ba60c057dbe9ff37c87e65cdec-integrity/node_modules/regenerate-unicode-properties/Binary_Property/Grapheme_Base.js'"
13:15:14.607  
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
13:15:17.130  
warning url-loader@1.1.2: Invalid bin field for "url-loader".
13:15:20.902  
Error: Command "yarn install" exited with 1
13:15:22.734  
Done with "package.json"
```

It would fail immediately upon entering 3/5, with a random library/pkg. I tried to copy that folder elsewhere (outside of the yarn workspaces) and ran `yarn install` successfully.

I will try to create a simple reproduction or can give access to the private repo upon requested.

Thanks!
