### ISSUE TITLE
[node & nextjs] LAMBDA_RUNTIME Failed to post handler success response.

### ISSUE THREAD

**Issue by bluelovers** [vercel/vercel#3825]
> [ERROR] [1582551956881] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.

when i response a big data from server ( about 6mb )

server is fail with this message

**Comment by IanShaffer** [comment]
I get this error when trying to retrieve 10mb videos. Is there a limit to individual static file size?

**Comment by styfle** [comment]
The maximum payload size for the request body or the response body of a Serverless Function is 5MB.

If a Serverless Function receives a payload in excess of the limit it will return an error - 413: `FUNCTION_PAYLOAD_TOO_LARGE`.

This is a hard limit and cannot be increased.

Read more: https://zeit.co/docs/v2/platform/limits#serverless-function-payload-size-limit

**Comment by gruckion** [comment]
My file is 3.5mbs and I am getting this warning. I have an API Gateway that connects to a lambda which then uses the aws-sdk to `getObject` from an S3 bucket. I am using serverless framework, it works fine in the local `serverless-offline` testing. 

It also works fine when the file was smaller, but now it is 3.5mbs it is failing. The response when I hit the end point is;

```
{
    "message": "Internal server error"
}
```

In CloudWatch I get:

```
[ERROR] [1607717147403] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.
```

Says the limit is 6mbs, what's up with this?

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

My file is just a json file

**Comment by benjan-cleo** [comment]
@gruckion Did you find any resolution for your problem with '[ERROR] [1607717147403] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.'

**Comment by mbad0la** [comment]
I've been having the same troubles - just out of curiosity - is this limit on the transfer size or the resource size?

**Comment by dihersolutions** [comment]
While my application outside the vercel service (such as heroku , qovery , railway) is fine, but in vercel experiencing the same problem LAMBDA_RUNTIME failed :'(

**Comment by bradgreens** [comment]
I just experienced this issue, and fixed it be re-deploying a non-operational change to the code. 

There are no files or transfers involved in my endpoint, it is a very lightweight endpoint that makes some additional HTTP requests during execution. I don't think the nested HTTP requests are returning too much data, since the fix was simply by re-deploying it.

I suspect there is a memory leak or aggregation of data happening, but this endpoint is pretty much all immutable code so I can't spot where that would happen.

I am using `next-iron-session` on this endpoint, which may be a factor. I doubt I can consistently replicate it, I will open a new issue if I can.

**Comment by bscaspar** [comment]
@bradgreens by a non-operational change, do you simply mean you effectively redeployed the endpoint with no changes?

This seems to be happening to me across multiple different Vercel API endpoints sending small amounts of data to an AWS API Gateway.

**Comment by bradgreens** [comment]
@bscaspar yes, I redeployed by adding a comment in the code to trigger the redeployment hooks.

I was not able to consistently reproduce it, and the problem has since gone away. 

I do recommend adding logging in your endpoint at every possible step. Because sometimes the code execution stops and the error is not necessarily presented back in a meaningful way. I found issues where my code execution would stop, but 500, 413, or other errors would hide the underlying flaw in the code. Use Vercel's function logs to debug that, assuming you can't replicate locally.

Also, if you're sure it's not the code execution, other thoughts would be to tick your versions slightly up or down in package.json and redeploy, but obviously that's just throwing shit at a wall to see what sticks.

**Comment by KeKs0r** [comment]
I am also running into this issue. I started checking the size of my response:
```
const responseSize = Buffer.byteLength(JSON.stringify(response), 'utf-8')
logger.info('FINAL Response', responseSize, formatBytes(responseSize))
// Response Size 4945777 4.72 MB
```
With this helper: 
```
function formatBytes(bytes: number, decimals = 2) {
    if (bytes === 0) return '0 Bytes'

    const k = 1024
    const dm = decimals < 0 ? 0 : decimals
    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']

    const i = Math.floor(Math.log(bytes) / Math.log(k))

    return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i]
}
```

I would assume that this response is lower than the threshold, but I am still experiencing `LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413`

**Comment by devalphaleap** [comment]
I am having the same problem with server side rendering, on my getServerSideProps, I query the database directly, and the db query is successful. 
Here is the log:

call getStats from db
get data from db 343
[ERROR] [1641741010335] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.

Can someone help?

**Comment by koraysels** [comment]
I am heving the exact same issues.. also mentioned here on the netlify support forum .

https://answers.netlify.com/t/started-getting-function-responsesizetoolarge-error/49625/4

**Comment by ryparker** [comment]
I'm having this issue as well. I'm not seeing a payload larger than 1mb on my page though (via network tab of chrome dev tools). Any tips for debugging this?

Using NextJS by the way.

**Comment by dshunfen** [comment]
@styfle My team was seeing this even with a verified payload of about 2.5MB. We cut down the size to 500kb which seemed to resolve the issue.
That being the case, the conclusion is that it appears that the hard limit of 5MB may not be accurate. Unfortunately, we weren't able to get much more insight into this since the error in the function logs does not provide any more detail about what threshold was tripped that resulted in this error. It would be good to know if 5MB is truly the hard limit here.

**Comment by styfle** [comment]
@dshunfen The limit is not just response body but also headers too.

If you submit a support case, the team can take a look, thanks! https://vercel.com/help

**Comment by rd13** [comment]
I was debugging an issue whereby my site was serving stale content, revalidate was set to 60 minutes, yet the response header was x-vercel-cache: STALE. So digging into the vercel logs led me to this error and reported issue. The issue was indeed that the data size was greater than 5mb and reducing this fixed the revalidation / stale content.

**Comment by pguardiario** [comment]
is the limit before gzipping or after? I'm getting the error with 700k gzipped json

**Comment by roofleDev** [comment]
I'll second that I get the error on a response that's 1mb... which seems to imply gzipping or whatever

**Comment by thanossOp** [comment]
> My file is 3.5mbs and I am getting this warning. I have an API Gateway that connects to a lambda which then uses the aws-sdk to `getObject` from an S3 bucket. I am using serverless framework, it works fine in the local `serverless-offline` testing.
> 
> It also works fine when the file was smaller, but now it is 3.5mbs it is failing. The response when I hit the end point is;
> 
> ```
> {
>     "message": "Internal server error"
> }
> ```
> 
> In CloudWatch I get:
> 
> ```
> [ERROR] [1607717147403] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.
> ```
> 
> Says the limit is 6mbs, what's up with this?
> 
> https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html
> 
> My file is just a json file

I got the same error did you find any solution

**Comment by jramke** [comment]
I got the same error in my express app when storing audio files to the `/temp` folder before sending them back to the client and deleting them. The files are < 5mb but it only appears on longer files like 4/5min+. Had to switch to render where everything works

**Comment by cvargas-xbrein** [comment]
im faced with the problem fron a api with java  too ,apparently the responce is  under 6 mb  :

[ERROR] [1710164971471] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.
