### ISSUE TITLE
File system public routes & rewrites

### ISSUE THREAD

**Issue by Corjen** [vercel/vercel#3836]
Hi! 

First of all, we love Zeit and all the great stuff you are doing. 👏 

We're currently expirementing with custom routes (https://github.com/zeit/next.js/issues/9081), which we want to use for intl. We're experiencing inconsistencies between local development and when deployed to now. 

Here's our demo repo: https://github.com/Corjen/next-custom-routes and deployment url: https://test-dynamic-routing.now.sh/en/test

Locally, url's like `/` `/test` and `/collection` give a 404, which is expected as we have set `useFileSystemPublicRoutes` to `false` in `next.config.js`. Once deployed though, the urls are available, although the rewrites are also working.

Is this intentional, a bug or are we missing something? Thanks for looking into to it!

**Comment by ijjk** [comment]
Hi, we don't currently support disabling `useFileSystemPublicRoutes` when deploying and was originally meant for usage with a custom-server which is not ideal with serverless environments. If you would like to only rewrite to these pages you could prefix the pages with `__` and then rewrite to that e.g. `__home.js` or another value so that they are less likely to be visited but to rewrite to them they need to have be available at some endpoint.

**Comment by Corjen** [comment]
> Hi, we don't currently support disabling `useFileSystemPublicRoutes` when deploying and was originally meant for usage with a custom-server which is not ideal with serverless environments. If you would like to only rewrite to these pages you could prefix the pages with `__` and then rewrite to that e.g. `__home.js` or another value so that they are less likely to be visited but to rewrite to them they need to have be available at some endpoint.

Makes sense 😃 Thanks for the reply!
