### ISSUE TITLE
Should I use one or two package.json files?

### ISSUE THREAD

**Issue by cosbgn** [vercel/vercel#3841]
Hello, this is not an issue, but a clarification as I could not find anything in the docs.
I have a frontend app with it's package.json file and a node.js app in the /api folder. 

Should I have a package.json inside the /api folder with my backend libraries? So far I have everything in the main frontend package.json and it all works fine. 

I'm just wondering if this would make my frontend app heavier and slow it down? Is there any drawback on having all my backend libraries in the frontend package.json file?

Thanks.

**Comment by styfle** [comment]
If you create a file `/api/package.json` then it will be used for your Serverless Functions instead of the root `package.json`. 

There shouldn't be a difference because the build will tree-shake before creating Serverless Functions and your frontend only uses the output files in the `public` directory (or you can define any output directory).

**Comment by cosbgn** [comment]
Thanks
