### ISSUE TITLE
Debugging with `now dev` inside IntelliJ IDEA

### ISSUE THREAD

**Issue by tomadimitrie** [vercel/vercel#3849]
Is this supported? I can't get to attach the debugger

**Comment by styfle** [comment]
Attaching a debugger is not possible at this time, we might add support in the future.

See related issues #2864 and #2077.

**Comment by ggascoigne** [comment]
I realize that this is closed, but can I add my voice to those wanting to find some way to support this.  Part of the promise of  `now dev`, and one of the reasons why it can try and hide the details of what it's doing is that it should make things simpler.  If I have to bypass all of this and install the aws lambda sdk so that I can develop efficiently, then I feel that `now dev` is missing the boat.

**Comment by styfle** [comment]
We are currently rewriting `now dev` to improve performance and consequently, it will also make it easier to add a debugging feature in the future.

**Comment by tilman** [comment]
Any progress on the debugging feature already?

**Comment by CootieMonster** [comment]
Any progress on this?

**Comment by taprile314** [comment]
any progress on this?
