### ISSUE TITLE
Official Flask Example

### ISSUE THREAD

**Issue by redreceipt** [vercel/vercel#3868]
Feature Request: An official Flask example using `now init`

**Comment by styfle** [comment]
We show a [Flask WSGI example](https://zeit.co/docs/runtimes#advanced-usage/advanced-python-usage/web-server-gateway-interface) in the documentation.

However, we are using `now init` for frontend frameworks, the same ones you see during [import](https://zeit.co/import/templates).

Flask is a backend framework so it will not be considered. Similarly, there is no express example for Node.js because these patterns give the wrong impression to new users.

The pattern we want to lead users into is the following:
- Your favorite frontend framework that generates html files (SSG)
- Your favorite backend language in the `/api` directory where each file is a function
- Routing is handled by the filesystem in both frontend and backend
