### ISSUE TITLE
Remove IDs

### ISSUE THREAD

**Issue by leo** [vercel/vercel#387]
There's no need for IDs anymore. All of our data sets have their own identifiers (like deployments have a URL or a domain and the same for aliases).

This was suggested by @nkzawa.

**Comment by matheuss** [comment]
Not all of them – credit cards for example 👌

**Comment by matheuss** [comment]
I think @jamo suggested another data set that need IDs 🤔 Can't recall

**Comment by leo** [comment]
Nah, completely... 😊 

<img width="441" alt="screen shot 2017-03-17 at 16 02 37" src="https://cloud.githubusercontent.com/assets/6170607/24049080/2e479594-0b2b-11e7-8655-9adaa7c4b879.png">

**Comment by jamo** [comment]
E.g removing DNS records will become pita.
`now dns rm zeit.ninja @ A 0.0.0.0` would be the minimal syntax to remove a single DNS record...

**Comment by jamo** [comment]
For domains (not DNS), aliases, and deploymets this would be ok. For the rest, well, not so much

**Comment by leo** [comment]
We could introduce something like:

```bash
now dns rm zeit.ninja
```

Which DNS record for `zeit.ninja` would you like to remove?

- A (0.0.0.0)
- CNAME (test.tld)

The user could cycle through these with the up and down arrows.

**Comment by jamo** [comment]
How would one possibly automate this? 
IMO That could be ok for web but not for a cli
cc @rauchg

**Comment by leo** [comment]
Does "automate" mean running `now` inside a CI env? In this case, the program could still specify the whole value list like you stated it [here](https://github.com/zeit/now-cli/issues/387#issuecomment-287383872).

**Comment by nkzawa** [comment]
It seems we fixed all sub-commands with https://github.com/zeit/now-cli/pull/665, except ones which has no identifiable values .

**Comment by OlliV** [comment]
I disagree with removing the IDs from the DNS. If the point is to make it easier it doesn't, instead it makes it harder to use. The only viable option to remove a record is to type the whole record which isn't nice. The reason: It's rather complicated which parts of the record are unique and I'd hate to see an interactive list. If you really want to make it better, I'd suggest a `dns.json` interface but IMO that can't be the only interface.

Then again it's absolutely necessary to have IDs for certificates because a single certificate can contain multiple common names and in theory there could be multiple certs for the same domain.

**Comment by leo** [comment]
Completely agreed, @OlliV! We just removed them from `now secrets`, which is fine. All other commands definitely still need them (just held a discussion with @nkzawa to be sure).
