### ISSUE TITLE
Take multiple arguments in domains buy

### ISSUE THREAD

**Issue by darknoon** [vercel/vercel#470]
Would be useful to check multiple for availability: `now domains buy myco.com myco.co.uk`

or a text file / stdin?

**Comment by leo** [comment]
Sounds like a very good idea!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
