### ISSUE TITLE
"vercel-build" in package.json isn't recognized

### ISSUE THREAD

**Issue by iinfin** [vercel/vercel#4758]
There is an option to add `now-build` in package.json and it gets prioritized over `build` script.
I guess it should now be updated to also recognize `vercel-build`.

**Comment by TooTallNate** [comment]
Yes indeed. We will be adding support for this soon!

**Comment by iinfin** [comment]
Do you think `vercel` will be possible instead of `vercel-build`? I think it's more simple and clean but not sure if it'd conflict with something else.
Thank you regardless @TooTallNate, looking forward to either of them.

**Comment by gurkerl83** [comment]
**UPDATE: THIS COMMENT IS NOT RELATED WITH THIS ISSUE**

The deployment of my app is breaking without any hit of the reason. I did a small experiment and found the cause. It seems a bug was introduced from @vercel/next@2.6.8-canary.5 => @vercel/next@2.6.8-canary.6, the incremental test further down.

My setup.
I have a vercel.json file. Important to note is that I have in package.json a vercel-build script that executes several build tasks in a row. This was working perfectly fine until now. The is an issue mentioned in the Github repo that vercel-build script is not recognized. Before, I had a now-build script, but this also works not anymore.

I`m not sure the problem is related to this issue, but the time of my last deployment working aligns with the date this issue was created. I compared the version tags of the source code canary.5 to canary.6, and there is some now.json/vercel.json stuff in it, which might make this not working anymore.

I usually use in vercel.json 
"src": "package.json",
"use": "@vercel/next"

Because this is not working anymore in the experiment, it tried the canary versions. To track the bug, I incrementally increased the canary version in the build/use property. I have executed the following deployments and found the following results.

"use": "@vercel/next@2.6.7" => working
"use": "@vercel/next@2.6.8-canary.0" => working
"use": "@vercel/next@2.6.8-canary.1" => working
"use": "@vercel/next@2.6.8-canary.2" => working
"use": "@vercel/next@2.6.8-canary.3" => working
"use": "@vercel/next@2.6.8-canary.4" => working

**"use": "@vercel/next@2.6.8-canary.5" => Still working**
See deployment result - https://vercel.com/gurkerl83/millipede-docs/dz3jinylz 
**and file vercel.json** of the respective deployment 
https://vercel.com/gurkerl83/millipede-docs/dz3jinylz/source?f=src%2Fvercel.json

**"use": "@vercel/next@2.6.8-canary.6" => !!! NOT WORKING ANYMORE !!!**
See deployment results - https://vercel.com/gurkerl83/millipede-docs/1nebrwov6
**and file vercel.json** of the respective deployment 
https://vercel.com/gurkerl83/millipede-docs/1nebrwov6/source?f=src%2Fvercel.json

"use": "@vercel/next@2.6.8-canary.7" => NOT WORKING
"use": "@vercel/next@2.6.8" => NOT WORKING
"use": "@vercel/next@canary" => NOT WORKING

The only solution is to pin the version and select either the latest working @vercel/next to 2.6.8-canary.5 or @vercel/next@2.6.7.

Thx!

**Comment by iinfin** [comment]
@gurkerl83 I don't really think this is related.

Your problem could be about a particular Next.js version, But it specifically says:
> Build Failed. Internal error. Please contact support@vercel.com.

You should take a look at [its own repository](https://github.com/vercel/next.js/) and [issues](https://github.com/vercel/next.js/issues) instead, or [contact support](https://vercel.com/support/request).
