### ISSUE TITLE
List Deployments w/ Aliases

### ISSUE THREAD

**Issue by mojo5000** [vercel/vercel#488]
I know we can see them both separately (now ls + now alias ls), but seeing this info together would help.

now ls -a (alias/advanced/all?)

Great if we could see both running instances along with their aliases.  Perhaps a column with an orange colored alias name.  It's difficult to know which deployment is which.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
