### ISSUE TITLE
Issue updating Now to the latest after Vercel name change

### ISSUE THREAD

**Issue by kirillzubovsky** [vercel/vercel#5082]
https://github.com/vercel/vercel/blob/ee8dff2dc986002aec318a9c862659b02f381f8b/packages/now-cli/src/index.js#L143

I was experiencing a bug updating `now` to the latest version, and I've just realized it is caused by Vercel and Now being interchangeable options. I am not sure exactly where to fix it, so making this as a note for someone who does.

After deploy, I would get a message 
`> UPDATE AVAILABLE Run npm i -g now@latest to install Vercel CLI 19.2.0`
But making this update does not change anything, and the message appears again.

From what I understand that's because the script checks for the latest version of Vercel, but installs the latest version of Now. 
Updating "now" > "vercel" in package.json fixed the issue. Running `npm i -g vercel@latest` fixed it too.

If you find out where to fix this, can you leave a comment. I'd love to know.

**Comment by styfle** [comment]
Hi @kirillzubovsky 

This was fixed in PR #5051 so after you update `npm i -g vercel@latest` (20.0.0 or newer), then you won't see this issue for subsequent updates.

Also note that [`now`](https://www.npmjs.com/package/now) is deprecated and you should be using [`vercel`](https://www.npmjs.com/package/vercel) instead.

Thanks!
