### ISSUE TITLE
Add option to filter deployments in list by state

### ISSUE THREAD

**Issue by hawkins** [vercel/vercel#621]
Some of my builds have failed in the past, so I see some deployments with state `BUILDING` from 30+ days ago when I run `now ls`. I know they'll never finish, but I want an easy way to remove those deployments, rather than manually looking through all deployments for them.

It would be great if there was a way to filter for deployments by state; something like `now ls -s building` or `now ls -s ready` etc. This way we could more easily tell if we have failed deployments and inspect them alone.

**Comment by hawkins** [comment]
If this is something the team feels would fit in the project, I'd be happy to try to integrate this feature myself

**Comment by leo** [comment]
This sounds like an interesting idea. Even with support for [metadata](https://zeit.co/blog/deployment-metadata), this still makes sense.

**Comment by hawkins** [comment]
Metadata does look nice! But I think you’re right, it still leaves this particular capability unsolved, and I know it’s one I’ve needed every time I’ve used now since I opened the issue. 

I’ve made due with manual `grep`, though that can obscure other information I wanted to know, so I personally think a proper solution to this issue is still needed.

I’m happy to contribute it myself, so since you’re interested, I’ll see if I can’t spin something together by this weekend!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
