### ISSUE TITLE
Deploy subdirectory as static deployment

### ISSUE THREAD

**Issue by ksmithut** [vercel/vercel#622]
It would be cool if you could have a `now.json` that could publish a subdirectory as a static website. A lot of build tools (like create-react-app and `next.js` export a "static assets" directory like `build/` or `dist/`. Rather than have to `cd` into that directory and run `now`, it would bee cool to have now config in the root project something like this (now.json):

```
{
  "name": "my-next-website",
  "alias": "my-next-website",
  "type": "static",
  "root": "./build"
}
```

Or something like that. Or can this already be done?

**Comment by leo** [comment]
`now ./build` works without any config... 😊

**Comment by ksmithut** [comment]
alright, I'll stick with that :) Thanks

**Comment by ksmithut** [comment]
@leo So my deploy script looks like this:

```npm run build && now ./build && now alias```

And my config:

(I replaced my alias/name for stubs)

```
{
  "name": "my-name",
  "alias": "my-alias",
  "type": "static",
  "files": [
    "build"
  ]
}
```

It deploys it just fine, but it doesn't alias the right deployment:

```
> Deploying ~/path/to/project/build under username
> Ready! https://build-newhash.now.sh (copied to clipboard) [6s]
> Initializing…
> Deployment complete!
> Assigning alias my-alias to deployment...
> Success! my-alias.now.sh now points to my-alias-oldhash.now.sh! [783ms]
✨  Done in 23.33s.
```

Note that the build that was created `build-newhash.now.sh` did not match `my-alias-oldhash.now.sh`. I assume that when I specified that subdirectory, it now looks for a `now.json` in the subdirectory, but when it sets the alias, it takes the last deploy that I did from the upper directory.

Any idea how I can get this to work? Should I have a `now.json` be put into my build directory during my build step?

**Comment by leo** [comment]
The alias config would have to be in the same directory as the deployment (./build), yep.

**Comment by ksmithut** [comment]
cool, thanks :)

**Comment by benjick** [comment]
Agree, would be nice to shorten this:

```
npm run build
cp now.json build/
cd build
now --static
now alias
```

**Comment by kristojorg** [comment]
I have a pretty decent solution for this:

1. In `package.json` add:
```
{
  "scripts": {
    "deploy": "yarn build && now ./build",
    "alias": "cd ./build && now alias",
    ...
  }
}
```

2. Add a `now.json` to your `./build` folder. I am using `create-react-app`, so I added `now.json` to my `./public` folder so that it would be included in `./build` during the build step.

3. Run `yarn deploy` and `yarn alias`

It would be nice if now cli detected `now.json` or `package.json` in the parent folder when deploying a subdirectory

**Comment by kristojorg** [comment]
One downside of just deploying a `./build` directory instead of deploying the parent (and specifying `./build` as the static assets to serve) is that source files are not included in the deployment and therefore the `public` option and `/_src` is not very useful

**Comment by jacobmischka** [comment]
I feel this should be reopened, this doesn't seem like a very elegant solution to me. Especially when most interactions with now are pretty elegant.

```json
"scripts": {
  "deploy": "now --static public/ && cp now.json public/ && cd public/ && now alias && rm now.json"
}
```

**Comment by ksmithut** [comment]
There’s a config option in now.json (we’ll at least it’s documented), but it doesn’t work. The new issues is at #1075

**Comment by jacobmischka** [comment]
Oh, I looked on the website docs and didn't see that option, but I didn't check the README. Thanks!

**Comment by ksmithut** [comment]
You bet :) still wished it worked... but alas

**Comment by sergiodxa** [comment]
@benjick @jacobmischka you don't need to copy the now.json.

Now CLI has an option `--local-config=FILE` (or `-A FILE`). You can use it to deploy a subfolder using the correct now.json file without copying it everytime.

```bash
now ./build -A ../now.json
```

That will deploy the subdirectory `./build` using the `now.json` in his parent (your root). You can then run `now alias`. So a deploy and alias command will looks like:

```bash
now ./build -A ../now.json && now alias
```

**Comment by jacobmischka** [comment]
Oh that's definitely better, thanks!

**Comment by AdamGerthel** [comment]
> Now CLI has an option --local-config=FILE (or -A FILE). You can use it to deploy a subfolder using the correct now.json file without copying it everytime.

Does this work for package.json as well? For those that prefer too keep the now config there I mean.

**Comment by revelt** [comment]
hi all,
This ticket was closed prematurely, **it is actually not solved**.

Ideally, as a customer, I want a clear example in https://zeit.co/examples/ of how to deploy a subdirectory as a static deployment.

I have MSc and know web development. Yet I find documentation unfriendly and struggle with _now_'s config.

When @leo  says:

> now ./build works without any config... 😊

Yes it does work. But instructions in documentation start with suggesting to create a `now.json`!

I struggle concoct a `now.json` that does exactly the same thing.

It's not this:

```json
{
  "version": 2,
  "builds": [
    { "src": "public/**/*.*", "use": "@now/static" }
  ]
}
```

And not this:

```json
{
  "version": 2,
  "builds": [
    { "src": "public/", "use": "@now/static" }
  ]
}
```

And the problem is, the documentation points out to start from creating a config file, so vast majority of new starters **will stumble** trying to serve from subdirectory. The main USP of _now_ is user-friendliness and it's currently lacking.

Looking from an API perspective, I see clearly that somebody overlooked the **subfolder aspect** of the static deployment. And root customisation can't be solved via `src` in `builds` because there can be many different `src`s targeting different levels. Logically, I can see one possible solution — introduce a new key — `root` path:

```json
{
  "version": 2,
  "builds": [
    { "src": "public/", "use": "@now/static" }
  ],
  "root": "public/"
}
```

Let's reopen this ticket and address it properly.

1) Update https://zeit.co/docs/v2/deployments/official-builders/static-now-static/ to mention how to publish subfolder as root.
2) Update https://zeit.co/examples/ with static subfolder example: a) with no `now.json` and with `now.json` and `.nowignore` and real life example, where let's say Gulp is using Nunjucks to build static website in `public/` folder and we want to publish contents of that folder as static.
3) Consider API improvements

**Comment by mightyiam** [comment]
Wait, so there's currently no way to achieve this using `now.json`?

**Comment by tdjsnelling** [comment]
I agree with @revelt. I can't seem to find docs on this anywhere. I have a repo with `client/` and `server/` subdirectories, the client being a create-react-app application. This isn't a problem locally, where I can just `cd client && now` but I can't work out how to just deploy the client when using now for github, where `now.json` must be in the project root.

Currently, I am using this now config:

```JSON
{
  "version": 2,
  "build": {
    "env": {
      "REACT_APP_ENV": "production"
    }
  },
  "builds": [
    { "src": "client/package.json", "use": "@now/static-build" }
  ],
  "routes": [
    {"src": "^/static/(.*)", "dest": "/static/$1"},
    {"src": "^/favicon.ico", "dest": "/favicon.ico"},
    {"src": "^/asset-manifest.json", "dest": "/asset-manifest.json"},
    {"src": "^/manifest.json", "dest": "/manifest.json"},
    {"src": "^/service-worker.js", "headers": {"cache-control": "s-maxage=0"}, "dest": "/service-worker.js"},
    {"src": "^/precache-manifest.(.*)", "dest": "/precache-manifest.$1"},
    {"src": "^/(.*)", "dest": "/index.html"}
  ]
}
```
but this leads to my code being deployed at `my-project.now.sh/client/...` rather than at the root. Is there any way around this other than splitting my code up into 2 repositories?

**Comment by mightyiam** [comment]
@tdjsnelling perhaps instead of all of the `routes` you could use the `config.distDir` field.
https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build/#configuring-the-dist-directory

**Comment by donedgardo** [comment]
Support for static build folders in now.json would be :+1: for automatic deployments feature. Agreed with @revelt this should be reopened.

**Comment by bfulop** [comment]
I've raised this question over the spectrum chat and @paulogdm [quickly pointed me to a solution](
https://spectrum.chat/zeit/general/static-builder-vs-static-builds-builder~ad8916ea-a106-4be9-8e34-2595c6b549c9) (thanks!)

You need to add a `routes` property as below. The catch-all rule (`/(.*)`) should be the last in the list if you have more than one route.

```json
{
  "version": 2,
    "builds": [
      { "src": "./dist/**", "use": "@now/static" }
    ],
    "routes": [
      { "src": "/(.*)", "dest": "dist/$1" }
    ]
}
```

With this setup, I can build locally on my machine to the `/dist` directory, but keep the `now.json` file in the root folder (and add more builds targets). 

He also noted:

> 1- Make a new .nowignore file that will ignore everything, except now.json and build. Example: https://github.com/zeit/now-examples/blob/master/nextjs/.nowignore

**Comment by vladshcherbin** [comment]
https://github.com/zeit/now-cli/issues/622#issuecomment-454482804

Kinda meh solution, you still need to use `.nowignore` to ignore all files except build. Your config will also get dirty (if even possible) when you have files in dist that you don't want to serve (like `package.json`).

Solution that kinda works for now: https://github.com/zeit/now-cli/issues/622#issuecomment-360889358

`root` will be still a much better solution.

**Comment by bigsee** [comment]
+1 for @revelt's point re: docs. They leave quite a bit to be desired in this area, which is a shame given the great DX Now usually affords us...

**Comment by rskvazh** [comment]
Why is @now/static documentation has been disappeared from anywhere? Is it deprecated?

**Comment by YuriGor** [comment]
Just in case someone like me will be struggling with the task of serving static files from node_modules:
it is possible using `copy-webpack-plugin` in next.config.js [as suggested here](https://github.com/vercel/next.js/issues/3444#issuecomment-479454594):
```js
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  webpack: (config, { isServer }) => {
    config.plugins.push(
      new CopyWebpackPlugin([
        {
          from: path.join(__dirname, 'node_modules/widget-editor/dist/images'),
          to: path.join(__dirname, 'static/images/widget-editor/')
        }
      ])
    );
    return config;
  }
};
```
