### ISSUE TITLE
now alias ls [alias] does not work on simple aliases

### ISSUE THREAD

**Issue by Sequoia** [vercel/vercel#673]
## Aliases

```
$ now alias ls
> 4 aliases found [877ms] under sequoia

  source                             url                                 age
  https://auth-pqcfahnogz.now.sh     https://sequoia-auth.now.sh          2d
  https://webapp-bpgcubktqz.now.sh   https://sequoia-webapp.now.sh        2d
  [3 custom rules]                   https://sequoia-monolith.now.sh      2d
  [4 custom rules]                   https://counter-demo.now.sh         16d
```

## `now alias ls alias-with-rules`

```
$ now alias ls counter-demo.now.sh
  pathname    method  dest
  /login      *       writer-gkdldldejq.now.sh
  /increment  *       writer-gkdldldejq.now.sh
  /logout     *       writer-gkdldldejq.now.sh
              *       reader-jdaugptkks.now.sh
```

## `now alias ls alias-without-rules`

```
$ now alias ls sequoia-auth.now.sh
> Error! Could not match path alias for: sequoia-auth.now.sh
```

# Expected

`now alias ls <alias>` returns info about an alias

# Actual

`now alias ls <alias>` **fails** if it's a simple url 👉  source alias

**Comment by leo** [comment]
@Ignigena Did your most recent change affect this?

**Comment by andymckay** [comment]
As far as I can tell `alias ls` does not accept these arguments and I think the usage of this command no longer exists. This issue is from a few years ago, so a few things have probably changed since then. 

Based on that, I'm going to close this issue, but if it's wrong please let me know and I'll re-open. Thank you for the issue 🙇🏾
