### ISSUE TITLE
now ls <name> doesn't find app

### ISSUE THREAD

**Issue by 1jerry** [vercel/vercel#682]
I cannot list _only_ deployments for a specific app.
## Example:

```
>now ls
> 8 deployments found under <me>
"Teachers" (5 of 5 total)
teachers-<randomString>.now.sh  ...

>now ls teachers
> 0 deployments....
```

I've tried teachers, Teachers, "Teachers", "teachers".  **always** 0 found.  Searching through the issues I found nobody else with this issue, but I cannot see what I could be doing wrong.  (Maybe a separate "issue", but is there no way to remove multiple deployments?  It seems crazy to have to copy&paste _every single url_ to delete all my obsolete deployments.)

[Windows 10 cmd.exe]
>now -v
7.0.1
>node -v
v7.9.0

**Comment by Qix-** [comment]
What does `now ls \"Teachers\"` (with the backslashes) show you?

**Comment by 1jerry** [comment]
Interesting.  That works.  I wonder if this is a Windows thing or because I'm using the Meteor tool [meteor-now](https://github.com/jkrup/meteor-now)?  Although that tool _does not_ add a --name parameter, just passes a series of -e parameters, and there is no extra quote marks in the package.json file.

edit: I see in the Dockerfile the line: `LABEL name="Teachers"`.  That must be what is setting the "app" name.  If that is so, I will need to post the bug as a `meteor-tool` issue, and tell them to remove the quote marks?

**Comment by Qix-** [comment]
This was actually a bug in an upstream dependency, `docker-file-parser`. I submitted a patch at joyent/node-docker-file-parser#3.

In your specific case, you can do a temporary workaround for this by manually removing the quotes if you'd like - it shouldn't matter in this case you since it's a single word.

Alternatively, set `"name": "Teachers"` in your `now.json` file, or use the `--name Teachers` command line flag when deploying.

Thanks for the report! I'll close this when the PR lands.
