### ISSUE TITLE
Pass `debug` flag in all places `handleError` is being used

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#689]
By passing `, { debug: true }`, we would get the ability to see stack traces whenever `-d` is used and an error occurs that gets passed to the `handleError` utility

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
