### ISSUE TITLE
`now teams add` with invalid team name still seems to work despite error

### ISSUE THREAD

**Issue by Qix-** [vercel/vercel#699]
A screenshot is going to illustrate this better:

<img width="836" alt="screen shot 2017-06-27 at 10 22 01 pm" src="https://user-images.githubusercontent.com/885648/27621648-2fc7a5a6-5b87-11e7-81ed-e4d3e2d15227.png">

I think all of the pieces of information should be included _first_ before any mutating API calls are made (i.e. notwithstanding any availability calls, etc).

Even then, it appears the CLI still stripped away all of the bad characters and submitted it anyway, and the team was created successfully.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
