### ISSUE TITLE
"files" key in now.json doesn't override .gitignore

### ISSUE THREAD

**Issue by mjswensen** [vercel/vercel#717]
First of all, `now` is amazing. Seriously. 👏 

I've seen a number of variations on this issue (including some discussion on Slack), but in my digging I haven't been able to come up with an answer that makes sense. So please feel free to close if this is a duplicate.

In the [`now.json` docs for the "files" key](https://zeit.co/docs/features/configuration#`files`-(array)):

> A list of files and directories to be force-uploaded to the deployment (even if they're ignored by .gitignore).

So in my docker project, I have the following files:

`.gitignore`

    target

`now.json`

    {
      "type": "docker",
      "files": [
        "target"
      ]
    }

I would expect the contents of the `target` directory to be uploaded. (I also tried the more explicit `"./target"`.) However, the directory is not uploaded unless I remove the relevant entry from `.gitignore`.

What am I missing?

**Comment by mjswensen** [comment]
It's also worth noting that my project also has a `package.json` file, which may mean that `now-cli` is applying different behavior even though my project type is set to `"docker"` in `now.json`. Possible?

**Comment by mjswensen** [comment]
Confirmed this one again on now @ 7.2.4. I have a static site where some of the assets are created at build time. Therefore, I keep the built asset directory under `.gitignore` but would like to deploy them when I run `now`. So I add the directory name to the `"files"` array in my now config, but the files are not uploaded unless I temporarily remove them from the `.gitignore` every time I want to deploy.

**Comment by hlobil** [comment]
I have the same issue. Use to work with .npmignore. I added dist to files and because I have .gitignore with dist directory it doesn' t upload static files in dist.

https://zeit.co/docs/features/now-cli#selecting-files-and-directories-to-be-uploaded

**Comment by gregsantos** [comment]
I'm having the same issue with now --docker deploys. Tried adding "files" array to package.json and now.json to no avail. Also solved when removing "dist" directory from .gitignore

**Comment by revolunet** [comment]
same issue with npm deploys : https://github.com/zeit/now-cli/issues/273#issuecomment-324286930

**Comment by revolunet** [comment]
workaround : put your .gitgnore in subfolders, now will not use them but git/npm will

**Comment by matheuss** [comment]
@leo @TooTallNate could you take a look at this? It should override with no issues – I wonder if we changed something recently? Also @Qix- I think you recently sent a PR for this, no?

**Comment by leo** [comment]
Did we ever make it override? I mean it should, but I don't think we ever added that. It was more of a "include only these files" feature.

**Comment by revolunet** [comment]
[doc](https://zeit.co/docs/features/configuration#%60files%60-(array)) says "files: A list of files and directories to be force-uploaded to the deployment (even if they're ignored by .gitignore)."

**Comment by Qix-** [comment]
Thought this was fixed in #692 but it may have pertained to something else. We should have a very clear order of operations for file inclusion - I feel like the ignore pattern logic is really arbitrary as it exists now.

I would agree that `"files"` in _now.json_, if present, trumps all (much like it does for NPM packages in package.json).

I'd also push for contextual ignoring, where ignoring behaves more synonymously with the type of deployment you're creating:

- **Docker Deployment**: Check `"files"` key (now.json); fallback to `.dockerignore`; fallback to `.gitignore`; otherwise, push everything
- **Node.js Deployment**: Check `"files"` key (now.json); fallback to `"files"` key (package.json); fallback to `.npmignore` (including the [default ignored paths](https://docs.npmjs.com/misc/developers#page)); fallback to `.gitignore`; otherwise, push everything
- **Static Deployment**: Check `"files"` key (now.json); fallback to `.gitignore`; otherwise, push everything

For each of the types of deployments above, inclusion/exclusion discovery stops on the first satisfied check (e.g. if it's a Node.js deployment and `"files"` isn't present but `.npmignore` is, use `.npmignore` and stop there - don't continue to evaluate `.gitignore`, etc).

This would ultimately result in _much_ more predictable and sensible behavior IMO.

I don't think there should ever be a circumstance where we evaluate _both_ an `.npmignore` and a `.dockerignore` since they don't make sense in the same context IMO. I dislike the fact a lot of the file inclusion workarounds consist of making several types of ignore files.

Ultimately, if your build artifacts are so complex that you need several 'layers' of inclusion/exclusion patterns like a few of the people I've seen have requested (e.g. files key, npmignore, dockerignore, gitignore all put together), you should _probably_ simplify your build process/project structure since that workflow isn't going be sustainable in the long term regardless of whether or not you're using Now. Just my two cents.

This logic would solve #717 (this issue), #742, #157, and I'm sure a few others (e.g. would probably hit #597 et al).

Thoughts?

**Comment by revolunet** [comment]
this sounds more consistent and predictable behaviour.

there's also the package.json `now.files` attribute ?

**Comment by Qix-** [comment]
Good catch @revolunet.

In my personal opinion, the `now` section of the package.json should be deprecated and ultimately removed in favor of now.json - but that's just a personal opinion, would love feedback on that too. I'd like to hear reasoning for _keeping_ the `now` block from those who use it as opposed to using now.json.

My opposition to it is that there's no clear precedence when there are both a `now` block and a `now.json`, and even with my proposed changes above there are still a lot of moving pieces to the configuration puzzle.

I also think there's some worth in logically separating out an NPM package manifest from the means by which it is deployed.

Again, purely subjective view and would love any thoughts.

**Comment by revolunet** [comment]
+1 to deprecate package.json now section. i dont want to publish my now setup to npm/github

**Comment by BassT** [comment]
@Qix that's a nice proposal.

But I think I'm missing how this solves the original issue.

@mjswensen (and also myself) wants to 
- **include** files listed under `files` **and**
- **exclude** files listed in `.gitignore`.

As far as I understand you're proposing to
- **include** files listed under `files` **or**
- **exclude** files listed in `.gitignore`.

Do you agree?

I like the idea of having configuration to explicitly include and exclude files.

**Comment by tdurand** [comment]
I ran into that issue today, what is the status ? 😁

**Comment by dpfavand** [comment]
I also think I've run into this issue.

.gitignore
```
...
/dist/
...
```
now.json
```
{
  "files": [ "dist" ],
  "type": "static"
}
```
`dist` directory is not uploaded. In fact only `now.json` is uploaded, even though it's in the root (not in `dist`) and there are other files in the root directory.

**Comment by cachrisman** [comment]
I've also run into this issue. `.gitignore` has `public/bundle.js` in it and my `now.json` has `"files": [ "public/bundle.js" ]` and `bundle.js` **doesn't** get uploaded

**Comment by kochie** [comment]
@Qix- I think your proposal looks like it would fix the issue to the satisfaction of most people in this thread. Do you need any help implementing it?

**Comment by Qix-** [comment]
@BassT which one gets precedence, though? If `files` is present, does `.gitignore` trump entries in `files`?

```
foo/
    bar.html
    qux.html
blah/
    bloo.html
    bleh.html
```

```gitignore
# .gitignore

/foo/*.html
/bar/bloo.html
```

```json
{
    "files": [ "foo", "blah" ]
}
```

In this situation, what are the resulting files that are sent up with the deployment?

In my solution, it'd be all four normal files (`bar.html`, `qux.html`, `bloo.html`, and `bleh.html`). Since Now isn't Git, it doesn't make a lot of sense to adhere to `.gitignore` here.

In your `.gitignore` proposal, it'd only be `bleh.html`, which IMO is counter-intuitive since it's in the `files` key but doesn't get deployed.

---

This is a problem for generated assets that are included in `.gitignore` but are intended to be uploaded as part of the deployment.

If you have a deployment that generates `out/` and you want `out/` to be part of the deployment, but you have it included in `.gitignore` in order to keep it out of revision control, then `out/` will never see the light of day under the '**and**' scenario.

My proposal was just to make things blatantly clear: Use `files` as the _sole_ authoritative whitelist for what gets uploaded (similar to how NPM does it) and fallback to `.gitignore` (if present) as a blacklist if `files` isn't present.

Seems simple enough to me. Like I said, I'd be interested in concrete use-cases where this would make impossible both the deployment of generated assets _and_ ignoring of artifacts out of revision control.

---

In a perfect world, we'd introduce something akin to `.nowignore`, though I know people dislike putting yet another dotfile in their repositories.

**Comment by BassT** [comment]
@Qix- It's been a while since I encountered the problem at first. I don't remember having a situation which couldn't be solved with your proposal. +1 for having using `files` as sole authoritative whitelist.

**Comment by mjswensen** [comment]
That seems like a great solution, @Qix- ! I like the idea of having `files` be authoritative, then falling back to smart defaults in its absence (using `.gitignore` and the like).

**Comment by kochie** [comment]
Hey all, I've created a PR that should fix this issue, please comment/discuss #1126

**Comment by rokf** [comment]
Same issue today. This should be pretty common with any dockerized projects that use binary files.

How come this issue isn't getting more attention? :worried:

**Comment by rauchg** [comment]
@rokf you're absolutely right. We are bumping the priority of this. Thank you
