### ISSUE TITLE
When `ctrl-c` is pressed during a deploy, ask user if they want to cancel deploy or show help info

### ISSUE THREAD

**Issue by vjpr** [vercel/vercel#752]
If I have a long deploy, or I remember I forgot to deploy something, I might want to cancel it from the cli.

When I press `ctrl+c`, my intention is to stop what it is currently doing.

Options:

a. Have a prompt that asks if you would like to cancel your build.
b. Print out instructions on exit of 
- the link to view deployment logs of your build online.
- the command to run to stop build `now rm...`
- the cli command to view deployment logs again #751

**Comment by leo** [comment]
This sounds like a very good idea! 👍 I would expect the same.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
