### ISSUE TITLE
Secret being set incorrectly

### ISSUE THREAD

**Issue by leo** [vercel/vercel#765]
_From @captDaylight on August 8, 2017 14:6_

setting a secret with:

`now secrets add email_pass "u5wV@#om$cLwAZC&mmlB3*2ly&Mm8bkv@54JOZ4N"`

is getting the secret passed to my app as:

`u5wV@#om&mmlB3*2ly&Mm8bkv@54JOZ4N`

I'll put them one on top of each other to inspect them easier, first the original and then the output.

```
u5wV@#om$cLwAZC&mmlB3*2ly&Mm8bkv@54JOZ4N
u5wV@#om&mmlB3*2ly&Mm8bkv@54JOZ4N
```

I fixed this by changing the value to only numbers and letters, but I imagine this is unexpected behavior.

_Copied from original issue: zeit/now#45_

**Comment by Qix-** [comment]
@captDaylight sorry for the delayed response - this is actually a side effect of your shell. The `$` is the culprit here - your shell is parsing all `\w+` characters as a variable, and since that shell variable doesn't exist, it gets replaced with an empty string.

That's why `$cLwAZC`  gets replaced - `&` is not a valid shell variable name, so your shell stops consuming characters when it sees the ampersand.

Either escape (`\$`) or use single quotes since single quotes treat contents as literals (and thus your shell won't try to expand anything that looks like a variable):

```console
$ now secrets add email_pass 'u5wV@#om$cLwAZC&mmlB3*2ly&Mm8bkv@54JOZ4N'
```

Hope that helps! 💃

**Comment by captDaylight** [comment]
Awesome, thanks for the thorough explanation. I'll go with single quotes :)
