### ISSUE TITLE
Deploying to AWS does not use now config

### ISSUE THREAD

**Issue by robinvdvleuten** [vercel/vercel#815]
When I try to deploy my app through `now aws`, the configuration in my `package.json` is not picked up at all. When I add a `now.json` instead, it works normally.

**Comment by Qix-** [comment]
Hi! 👋 

Apologies for the delay - are you still seeing this issue?

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
