### ISSUE TITLE
Display current team slug

### ISSUE THREAD

**Issue by chabou** [vercel/vercel#825]
It would be great to have a command to get current team name.

For now, I have to parse .now.json with 3 different ways (js, ruby, python) to adapt to user environnement. It would be really better to exec a command and not parsing now internals.
This is my current solution: https://github.com/chabou/pure-now/blob/v1.5.4/now_functions.zsh

I can make a PR for this new command if you give me its name.

Proposals:
* now teams current
* now teams info
* now teams show
* now teams status
* now info team slug

**Comment by leo** [comment]
We already have `now config`, so maybe `now config get` (like Git)? @matheuss @Qix- 

Example: `now config get currentTeam`
Another one for getting the email: `now config get user.email`

**Comment by Qix-** [comment]
Another option for OP's case specifically:

```console
$ now whoami --team
```

Otherwise, I like `now info` more than `now config`. Configuration is a subset of what `info` would provide, IMO.

**Comment by leo** [comment]
I would like to see consistency between the config props and the way you load them. Like, you shouldn't able to get `currentTeam.slug` using `now info team slug`, IMO.

**Comment by leo** [comment]
We definitely need a command for outputting the team slug. Maybe not a new command, though.

**Comment by nicobarray** [comment]
👍 on this, I cames here to create the same issue to make https://github.com/Hyperline/hyperline/pull/175 working without refetching the team/scope name.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
