### ISSUE TITLE
Add the ttl setting when  create record  

### ISSUE THREAD

**Issue by foxundermoon** [vercel/vercel#844]
add the ttl setting option  api
and add a param for cli

seemed like this 
`now dns add  my.io  shotttl 1.2.3.4  --ttl  60`

`now dns add  my.io  longttl 1.2.3.4  --ttl  12000`

**Comment by OlliV** [comment]
This feature will be definitely implemented.

**Comment by leo** [comment]
👍

**Comment by hyochan** [comment]
Any update on this?

**Comment by leo** [comment]
@hyochan Hey! We do think this is a great idea, however, we haven't yet had time to work on it.

🔜

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by ThaneshR** [comment]
Can we add ttl yet? I don't see it mentioned in the docs.

**Comment by greenisagoodcolor** [comment]
any progress on this? what is the default ttl setting?
