### ISSUE TITLE
SIGPIPE should kill now/cancel a deployment

### ISSUE THREAD

**Issue by Qix-** [vercel/vercel#846]
`SIGPIPE` is raised with a process if an output pipe for one of the standard file descriptors breaks during execution.

We need to cancel/roll back a deployment if `SIGPIPE` or `EPIPE` are raised via a signal or fd operation, respectively.

@rauchg pointed out [epipebomb](https://github.com/mhart/epipebomb) as an example for how some of these are handled.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
