### ISSUE TITLE
aws help submenu not implemented

### ISSUE THREAD

**Issue by kandros** [vercel/vercel#882]
currently it just prints `halp`
https://github.com/zeit/now-cli/blob/3e677e3a34e480c1ba07d780721d239b266869f9/src/providers/aws/help.js

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
