### ISSUE TITLE
 Cannot read property 'region'

### ISSUE THREAD

**Issue by orozcorp** [vercel/vercel#891]
> Error! An unexpected error occurred in provider deploy: TypeError: Cannot read property 'region' of undefined
    at deploy (/snapshot/now-cli/dist/now.js:12906:27)

where can I find the regions that are acceptable for the now.json file

**Comment by wushan** [comment]
I got the same error when trying to deploy to gcp.

here is my `now.json` setting file. Did i do anything wrong ?
```
{
  "name": "test-ui",
  "description": "test",
  "type": "nodejs",
  "regions": ["asia-east1-a"]
}
```

**Comment by wushan** [comment]
So it is not possible to deploy to gcp for now ?

**Comment by rauchg** [comment]
@wushan we're on it! We'll keep you posted :)

**Comment by wushan** [comment]
@rauchg so glad to hear that, I can't wait to shut all my vps down !

**Comment by matheuss** [comment]
@leo @orozcorp means AWS deployments – not now.sh deployments 😅 That's a bug – it should work!

**Comment by mrasoahaingo** [comment]
Can't wait for region deployment support!

**Comment by Qix-** [comment]
Sorry for the tag spam - I read @matheuss's comment a little too late :)

**Comment by mrasoahaingo** [comment]
Any updates for now.sh deployment?

**Comment by mtford90** [comment]
So am I getting this right? Is it only possible to deploy to US West (SFO) at the moment? Ideally i'd like to locate my instances in Europe so they're colocated with the rest of my cloud infrastructure.

The now homepage describes "Instant Global Deployments" - is this not the case?

Cheers!

**Comment by angleman** [comment]
@mtford90, I'm fairly sure global deployments is an objective of zeit as this isn't noted just on their home page. It is also on their twitter https://twitter.com/zeithq. As best as I can tell, SFO is the only datacenter at this time. This became apparent to us during a multi-hour service interruption Dec 28, https://zeit-status.co/  which caused our microservices to disappear. Still waiting for the post mortem.

Otherwise our experiencing with `now` is great. Our concerns is for service stability. Having multiple datacenters would enable us to more seriously consider using `now` for production. `now`, appears to be in the following spaces:
- CaaS (containers as a service, via docker), we have this successfully running with `now`
- PaaS (platform as a service), with scalable instances, Heroku alternative, we have several of these running with `now`
- FaaS (function as a service). Haven't tried this with `now` it was unclear the cli support it and we needed multiple datacenters right now so we deployed with AWS Lambda via `up` which was very smooth. Are considering https://serverless.com as they bring multiple providers to the table.

If zeit can provide all of these types of services across multiple data centers (and providers as they seemed to want to do with FaaS), along with their clean, fast and easy deployment process; then they could easily become a great provider as they would have the bases covered.

**Comment by clodal** [comment]
Now.sh introduced the BRU1 (Belgium) region 2 days ago. https://zeit.co/blog/multi-dc
