### ISSUE TITLE
Feature Request : optional assume role as `NOW_DEFAULT_IAM_ROLE`

### ISSUE THREAD

**Issue by dav009** [vercel/vercel#908]
In [here](https://github.com/zeit/now-cli/blob/master/src/providers/aws/deploy.js#L148) `now` tries to assume role as the default role. I would like to bypass that , and let `now` assume that Im on the role with the expected permissions.

Reasons for this, when I want to deploy I assume role as the intended deploy-role and authenticate to aws for a session that last only a short period of time.

**Comment by rauchg** [comment]
@dav009 sounds great. Why would you suggest env vs a CLI flag however?

**Comment by dav009** [comment]
> @dav009 sounds great. Why would you suggest env vs a CLI flag however?

 tools using aws usually get credentials in the following order :

  1. Environment variables. (AWS_SECRET_KEY..)
  2. Shared credentials file.
  3. IAM role

so having `now` checking the env variables would make it much more standard.

---

On a second note, I changed the mentioned block of code just to find that  a bit later there is another block of code that seems to assume role again [here](https://github.com/zeit/now-cli/blob/master/src/providers/aws/deploy.js#L177)

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
