### ISSUE TITLE
aws resources : new apigateway stage, lambda function version per deploy

### ISSUE THREAD

**Issue by dav009** [vercel/vercel#914]
running a few deploys via now, polluted my aws account with many api-gateways and lambda functions.

it seems every deploy creates its own whole set of resources.
but there are some aws limitations on for example deleting aws apigateways,
instead we could create a new  api-gateway stage on every deploy.

same applies for lambda functions, maybe it could rely on lambda function versions ?

**Comment by OlliV** [comment]
I have no idea about this.

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
