### ISSUE TITLE
Compress on the upload

### ISSUE THREAD

**Issue by tdurand** [vercel/vercel#941]
Hi, 

I think this won't be a priority, but it may worth it to be on your backlog.. and maybe it's a quick win.

I'm working on a super bad network in terms of upload those days and I get to deploy lots of time static prototypes with big JSON / txt files.. And I noticed those don't get compressed when sent over to the now.sh server. 

And for my use case this means that instead of needing to upload 100 MB of json, I would upload 20 MB or less if compressed. 

I noticed that because when I push to the git server, it is much faster as it's compressed.

Or maybe git is doing some other black magic.

BTW, it is so awesome you compare the previous deployment with the new one and just upload the delta.

Best, 

Thibault

**Comment by pranaygp** [comment]
Haven't gotten around to compression yet, but if you check out #953 uploads should now be a lot faster (HTTP/2 is awesome). It's currently only enabled in the canary channel, so maybe give it a shot and try using `now` in the latest canary release?

https://zeit.co/blog/canary

**Comment by rauchg** [comment]
Definitely love the idea of compressing uploads. A heuristic to avoid meaningless compression would have to be in place (like not compressing `.zip` files).

Thanks for sharing!

**Comment by tdurand** [comment]
@pranaygp great, I'll try to get on the canary version, but I guess for my use case HTTP2 won't improve much as it's single huges files and not 1000 small ones.

Happy you are considering implementing the compression !

All the best and let me know if you need me to test things, happy to do it.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
