### ISSUE TITLE
Old deployments

### ISSUE THREAD

**Issue by leo** [vercel/vercel#969]
This issue is an ongoing discussion about how old deployments should be displayed inside the CLI. As mentioned in #921, it might even make sense to introduce a way for automatically removing old deployments. But at the very least, they shouldn't show in `now ls`.

I think right now, we're only showing the 5 most recent. Maybe we should decrease that number?

**Comment by sholladay** [comment]
What is your definition of _old_ here? Some threshold of time after a deploy becomes frozen?

Personally, I expect `now ls` to show me everything. Or at least provide a `--all` flag so I can alias it in my dotfiles to make that the default behavior on my machines.

In https://github.com/zeit/now-cli/issues/691, I use the word _old_ to describe replaced deploys. That is, ones that used to be associated with an alias but no longer are because they were replaced in CI. Probably should have just said _replaced_ instead of _old_.

**Comment by Qix-** [comment]
I think the intent of "old" here means "deployments that I haven't `now rm`'d but that I don't necessarily care about anymore".

@sholladay makes a great point - users that use Now from within CI (as do we) will see a ton of old deployments scaled to 0 ("frozen") that we never care about.

Further, it becomes a bit of a liability since it's not immediately clear what's still being used (but maybe scaled to 0 _currently_), and what is _actually_ removable.

Something else to consider, too, is that there's the potential for many people to be looking at the list of deployments at a time, and if we're too liberal with arbitrary metrics for determining exactly _what_ to remove, there's a chance the state of a particular application and all of its instances might look different between team members.

Luckily there are some baseline metrics that can be used to classify these things that _isn't_ arbitrary. The first things I can think of are:

- The deployment _isn't_ prunable if it's aliased
- The deployment _isn't_ prunable if it's scaled to 0 ("frozen")
- The deployment _isn't necessarily_ prunable if it's static

So then it really comes down to determining a suitable threshold:

- Time based (e.g. last time it was scaled > 0 is more than 5 days ago)
- LRU based (e.g. prune down to at most 10 deployments, pruning the oldest first)

etc.

However, it's a bit arguable that this belongs in the now client. Since there are opinions at play here, I'm skeptical about how much of this pruning logic should live in the main `now-cli` package. These kinds of things kind of feel like an addon or third-party module (as @rtsao has done here: https://github.com/zeit/now-cli/pull/921#issuecomment-341598486).

Just my $0.02.

**Comment by sholladay** [comment]
@Qix- You described my thoughts pretty well. When I am deploying with the intent to ~~set~~ replace an alias, which happens a **ton** in CI, there is basically leftover garbage at the end that someone needs to clean up. I'd prefer to explicitly do that at deploy time.

I proposed a flag on the `now alias set` command that would clean up the garbage immediately. I still think this is the right approach. But it would really just be a shortcut for two commands...

```sh
ID=$(now get-deployment-id-for-alias my-app.com)
# ... set the alias to new deployment ...
now rm "$ID";
```

So if y'all really didn't want to implement the flag on `now alias` for some reason, then could you at least provide the ability to resolve an alias to a deployment ID as shown above? If you do that, then I can clean up the garbage myself after I set the alias.

The reason I would prefer a flag is:

1. It's shorter and more readable / intuitive to me.
2. You could make the action more atomic. It would be possible to implement it as one API call instead of two, etc.

Personally, I am against any time-based magic for garbage collection.

**Comment by Errorname** [comment]
Hi!
Any news on the issue ? I'm still looking for a way to remove old non-aliased deployments

**Comment by leo** [comment]
@Errorname Have you tried `now rm <name> --safe` yet? Removes all deployments with that name that are not aliased.

**Comment by Errorname** [comment]
Awesome, thanks! I should have read the documentation better 🙃

**Comment by sholladay** [comment]
FYI, `now rm --safe` is usually a bad idea, because it is too blunt a tool. What you really want is to remove the existing deployment after updating the alias. Something like this...
```sh
OLD_URL="$(now get-url-of-current-alias)"
now alias
now rm "$OLD_URL"
```
Unfortunately, I'm not aware of an easy way to do the first step, without brittle regex.

**Comment by leo** [comment]
Closing this, since we launched a new `now ls` a while ago (done by @rauchg).

**Comment by andyburke** [comment]
Can you describe what change in ```now ls``` makes this a non-issue?

I think this feature would be good to have, especially because I am not clear on what happens to older deployments that had been aliased and have a min scale.

**Comment by bigsee** [comment]
I would also be interested in knowing more about the change that solves this issue. I would like to specifically replace the aliased deployment, rather than delete all deployments that aren't aliased...

**Comment by sholladay** [comment]
They didn't fix it. It seems it's just not a priority for them.

**Comment by cryptiklemur** [comment]
@leo how does `now ls` solve this problem?

**Comment by styfle** [comment]
The new projects feature helps solve this. You can even delete a whole project with all deployments now. 

https://zeit.co/blog/projects
